// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/account.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountStatus is the lifecycle state of an account.
type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	// Provisioned but not yet verified/activated.
	AccountStatus_ACCOUNT_STATUS_PENDING AccountStatus = 1
	// Normal, usable account.
	AccountStatus_ACCOUNT_STATUS_ACTIVE AccountStatus = 2
	// Temporarily blocked by an operator or automated policy.
	AccountStatus_ACCOUNT_STATUS_SUSPENDED AccountStatus = 3
	// Soft-deleted; retained for referential integrity, not usable for login.
	AccountStatus_ACCOUNT_STATUS_DELETED AccountStatus = 4
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_PENDING",
		2: "ACCOUNT_STATUS_ACTIVE",
		3: "ACCOUNT_STATUS_SUSPENDED",
		4: "ACCOUNT_STATUS_DELETED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_PENDING":     1,
		"ACCOUNT_STATUS_ACTIVE":      2,
		"ACCOUNT_STATUS_SUSPENDED":   3,
		"ACCOUNT_STATUS_DELETED":     4,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_account_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_qwibi_v1_account_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{0}
}

// GlobalRole is a platform-wide capability tier, distinct from the per-layer
// membership roles defined in layer.proto. Most users hold only USER.
type GlobalRole int32

const (
	GlobalRole_GLOBAL_ROLE_UNSPECIFIED GlobalRole = 0
	// Created via anonymous credentials; limited capabilities, upgradeable.
	GlobalRole_GLOBAL_ROLE_ANONYMOUS GlobalRole = 1
	// Standard registered user.
	GlobalRole_GLOBAL_ROLE_USER GlobalRole = 2
	// Platform operator/administrator.
	GlobalRole_GLOBAL_ROLE_ADMIN GlobalRole = 3
)

// Enum value maps for GlobalRole.
var (
	GlobalRole_name = map[int32]string{
		0: "GLOBAL_ROLE_UNSPECIFIED",
		1: "GLOBAL_ROLE_ANONYMOUS",
		2: "GLOBAL_ROLE_USER",
		3: "GLOBAL_ROLE_ADMIN",
	}
	GlobalRole_value = map[string]int32{
		"GLOBAL_ROLE_UNSPECIFIED": 0,
		"GLOBAL_ROLE_ANONYMOUS":   1,
		"GLOBAL_ROLE_USER":        2,
		"GLOBAL_ROLE_ADMIN":       3,
	}
)

func (x GlobalRole) Enum() *GlobalRole {
	p := new(GlobalRole)
	*p = x
	return p
}

func (x GlobalRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalRole) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_account_proto_enumTypes[1].Descriptor()
}

func (GlobalRole) Type() protoreflect.EnumType {
	return &file_qwibi_v1_account_proto_enumTypes[1]
}

func (x GlobalRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalRole.Descriptor instead.
func (GlobalRole) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{1}
}

// PrincipalKind distinguishes human accounts, unbound service identities, App
// principals and organization principals. All are persisted as Account rows
// with stable IDs; APP and ORGANIZATION are linked from their owning aggregate.
type PrincipalKind int32

const (
	PrincipalKind_PRINCIPAL_KIND_UNSPECIFIED PrincipalKind = 0
	PrincipalKind_PRINCIPAL_KIND_ACCOUNT     PrincipalKind = 1
	PrincipalKind_PRINCIPAL_KIND_SERVICE     PrincipalKind = 2
	PrincipalKind_PRINCIPAL_KIND_APP         PrincipalKind = 3
	// One immutable non-human principal owned by exactly one Organization.
	PrincipalKind_PRINCIPAL_KIND_ORGANIZATION PrincipalKind = 4
)

// Enum value maps for PrincipalKind.
var (
	PrincipalKind_name = map[int32]string{
		0: "PRINCIPAL_KIND_UNSPECIFIED",
		1: "PRINCIPAL_KIND_ACCOUNT",
		2: "PRINCIPAL_KIND_SERVICE",
		3: "PRINCIPAL_KIND_APP",
		4: "PRINCIPAL_KIND_ORGANIZATION",
	}
	PrincipalKind_value = map[string]int32{
		"PRINCIPAL_KIND_UNSPECIFIED":  0,
		"PRINCIPAL_KIND_ACCOUNT":      1,
		"PRINCIPAL_KIND_SERVICE":      2,
		"PRINCIPAL_KIND_APP":          3,
		"PRINCIPAL_KIND_ORGANIZATION": 4,
	}
)

func (x PrincipalKind) Enum() *PrincipalKind {
	p := new(PrincipalKind)
	*p = x
	return p
}

func (x PrincipalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_account_proto_enumTypes[2].Descriptor()
}

func (PrincipalKind) Type() protoreflect.EnumType {
	return &file_qwibi_v1_account_proto_enumTypes[2]
}

func (x PrincipalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalKind.Descriptor instead.
func (PrincipalKind) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{2}
}

// AccountRelationKind identifies one directional moderation edge. Block is
// symmetric at delivery evaluation time; mute applies only from actor to target.
type AccountRelationKind int32

const (
	AccountRelationKind_ACCOUNT_RELATION_KIND_UNSPECIFIED AccountRelationKind = 0
	AccountRelationKind_ACCOUNT_RELATION_KIND_BLOCK       AccountRelationKind = 1
	AccountRelationKind_ACCOUNT_RELATION_KIND_MUTE        AccountRelationKind = 2
)

// Enum value maps for AccountRelationKind.
var (
	AccountRelationKind_name = map[int32]string{
		0: "ACCOUNT_RELATION_KIND_UNSPECIFIED",
		1: "ACCOUNT_RELATION_KIND_BLOCK",
		2: "ACCOUNT_RELATION_KIND_MUTE",
	}
	AccountRelationKind_value = map[string]int32{
		"ACCOUNT_RELATION_KIND_UNSPECIFIED": 0,
		"ACCOUNT_RELATION_KIND_BLOCK":       1,
		"ACCOUNT_RELATION_KIND_MUTE":        2,
	}
)

func (x AccountRelationKind) Enum() *AccountRelationKind {
	p := new(AccountRelationKind)
	*p = x
	return p
}

func (x AccountRelationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountRelationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_account_proto_enumTypes[3].Descriptor()
}

func (AccountRelationKind) Type() protoreflect.EnumType {
	return &file_qwibi_v1_account_proto_enumTypes[3]
}

func (x AccountRelationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountRelationKind.Descriptor instead.
func (AccountRelationKind) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{3}
}

// Account is the public projection of a user. It never carries secrets
// (password hashes, tokens); those live only in the auth/credential storage and
// are exchanged through auth.proto messages.
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7, stable public identifier and primary key.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Human-facing name. Never empty: auto-generated (e.g. "Guest-1a2b") if not set.
	DisplayName string        `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status      AccountStatus `protobuf:"varint,3,opt,name=status,proto3,enum=qwibi.v1.AccountStatus" json:"status,omitempty"`
	// Platform-wide roles held by the account. Self-reads only: populated only
	// when the caller reads their own account; any other account arrives as a
	// PublicAccount, which has no roles field at all.
	Roles []GlobalRole `protobuf:"varint,4,rep,packed,name=roles,proto3,enum=qwibi.v1.GlobalRole" json:"roles,omitempty"`
	// Optional avatar/profile image URL.
	AvatarUrl string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Public, user-chosen handle (username, e.g. "maggnus"); globally unique and
	// mutable. Empty if unset — the account is still addressable by uid.
	Hid string `protobuf:"bytes,8,opt,name=hid,proto3" json:"hid,omitempty"`
	// Email the account is registered/recoverable with, when it has an email login
	// (basic or magic-link). Empty for a purely anonymous account. This is the only
	// contact identifier surfaced publicly to the account's owner; it is derived
	// from the email credential, not a stored profile field. Self-reads only:
	// populated only when the caller reads their own account; any other account
	// arrives as a PublicAccount, which has no email field at all.
	Email         string        `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	Kind          PrincipalKind `protobuf:"varint,10,opt,name=kind,proto3,enum=qwibi.v1.PrincipalKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_qwibi_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Account) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetRoles() []GlobalRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Account) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Account) GetHid() string {
	if x != nil {
		return x.Hid
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetKind() PrincipalKind {
	if x != nil {
		return x.Kind
	}
	return PrincipalKind_PRINCIPAL_KIND_UNSPECIFIED
}

// PublicAccount is the projection of ANOTHER account — what any caller may see
// about someone else: never email, never roles. The absence of those fields is
// a contract-level PII guarantee, not a server behavior: the type a stranger
// receives cannot carry contact details or capability tiers.
type PublicAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7, stable public identifier and primary key.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Human-facing name. Never empty: auto-generated (e.g. "Guest-1a2b") if not set.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Public, user-chosen handle (username, e.g. "maggnus"); empty if unset.
	Hid string `protobuf:"bytes,3,opt,name=hid,proto3" json:"hid,omitempty"`
	// Optional avatar/profile image URL.
	AvatarUrl     string        `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Status        AccountStatus `protobuf:"varint,5,opt,name=status,proto3,enum=qwibi.v1.AccountStatus" json:"status,omitempty"`
	Kind          PrincipalKind `protobuf:"varint,6,opt,name=kind,proto3,enum=qwibi.v1.PrincipalKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicAccount) Reset() {
	*x = PublicAccount{}
	mi := &file_qwibi_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAccount) ProtoMessage() {}

func (x *PublicAccount) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAccount.ProtoReflect.Descriptor instead.
func (*PublicAccount) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *PublicAccount) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PublicAccount) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PublicAccount) GetHid() string {
	if x != nil {
		return x.Hid
	}
	return ""
}

func (x *PublicAccount) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PublicAccount) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *PublicAccount) GetKind() PrincipalKind {
	if x != nil {
		return x.Kind
	}
	return PrincipalKind_PRINCIPAL_KIND_UNSPECIFIED
}

// CreateAccountRequest registers a new account. Credentials to attach are
// supplied separately through Authenticate; this call establishes the profile.
type CreateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional desired display name for the new account.
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// GetAccountRequest fetches an account by public id. An empty id means "the
// currently authenticated account" (resolved from the call's credentials).
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// GetAccountResponse carries exactly one of the two projections: the full
// Account for a self-read, the PublicAccount for a read of anyone else.
type GetAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set only when the caller reads themself (full projection incl. email/roles).
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Set when reading any other account. Exactly one of the two is set.
	PublicAccount *PublicAccount `protobuf:"bytes,2,opt,name=public_account,json=publicAccount,proto3" json:"public_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountResponse) GetPublicAccount() *PublicAccount {
	if x != nil {
		return x.PublicAccount
	}
	return nil
}

// UpdateAccountRequest performs a partial update: only fields explicitly set
// (proto3 optional presence) are written; unset fields are left unchanged.
type UpdateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target account; empty id means the authenticated account.
	Uid         string  `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DisplayName *string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	AvatarUrl   *string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	// Set/rename the public handle; an empty string clears it. Globally unique.
	Hid           *string `protobuf:"bytes,4,opt,name=hid,proto3,oneof" json:"hid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UpdateAccountRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateAccountRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateAccountRequest) GetHid() string {
	if x != nil && x.Hid != nil {
		return *x.Hid
	}
	return ""
}

type UpdateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountResponse) Reset() {
	*x = UpdateAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountResponse) ProtoMessage() {}

func (x *UpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// DeleteAccountRequest deletes the caller's account (GDPR path): empty uid =
// self; only self-deletion is allowed. In one transaction the account is
// marked DELETED and its PII scrubbed (display name, handle, avatar,
// credentials, magic links), and every session dies; authored objects are
// anonymized (author cleared, content kept — shared layers stay intact) by the
// async purge; an empty personal org is removed. Blocked (FAILED_PRECONDITION)
// while the caller still solely owns an organization that has other members OR
// any live apps — transfer or delete those first (an ownerless app would be
// ungovernable). A service account cannot be deleted this way (PERMISSION_DENIED)
// — delete its app instead.
type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAccountRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{9}
}

// CheckHandleAvailableRequest checks whether a public @handle is free to claim,
// for live feedback while editing the profile.
type CheckHandleAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hid           string                 `protobuf:"bytes,1,opt,name=hid,proto3" json:"hid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHandleAvailableRequest) Reset() {
	*x = CheckHandleAvailableRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHandleAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHandleAvailableRequest) ProtoMessage() {}

func (x *CheckHandleAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHandleAvailableRequest.ProtoReflect.Descriptor instead.
func (*CheckHandleAvailableRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *CheckHandleAvailableRequest) GetHid() string {
	if x != nil {
		return x.Hid
	}
	return ""
}

type CheckHandleAvailableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the handle is free (or is already the caller's own current handle).
	Available bool `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	// Machine-readable reason when not available (e.g. "taken"); empty when available.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHandleAvailableResponse) Reset() {
	*x = CheckHandleAvailableResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHandleAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHandleAvailableResponse) ProtoMessage() {}

func (x *CheckHandleAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHandleAvailableResponse.ProtoReflect.Descriptor instead.
func (*CheckHandleAvailableResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *CheckHandleAvailableResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckHandleAvailableResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AccountRelation is one outgoing moderation edge owned by the caller. The
// actor is implicit and never accepted from or disclosed to another account.
type AccountRelation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	TargetAccountId string                 `protobuf:"bytes,2,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	Kind            AccountRelationKind    `protobuf:"varint,3,opt,name=kind,proto3,enum=qwibi.v1.AccountRelationKind" json:"kind,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountRelation) Reset() {
	*x = AccountRelation{}
	mi := &file_qwibi_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRelation) ProtoMessage() {}

func (x *AccountRelation) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRelation.ProtoReflect.Descriptor instead.
func (*AccountRelation) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *AccountRelation) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AccountRelation) GetTargetAccountId() string {
	if x != nil {
		return x.TargetAccountId
	}
	return ""
}

func (x *AccountRelation) GetKind() AccountRelationKind {
	if x != nil {
		return x.Kind
	}
	return AccountRelationKind_ACCOUNT_RELATION_KIND_UNSPECIFIED
}

func (x *AccountRelation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BlockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAccountRequest) Reset() {
	*x = BlockAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAccountRequest) ProtoMessage() {}

func (x *BlockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAccountRequest.ProtoReflect.Descriptor instead.
func (*BlockAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *BlockAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type BlockAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *AccountRelation       `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAccountResponse) Reset() {
	*x = BlockAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAccountResponse) ProtoMessage() {}

func (x *BlockAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAccountResponse.ProtoReflect.Descriptor instead.
func (*BlockAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *BlockAccountResponse) GetRelation() *AccountRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type UnblockAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAccountRequest) Reset() {
	*x = UnblockAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAccountRequest) ProtoMessage() {}

func (x *UnblockAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAccountRequest.ProtoReflect.Descriptor instead.
func (*UnblockAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{15}
}

func (x *UnblockAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UnblockAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAccountResponse) Reset() {
	*x = UnblockAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAccountResponse) ProtoMessage() {}

func (x *UnblockAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAccountResponse.ProtoReflect.Descriptor instead.
func (*UnblockAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{16}
}

type MuteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteAccountRequest) Reset() {
	*x = MuteAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteAccountRequest) ProtoMessage() {}

func (x *MuteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteAccountRequest.ProtoReflect.Descriptor instead.
func (*MuteAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{17}
}

func (x *MuteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type MuteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *AccountRelation       `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteAccountResponse) Reset() {
	*x = MuteAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteAccountResponse) ProtoMessage() {}

func (x *MuteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteAccountResponse.ProtoReflect.Descriptor instead.
func (*MuteAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{18}
}

func (x *MuteAccountResponse) GetRelation() *AccountRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type UnmuteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmuteAccountRequest) Reset() {
	*x = UnmuteAccountRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmuteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmuteAccountRequest) ProtoMessage() {}

func (x *UnmuteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmuteAccountRequest.ProtoReflect.Descriptor instead.
func (*UnmuteAccountRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{19}
}

func (x *UnmuteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UnmuteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmuteAccountResponse) Reset() {
	*x = UnmuteAccountResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmuteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmuteAccountResponse) ProtoMessage() {}

func (x *UnmuteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmuteAccountResponse.ProtoReflect.Descriptor instead.
func (*UnmuteAccountResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{20}
}

type ListAccountRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AccountRelationKind    `protobuf:"varint,1,opt,name=kind,proto3,enum=qwibi.v1.AccountRelationKind" json:"kind,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountRelationsRequest) Reset() {
	*x = ListAccountRelationsRequest{}
	mi := &file_qwibi_v1_account_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountRelationsRequest) ProtoMessage() {}

func (x *ListAccountRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountRelationsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountRelationsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{21}
}

func (x *ListAccountRelationsRequest) GetKind() AccountRelationKind {
	if x != nil {
		return x.Kind
	}
	return AccountRelationKind_ACCOUNT_RELATION_KIND_UNSPECIFIED
}

func (x *ListAccountRelationsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAccountRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*AccountRelation     `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountRelationsResponse) Reset() {
	*x = ListAccountRelationsResponse{}
	mi := &file_qwibi_v1_account_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountRelationsResponse) ProtoMessage() {}

func (x *ListAccountRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_account_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountRelationsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountRelationsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_account_proto_rawDescGZIP(), []int{22}
}

func (x *ListAccountRelationsResponse) GetRelations() []*AccountRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *ListAccountRelationsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_qwibi_v1_account_proto protoreflect.FileDescriptor

const file_qwibi_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x16qwibi/v1/account.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15qwibi/v1/common.proto\"\x93\x04\n" +
	"\aAccount\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x03uid\x12+\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vdisplayName\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.qwibi.v1.AccountStatusR\x06status\x12*\n" +
	"\x05roles\x18\x04 \x03(\x0e2\x14.qwibi.v1.GlobalRoleR\x05roles\x12'\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\tavatarUrl\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\x03hid\x18\b \x01(\tB$\xbaH!r\x1f2\x1d^$|^[a-z0-9][a-z0-9_-]{1,62}$R\x03hid\x12\x1e\n" +
	"\x05email\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\xfe\x01R\x05email\x12+\n" +
	"\x04kind\x18\n" +
	" \x01(\x0e2\x17.qwibi.v1.PrincipalKindR\x04kind\"\xd7\x02\n" +
	"\rPublicAccount\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x03uid\x12+\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vdisplayName\x126\n" +
	"\x03hid\x18\x03 \x01(\tB$\xbaH!r\x1f2\x1d^$|^[a-z0-9][a-z0-9_-]{1,62}$R\x03hid\x12'\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\tavatarUrl\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.qwibi.v1.AccountStatusR\x06status\x12+\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x17.qwibi.v1.PrincipalKindR\x04kind\"C\n" +
	"\x14CreateAccountRequest\x12+\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vdisplayName\"D\n" +
	"\x15CreateAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.qwibi.v1.AccountR\aaccount\"o\n" +
	"\x11GetAccountRequest\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2A^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\x03uid\"\x81\x01\n" +
	"\x12GetAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.qwibi.v1.AccountR\aaccount\x12>\n" +
	"\x0epublic_account\x18\x02 \x01(\v2\x17.qwibi.v1.PublicAccountR\rpublicAccount\"\xb7\x02\n" +
	"\x14UpdateAccountRequest\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2A^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\x03uid\x120\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02H\x00R\vdisplayName\x88\x01\x01\x12,\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10H\x01R\tavatarUrl\x88\x01\x01\x12;\n" +
	"\x03hid\x18\x04 \x01(\tB$\xbaH!r\x1f2\x1d^$|^[a-z0-9][a-z0-9_-]{1,62}$H\x02R\x03hid\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\r\n" +
	"\v_avatar_urlB\x06\n" +
	"\x04_hid\"D\n" +
	"\x15UpdateAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.qwibi.v1.AccountR\aaccount\"r\n" +
	"\x14DeleteAccountRequest\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2A^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\x03uid\"\x17\n" +
	"\x15DeleteAccountResponse\"R\n" +
	"\x1bCheckHandleAvailableRequest\x123\n" +
	"\x03hid\x18\x01 \x01(\tB!\xbaH\x1er\x1c2\x1a^[a-z0-9][a-z0-9_-]{1,62}$R\x03hid\"T\n" +
	"\x1cCheckHandleAvailableResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xdd\x02\n" +
	"\x0fAccountRelation\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x03uid\x12t\n" +
	"\x11target_account_id\x18\x02 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x0ftargetAccountId\x12=\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1d.qwibi.v1.AccountRelationKindB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04kind\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"~\n" +
	"\x13BlockAccountRequest\x12g\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\taccountId\"U\n" +
	"\x14BlockAccountResponse\x12=\n" +
	"\brelation\x18\x01 \x01(\v2\x19.qwibi.v1.AccountRelationB\x06\xbaH\x03\xc8\x01\x01R\brelation\"\x80\x01\n" +
	"\x15UnblockAccountRequest\x12g\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\taccountId\"\x18\n" +
	"\x16UnblockAccountResponse\"}\n" +
	"\x12MuteAccountRequest\x12g\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\taccountId\"T\n" +
	"\x13MuteAccountResponse\x12=\n" +
	"\brelation\x18\x01 \x01(\v2\x19.qwibi.v1.AccountRelationB\x06\xbaH\x03\xc8\x01\x01R\brelation\"\x7f\n" +
	"\x14UnmuteAccountRequest\x12g\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\taccountId\"\x17\n" +
	"\x15UnmuteAccountResponse\"\x87\x01\n" +
	"\x1bListAccountRelationsRequest\x12=\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.qwibi.v1.AccountRelationKindB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04kind\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.qwibi.v1.PageRequestR\x04page\"\x83\x01\n" +
	"\x1cListAccountRelationsResponse\x127\n" +
	"\trelations\x18\x01 \x03(\v2\x19.qwibi.v1.AccountRelationR\trelations\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.qwibi.v1.PageResponseR\x04page*\xa0\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x02\x12\x1c\n" +
	"\x18ACCOUNT_STATUS_SUSPENDED\x10\x03\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_DELETED\x10\x04*q\n" +
	"\n" +
	"GlobalRole\x12\x1b\n" +
	"\x17GLOBAL_ROLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GLOBAL_ROLE_ANONYMOUS\x10\x01\x12\x14\n" +
	"\x10GLOBAL_ROLE_USER\x10\x02\x12\x15\n" +
	"\x11GLOBAL_ROLE_ADMIN\x10\x03*\xa0\x01\n" +
	"\rPrincipalKind\x12\x1e\n" +
	"\x1aPRINCIPAL_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PRINCIPAL_KIND_ACCOUNT\x10\x01\x12\x1a\n" +
	"\x16PRINCIPAL_KIND_SERVICE\x10\x02\x12\x16\n" +
	"\x12PRINCIPAL_KIND_APP\x10\x03\x12\x1f\n" +
	"\x1bPRINCIPAL_KIND_ORGANIZATION\x10\x04*}\n" +
	"\x13AccountRelationKind\x12%\n" +
	"!ACCOUNT_RELATION_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bACCOUNT_RELATION_KIND_BLOCK\x10\x01\x12\x1e\n" +
	"\x1aACCOUNT_RELATION_KIND_MUTE\x10\x02B\x8f\x01\n" +
	"\fcom.qwibi.v1B\fAccountProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_account_proto_rawDescOnce sync.Once
	file_qwibi_v1_account_proto_rawDescData []byte
)

func file_qwibi_v1_account_proto_rawDescGZIP() []byte {
	file_qwibi_v1_account_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_account_proto_rawDesc), len(file_qwibi_v1_account_proto_rawDesc)))
	})
	return file_qwibi_v1_account_proto_rawDescData
}

var file_qwibi_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_qwibi_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_qwibi_v1_account_proto_goTypes = []any{
	(AccountStatus)(0),                   // 0: qwibi.v1.AccountStatus
	(GlobalRole)(0),                      // 1: qwibi.v1.GlobalRole
	(PrincipalKind)(0),                   // 2: qwibi.v1.PrincipalKind
	(AccountRelationKind)(0),             // 3: qwibi.v1.AccountRelationKind
	(*Account)(nil),                      // 4: qwibi.v1.Account
	(*PublicAccount)(nil),                // 5: qwibi.v1.PublicAccount
	(*CreateAccountRequest)(nil),         // 6: qwibi.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),        // 7: qwibi.v1.CreateAccountResponse
	(*GetAccountRequest)(nil),            // 8: qwibi.v1.GetAccountRequest
	(*GetAccountResponse)(nil),           // 9: qwibi.v1.GetAccountResponse
	(*UpdateAccountRequest)(nil),         // 10: qwibi.v1.UpdateAccountRequest
	(*UpdateAccountResponse)(nil),        // 11: qwibi.v1.UpdateAccountResponse
	(*DeleteAccountRequest)(nil),         // 12: qwibi.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),        // 13: qwibi.v1.DeleteAccountResponse
	(*CheckHandleAvailableRequest)(nil),  // 14: qwibi.v1.CheckHandleAvailableRequest
	(*CheckHandleAvailableResponse)(nil), // 15: qwibi.v1.CheckHandleAvailableResponse
	(*AccountRelation)(nil),              // 16: qwibi.v1.AccountRelation
	(*BlockAccountRequest)(nil),          // 17: qwibi.v1.BlockAccountRequest
	(*BlockAccountResponse)(nil),         // 18: qwibi.v1.BlockAccountResponse
	(*UnblockAccountRequest)(nil),        // 19: qwibi.v1.UnblockAccountRequest
	(*UnblockAccountResponse)(nil),       // 20: qwibi.v1.UnblockAccountResponse
	(*MuteAccountRequest)(nil),           // 21: qwibi.v1.MuteAccountRequest
	(*MuteAccountResponse)(nil),          // 22: qwibi.v1.MuteAccountResponse
	(*UnmuteAccountRequest)(nil),         // 23: qwibi.v1.UnmuteAccountRequest
	(*UnmuteAccountResponse)(nil),        // 24: qwibi.v1.UnmuteAccountResponse
	(*ListAccountRelationsRequest)(nil),  // 25: qwibi.v1.ListAccountRelationsRequest
	(*ListAccountRelationsResponse)(nil), // 26: qwibi.v1.ListAccountRelationsResponse
	(*timestamppb.Timestamp)(nil),        // 27: google.protobuf.Timestamp
	(*PageRequest)(nil),                  // 28: qwibi.v1.PageRequest
	(*PageResponse)(nil),                 // 29: qwibi.v1.PageResponse
}
var file_qwibi_v1_account_proto_depIdxs = []int32{
	0,  // 0: qwibi.v1.Account.status:type_name -> qwibi.v1.AccountStatus
	1,  // 1: qwibi.v1.Account.roles:type_name -> qwibi.v1.GlobalRole
	27, // 2: qwibi.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	27, // 3: qwibi.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: qwibi.v1.Account.kind:type_name -> qwibi.v1.PrincipalKind
	0,  // 5: qwibi.v1.PublicAccount.status:type_name -> qwibi.v1.AccountStatus
	2,  // 6: qwibi.v1.PublicAccount.kind:type_name -> qwibi.v1.PrincipalKind
	4,  // 7: qwibi.v1.CreateAccountResponse.account:type_name -> qwibi.v1.Account
	4,  // 8: qwibi.v1.GetAccountResponse.account:type_name -> qwibi.v1.Account
	5,  // 9: qwibi.v1.GetAccountResponse.public_account:type_name -> qwibi.v1.PublicAccount
	4,  // 10: qwibi.v1.UpdateAccountResponse.account:type_name -> qwibi.v1.Account
	3,  // 11: qwibi.v1.AccountRelation.kind:type_name -> qwibi.v1.AccountRelationKind
	27, // 12: qwibi.v1.AccountRelation.created_at:type_name -> google.protobuf.Timestamp
	16, // 13: qwibi.v1.BlockAccountResponse.relation:type_name -> qwibi.v1.AccountRelation
	16, // 14: qwibi.v1.MuteAccountResponse.relation:type_name -> qwibi.v1.AccountRelation
	3,  // 15: qwibi.v1.ListAccountRelationsRequest.kind:type_name -> qwibi.v1.AccountRelationKind
	28, // 16: qwibi.v1.ListAccountRelationsRequest.page:type_name -> qwibi.v1.PageRequest
	16, // 17: qwibi.v1.ListAccountRelationsResponse.relations:type_name -> qwibi.v1.AccountRelation
	29, // 18: qwibi.v1.ListAccountRelationsResponse.page:type_name -> qwibi.v1.PageResponse
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_qwibi_v1_account_proto_init() }
func file_qwibi_v1_account_proto_init() {
	if File_qwibi_v1_account_proto != nil {
		return
	}
	file_qwibi_v1_common_proto_init()
	file_qwibi_v1_account_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_account_proto_rawDesc), len(file_qwibi_v1_account_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_v1_account_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_account_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_account_proto_enumTypes,
		MessageInfos:      file_qwibi_v1_account_proto_msgTypes,
	}.Build()
	File_qwibi_v1_account_proto = out.File
	file_qwibi_v1_account_proto_goTypes = nil
	file_qwibi_v1_account_proto_depIdxs = nil
}
