// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/app_installation.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppInstallationStatus int32

const (
	AppInstallationStatus_APP_INSTALLATION_STATUS_UNSPECIFIED AppInstallationStatus = 0
	AppInstallationStatus_APP_INSTALLATION_STATUS_ACTIVE      AppInstallationStatus = 2
	AppInstallationStatus_APP_INSTALLATION_STATUS_SUSPENDED   AppInstallationStatus = 4
	AppInstallationStatus_APP_INSTALLATION_STATUS_REMOVED     AppInstallationStatus = 5
)

// Enum value maps for AppInstallationStatus.
var (
	AppInstallationStatus_name = map[int32]string{
		0: "APP_INSTALLATION_STATUS_UNSPECIFIED",
		2: "APP_INSTALLATION_STATUS_ACTIVE",
		4: "APP_INSTALLATION_STATUS_SUSPENDED",
		5: "APP_INSTALLATION_STATUS_REMOVED",
	}
	AppInstallationStatus_value = map[string]int32{
		"APP_INSTALLATION_STATUS_UNSPECIFIED": 0,
		"APP_INSTALLATION_STATUS_ACTIVE":      2,
		"APP_INSTALLATION_STATUS_SUSPENDED":   4,
		"APP_INSTALLATION_STATUS_REMOVED":     5,
	}
)

func (x AppInstallationStatus) Enum() *AppInstallationStatus {
	p := new(AppInstallationStatus)
	*p = x
	return p
}

func (x AppInstallationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppInstallationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_app_installation_proto_enumTypes[0].Descriptor()
}

func (AppInstallationStatus) Type() protoreflect.EnumType {
	return &file_qwibi_v1_app_installation_proto_enumTypes[0]
}

func (x AppInstallationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppInstallationStatus.Descriptor instead.
func (AppInstallationStatus) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{0}
}

type AppActionUnavailableReason int32

const (
	AppActionUnavailableReason_APP_ACTION_UNAVAILABLE_REASON_UNSPECIFIED              AppActionUnavailableReason = 0
	AppActionUnavailableReason_APP_ACTION_UNAVAILABLE_REASON_INSTALLATION_NOT_SERVING AppActionUnavailableReason = 1
	// The action remains discoverable and can be used after this reader allows
	// one of its declared sensitive rights.
	AppActionUnavailableReason_APP_ACTION_UNAVAILABLE_REASON_CONSENT_REQUIRED AppActionUnavailableReason = 3
)

// Enum value maps for AppActionUnavailableReason.
var (
	AppActionUnavailableReason_name = map[int32]string{
		0: "APP_ACTION_UNAVAILABLE_REASON_UNSPECIFIED",
		1: "APP_ACTION_UNAVAILABLE_REASON_INSTALLATION_NOT_SERVING",
		3: "APP_ACTION_UNAVAILABLE_REASON_CONSENT_REQUIRED",
	}
	AppActionUnavailableReason_value = map[string]int32{
		"APP_ACTION_UNAVAILABLE_REASON_UNSPECIFIED":              0,
		"APP_ACTION_UNAVAILABLE_REASON_INSTALLATION_NOT_SERVING": 1,
		"APP_ACTION_UNAVAILABLE_REASON_CONSENT_REQUIRED":         3,
	}
)

func (x AppActionUnavailableReason) Enum() *AppActionUnavailableReason {
	p := new(AppActionUnavailableReason)
	*p = x
	return p
}

func (x AppActionUnavailableReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppActionUnavailableReason) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_app_installation_proto_enumTypes[1].Descriptor()
}

func (AppActionUnavailableReason) Type() protoreflect.EnumType {
	return &file_qwibi_v1_app_installation_proto_enumTypes[1]
}

func (x AppActionUnavailableReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppActionUnavailableReason.Descriptor instead.
func (AppActionUnavailableReason) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{1}
}

type InstallationParticipantConsentDecision int32

const (
	InstallationParticipantConsentDecision_INSTALLATION_PARTICIPANT_CONSENT_DECISION_UNSPECIFIED InstallationParticipantConsentDecision = 0
	InstallationParticipantConsentDecision_INSTALLATION_PARTICIPANT_CONSENT_DECISION_CONSENTED   InstallationParticipantConsentDecision = 1
	InstallationParticipantConsentDecision_INSTALLATION_PARTICIPANT_CONSENT_DECISION_WITHDRAWN   InstallationParticipantConsentDecision = 2
)

// Enum value maps for InstallationParticipantConsentDecision.
var (
	InstallationParticipantConsentDecision_name = map[int32]string{
		0: "INSTALLATION_PARTICIPANT_CONSENT_DECISION_UNSPECIFIED",
		1: "INSTALLATION_PARTICIPANT_CONSENT_DECISION_CONSENTED",
		2: "INSTALLATION_PARTICIPANT_CONSENT_DECISION_WITHDRAWN",
	}
	InstallationParticipantConsentDecision_value = map[string]int32{
		"INSTALLATION_PARTICIPANT_CONSENT_DECISION_UNSPECIFIED": 0,
		"INSTALLATION_PARTICIPANT_CONSENT_DECISION_CONSENTED":   1,
		"INSTALLATION_PARTICIPANT_CONSENT_DECISION_WITHDRAWN":   2,
	}
)

func (x InstallationParticipantConsentDecision) Enum() *InstallationParticipantConsentDecision {
	p := new(InstallationParticipantConsentDecision)
	*p = x
	return p
}

func (x InstallationParticipantConsentDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallationParticipantConsentDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_app_installation_proto_enumTypes[2].Descriptor()
}

func (InstallationParticipantConsentDecision) Type() protoreflect.EnumType {
	return &file_qwibi_v1_app_installation_proto_enumTypes[2]
}

func (x InstallationParticipantConsentDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallationParticipantConsentDecision.Descriptor instead.
func (InstallationParticipantConsentDecision) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{2}
}

type AppActionAvailability struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	ActionId          string                     `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Available         bool                       `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	UnavailableReason AppActionUnavailableReason `protobuf:"varint,3,opt,name=unavailable_reason,json=unavailableReason,proto3,enum=qwibi.v1.AppActionUnavailableReason" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppActionAvailability) Reset() {
	*x = AppActionAvailability{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppActionAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppActionAvailability) ProtoMessage() {}

func (x *AppActionAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppActionAvailability.ProtoReflect.Descriptor instead.
func (*AppActionAvailability) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{0}
}

func (x *AppActionAvailability) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *AppActionAvailability) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *AppActionAvailability) GetUnavailableReason() AppActionUnavailableReason {
	if x != nil {
		return x.UnavailableReason
	}
	return AppActionUnavailableReason_APP_ACTION_UNAVAILABLE_REASON_UNSPECIFIED
}

// The App selects the release once at publication; no installation pins one.
type AppInstallation struct {
	state                    protoimpl.MessageState   `protogen:"open.v1"`
	InstallationId           string                   `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	LayerId                  string                   `protobuf:"bytes,2,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	AppId                    string                   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	InstalledByAccountId     string                   `protobuf:"bytes,5,opt,name=installed_by_account_id,json=installedByAccountId,proto3" json:"installed_by_account_id,omitempty"`
	Status                   AppInstallationStatus    `protobuf:"varint,6,opt,name=status,proto3,enum=qwibi.v1.AppInstallationStatus" json:"status,omitempty"`
	LifecycleRevision        uint64                   `protobuf:"varint,9,opt,name=lifecycle_revision,json=lifecycleRevision,proto3" json:"lifecycle_revision,omitempty"`
	CreatedAt                *timestamppb.Timestamp   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ActivatedAt              *timestamppb.Timestamp   `protobuf:"bytes,11,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	UpdatedAt                *timestamppb.Timestamp   `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SuspendedAt              *timestamppb.Timestamp   `protobuf:"bytes,13,opt,name=suspended_at,json=suspendedAt,proto3" json:"suspended_at,omitempty"`
	RemovedAt                *timestamppb.Timestamp   `protobuf:"bytes,14,opt,name=removed_at,json=removedAt,proto3" json:"removed_at,omitempty"`
	ActiveActionAvailability []*AppActionAvailability `protobuf:"bytes,15,rep,name=active_action_availability,json=activeActionAvailability,proto3" json:"active_action_availability,omitempty"`
	// Read-only presentation of an active App-owned block. Only this Layer's
	// owners and editors receive these fields; other readers receive defaults.
	// Neither the block id nor its source key/call id leaves the server.
	BlockedByApp    bool   `protobuf:"varint,16,opt,name=blocked_by_app,json=blockedByApp,proto3" json:"blocked_by_app,omitempty"`
	BlockingAppName string `protobuf:"bytes,17,opt,name=blocking_app_name,json=blockingAppName,proto3" json:"blocking_app_name,omitempty"`
	BlockReason     string `protobuf:"bytes,18,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	// The installed App's display name and access level, served with the
	// installation so a map's owners and editors see every App added to their
	// map, a private one included, even when they are not its members and may
	// not read the App itself. A reader who may not use a private App never
	// receives its installation at all.
	AppName        string         `protobuf:"bytes,19,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppAccessLevel AppAccessLevel `protobuf:"varint,20,opt,name=app_access_level,json=appAccessLevel,proto3,enum=qwibi.v1.AppAccessLevel" json:"app_access_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppInstallation) Reset() {
	*x = AppInstallation{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInstallation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInstallation) ProtoMessage() {}

func (x *AppInstallation) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInstallation.ProtoReflect.Descriptor instead.
func (*AppInstallation) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{1}
}

func (x *AppInstallation) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *AppInstallation) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *AppInstallation) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppInstallation) GetInstalledByAccountId() string {
	if x != nil {
		return x.InstalledByAccountId
	}
	return ""
}

func (x *AppInstallation) GetStatus() AppInstallationStatus {
	if x != nil {
		return x.Status
	}
	return AppInstallationStatus_APP_INSTALLATION_STATUS_UNSPECIFIED
}

func (x *AppInstallation) GetLifecycleRevision() uint64 {
	if x != nil {
		return x.LifecycleRevision
	}
	return 0
}

func (x *AppInstallation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppInstallation) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *AppInstallation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AppInstallation) GetSuspendedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SuspendedAt
	}
	return nil
}

func (x *AppInstallation) GetRemovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RemovedAt
	}
	return nil
}

func (x *AppInstallation) GetActiveActionAvailability() []*AppActionAvailability {
	if x != nil {
		return x.ActiveActionAvailability
	}
	return nil
}

func (x *AppInstallation) GetBlockedByApp() bool {
	if x != nil {
		return x.BlockedByApp
	}
	return false
}

func (x *AppInstallation) GetBlockingAppName() string {
	if x != nil {
		return x.BlockingAppName
	}
	return ""
}

func (x *AppInstallation) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

func (x *AppInstallation) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppInstallation) GetAppAccessLevel() AppAccessLevel {
	if x != nil {
		return x.AppAccessLevel
	}
	return AppAccessLevel_APP_ACCESS_LEVEL_UNSPECIFIED
}

type InstallationParticipantConsent struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	AppId         string                                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountId     string                                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Right         AppRight                               `protobuf:"varint,3,opt,name=right,proto3,enum=qwibi.v1.AppRight" json:"right,omitempty"`
	Decision      InstallationParticipantConsentDecision `protobuf:"varint,5,opt,name=decision,proto3,enum=qwibi.v1.InstallationParticipantConsentDecision" json:"decision,omitempty"`
	DecidedAt     *timestamppb.Timestamp                 `protobuf:"bytes,6,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallationParticipantConsent) Reset() {
	*x = InstallationParticipantConsent{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallationParticipantConsent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallationParticipantConsent) ProtoMessage() {}

func (x *InstallationParticipantConsent) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallationParticipantConsent.ProtoReflect.Descriptor instead.
func (*InstallationParticipantConsent) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{2}
}

func (x *InstallationParticipantConsent) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *InstallationParticipantConsent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *InstallationParticipantConsent) GetRight() AppRight {
	if x != nil {
		return x.Right
	}
	return AppRight_APP_RIGHT_UNSPECIFIED
}

func (x *InstallationParticipantConsent) GetDecision() InstallationParticipantConsentDecision {
	if x != nil {
		return x.Decision
	}
	return InstallationParticipantConsentDecision_INSTALLATION_PARTICIPANT_CONSENT_DECISION_UNSPECIFIED
}

func (x *InstallationParticipantConsent) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

type InstallAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayerId       string                 `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppRequest) Reset() {
	*x = InstallAppRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppRequest) ProtoMessage() {}

func (x *InstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppRequest.ProtoReflect.Descriptor instead.
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{3}
}

func (x *InstallAppRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *InstallAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type InstallAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installation  *AppInstallation       `protobuf:"bytes,1,opt,name=installation,proto3" json:"installation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppResponse) Reset() {
	*x = InstallAppResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppResponse) ProtoMessage() {}

func (x *InstallAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppResponse.ProtoReflect.Descriptor instead.
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{4}
}

func (x *InstallAppResponse) GetInstallation() *AppInstallation {
	if x != nil {
		return x.Installation
	}
	return nil
}

// Adds an App to the caller's private My map, creating that Layer on first use.
type AddAppToMyMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppToMyMapRequest) Reset() {
	*x = AddAppToMyMapRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppToMyMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppToMyMapRequest) ProtoMessage() {}

func (x *AddAppToMyMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppToMyMapRequest.ProtoReflect.Descriptor instead.
func (*AddAppToMyMapRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{5}
}

func (x *AddAppToMyMapRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type AddAppToMyMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayerId       string                 `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	Installation  *AppInstallation       `protobuf:"bytes,2,opt,name=installation,proto3" json:"installation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppToMyMapResponse) Reset() {
	*x = AddAppToMyMapResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppToMyMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppToMyMapResponse) ProtoMessage() {}

func (x *AddAppToMyMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppToMyMapResponse.ProtoReflect.Descriptor instead.
func (*AddAppToMyMapResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{6}
}

func (x *AddAppToMyMapResponse) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *AddAppToMyMapResponse) GetInstallation() *AppInstallation {
	if x != nil {
		return x.Installation
	}
	return nil
}

type GetAppInstallationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAppInstallationRequest) Reset() {
	*x = GetAppInstallationRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppInstallationRequest) ProtoMessage() {}

func (x *GetAppInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppInstallationRequest.ProtoReflect.Descriptor instead.
func (*GetAppInstallationRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{7}
}

func (x *GetAppInstallationRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

type GetAppInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installation  *AppInstallation       `protobuf:"bytes,1,opt,name=installation,proto3" json:"installation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppInstallationResponse) Reset() {
	*x = GetAppInstallationResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppInstallationResponse) ProtoMessage() {}

func (x *GetAppInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppInstallationResponse.ProtoReflect.Descriptor instead.
func (*GetAppInstallationResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{8}
}

func (x *GetAppInstallationResponse) GetInstallation() *AppInstallation {
	if x != nil {
		return x.Installation
	}
	return nil
}

type ListAppInstallationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayerId       string                 `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppInstallationsRequest) Reset() {
	*x = ListAppInstallationsRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppInstallationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppInstallationsRequest) ProtoMessage() {}

func (x *ListAppInstallationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppInstallationsRequest.ProtoReflect.Descriptor instead.
func (*ListAppInstallationsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{9}
}

func (x *ListAppInstallationsRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *ListAppInstallationsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAppInstallationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installations []*AppInstallation     `protobuf:"bytes,1,rep,name=installations,proto3" json:"installations,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppInstallationsResponse) Reset() {
	*x = ListAppInstallationsResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppInstallationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppInstallationsResponse) ProtoMessage() {}

func (x *ListAppInstallationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppInstallationsResponse.ProtoReflect.Descriptor instead.
func (*ListAppInstallationsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{10}
}

func (x *ListAppInstallationsResponse) GetInstallations() []*AppInstallation {
	if x != nil {
		return x.Installations
	}
	return nil
}

func (x *ListAppInstallationsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type SuspendAppInstallationRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	InstallationId            string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	ExpectedLifecycleRevision uint64                 `protobuf:"varint,2,opt,name=expected_lifecycle_revision,json=expectedLifecycleRevision,proto3" json:"expected_lifecycle_revision,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SuspendAppInstallationRequest) Reset() {
	*x = SuspendAppInstallationRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendAppInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendAppInstallationRequest) ProtoMessage() {}

func (x *SuspendAppInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendAppInstallationRequest.ProtoReflect.Descriptor instead.
func (*SuspendAppInstallationRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{11}
}

func (x *SuspendAppInstallationRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *SuspendAppInstallationRequest) GetExpectedLifecycleRevision() uint64 {
	if x != nil {
		return x.ExpectedLifecycleRevision
	}
	return 0
}

type SuspendAppInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installation  *AppInstallation       `protobuf:"bytes,1,opt,name=installation,proto3" json:"installation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendAppInstallationResponse) Reset() {
	*x = SuspendAppInstallationResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendAppInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendAppInstallationResponse) ProtoMessage() {}

func (x *SuspendAppInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendAppInstallationResponse.ProtoReflect.Descriptor instead.
func (*SuspendAppInstallationResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{12}
}

func (x *SuspendAppInstallationResponse) GetInstallation() *AppInstallation {
	if x != nil {
		return x.Installation
	}
	return nil
}

type ResumeAppInstallationRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	InstallationId            string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	ExpectedLifecycleRevision uint64                 `protobuf:"varint,2,opt,name=expected_lifecycle_revision,json=expectedLifecycleRevision,proto3" json:"expected_lifecycle_revision,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ResumeAppInstallationRequest) Reset() {
	*x = ResumeAppInstallationRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAppInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAppInstallationRequest) ProtoMessage() {}

func (x *ResumeAppInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAppInstallationRequest.ProtoReflect.Descriptor instead.
func (*ResumeAppInstallationRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{13}
}

func (x *ResumeAppInstallationRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *ResumeAppInstallationRequest) GetExpectedLifecycleRevision() uint64 {
	if x != nil {
		return x.ExpectedLifecycleRevision
	}
	return 0
}

type ResumeAppInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installation  *AppInstallation       `protobuf:"bytes,1,opt,name=installation,proto3" json:"installation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAppInstallationResponse) Reset() {
	*x = ResumeAppInstallationResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAppInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAppInstallationResponse) ProtoMessage() {}

func (x *ResumeAppInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAppInstallationResponse.ProtoReflect.Descriptor instead.
func (*ResumeAppInstallationResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{14}
}

func (x *ResumeAppInstallationResponse) GetInstallation() *AppInstallation {
	if x != nil {
		return x.Installation
	}
	return nil
}

type RemoveAppInstallationRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	InstallationId            string                 `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	ExpectedLifecycleRevision uint64                 `protobuf:"varint,2,opt,name=expected_lifecycle_revision,json=expectedLifecycleRevision,proto3" json:"expected_lifecycle_revision,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RemoveAppInstallationRequest) Reset() {
	*x = RemoveAppInstallationRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAppInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAppInstallationRequest) ProtoMessage() {}

func (x *RemoveAppInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAppInstallationRequest.ProtoReflect.Descriptor instead.
func (*RemoveAppInstallationRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveAppInstallationRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *RemoveAppInstallationRequest) GetExpectedLifecycleRevision() uint64 {
	if x != nil {
		return x.ExpectedLifecycleRevision
	}
	return 0
}

type RemoveAppInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installation  *AppInstallation       `protobuf:"bytes,1,opt,name=installation,proto3" json:"installation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAppInstallationResponse) Reset() {
	*x = RemoveAppInstallationResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAppInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAppInstallationResponse) ProtoMessage() {}

func (x *RemoveAppInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAppInstallationResponse.ProtoReflect.Descriptor instead.
func (*RemoveAppInstallationResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveAppInstallationResponse) GetInstallation() *AppInstallation {
	if x != nil {
		return x.Installation
	}
	return nil
}

type SetInstallationParticipantConsentRequest struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	AppId         string                                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Right         AppRight                               `protobuf:"varint,2,opt,name=right,proto3,enum=qwibi.v1.AppRight" json:"right,omitempty"`
	Decision      InstallationParticipantConsentDecision `protobuf:"varint,4,opt,name=decision,proto3,enum=qwibi.v1.InstallationParticipantConsentDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstallationParticipantConsentRequest) Reset() {
	*x = SetInstallationParticipantConsentRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstallationParticipantConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstallationParticipantConsentRequest) ProtoMessage() {}

func (x *SetInstallationParticipantConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstallationParticipantConsentRequest.ProtoReflect.Descriptor instead.
func (*SetInstallationParticipantConsentRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{17}
}

func (x *SetInstallationParticipantConsentRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetInstallationParticipantConsentRequest) GetRight() AppRight {
	if x != nil {
		return x.Right
	}
	return AppRight_APP_RIGHT_UNSPECIFIED
}

func (x *SetInstallationParticipantConsentRequest) GetDecision() InstallationParticipantConsentDecision {
	if x != nil {
		return x.Decision
	}
	return InstallationParticipantConsentDecision_INSTALLATION_PARTICIPANT_CONSENT_DECISION_UNSPECIFIED
}

type SetInstallationParticipantConsentResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Consent       *InstallationParticipantConsent `protobuf:"bytes,1,opt,name=consent,proto3" json:"consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstallationParticipantConsentResponse) Reset() {
	*x = SetInstallationParticipantConsentResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstallationParticipantConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstallationParticipantConsentResponse) ProtoMessage() {}

func (x *SetInstallationParticipantConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstallationParticipantConsentResponse.ProtoReflect.Descriptor instead.
func (*SetInstallationParticipantConsentResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{18}
}

func (x *SetInstallationParticipantConsentResponse) GetConsent() *InstallationParticipantConsent {
	if x != nil {
		return x.Consent
	}
	return nil
}

type ListMyInstallationParticipantConsentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyInstallationParticipantConsentsRequest) Reset() {
	*x = ListMyInstallationParticipantConsentsRequest{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyInstallationParticipantConsentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyInstallationParticipantConsentsRequest) ProtoMessage() {}

func (x *ListMyInstallationParticipantConsentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyInstallationParticipantConsentsRequest.ProtoReflect.Descriptor instead.
func (*ListMyInstallationParticipantConsentsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{19}
}

func (x *ListMyInstallationParticipantConsentsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListMyInstallationParticipantConsentsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListMyInstallationParticipantConsentsResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Consents      []*InstallationParticipantConsent `protobuf:"bytes,1,rep,name=consents,proto3" json:"consents,omitempty"`
	Page          *PageResponse                     `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyInstallationParticipantConsentsResponse) Reset() {
	*x = ListMyInstallationParticipantConsentsResponse{}
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyInstallationParticipantConsentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyInstallationParticipantConsentsResponse) ProtoMessage() {}

func (x *ListMyInstallationParticipantConsentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_installation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyInstallationParticipantConsentsResponse.ProtoReflect.Descriptor instead.
func (*ListMyInstallationParticipantConsentsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_installation_proto_rawDescGZIP(), []int{20}
}

func (x *ListMyInstallationParticipantConsentsResponse) GetConsents() []*InstallationParticipantConsent {
	if x != nil {
		return x.Consents
	}
	return nil
}

func (x *ListMyInstallationParticipantConsentsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_qwibi_v1_app_installation_proto protoreflect.FileDescriptor

const file_qwibi_v1_app_installation_proto_rawDesc = "" +
	"\n" +
	"\x1fqwibi/v1/app_installation.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12qwibi/v1/app.proto\x1a\x1aqwibi/v1/app_release.proto\x1a\x1bqwibi/v1/auth_options.proto\x1a\x15qwibi/v1/common.proto\"\xb5\x03\n" +
	"\x15AppActionAvailability\x12?\n" +
	"\taction_id\x18\x01 \x01(\tB\"\xbaH\x1fr\x1d\x10\x01\x18@2\x17^[a-z][a-z0-9_-]{0,63}$R\bactionId\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12]\n" +
	"\x12unavailable_reason\x18\x03 \x01(\x0e2$.qwibi.v1.AppActionUnavailableReasonB\b\xbaH\x05\x82\x01\x02\x10\x01R\x11unavailableReason:\xdd\x01\xbaH\xd9\x01\x1a\xd6\x01\n" +
	"\x1eapp_action_availability.reason\x12Mavailable actions have no unavailable reason and unavailable actions have one\x1ae(this.available && this.unavailable_reason == 0) || (!this.available && this.unavailable_reason != 0)\"\xfa\a\n" +
	"\x0fAppInstallation\x121\n" +
	"\x0finstallation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0einstallationId\x12#\n" +
	"\blayer_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\alayerId\x12\x1f\n" +
	"\x06app_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x12?\n" +
	"\x17installed_by_account_id\x18\x05 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x14installedByAccountId\x12C\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1f.qwibi.v1.AppInstallationStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\x126\n" +
	"\x12lifecycle_revision\x18\t \x01(\x04B\a\xbaH\x042\x02 \x00R\x11lifecycleRevision\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\factivated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vactivatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fsuspended_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vsuspendedAt\x129\n" +
	"\n" +
	"removed_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tremovedAt\x12h\n" +
	"\x1aactive_action_availability\x18\x0f \x03(\v2\x1f.qwibi.v1.AppActionAvailabilityB\t\xbaH\x06\x92\x01\x03\x10\x80\x02R\x18activeActionAvailability\x12$\n" +
	"\x0eblocked_by_app\x18\x10 \x01(\bR\fblockedByApp\x12*\n" +
	"\x11blocking_app_name\x18\x11 \x01(\tR\x0fblockingAppName\x12!\n" +
	"\fblock_reason\x18\x12 \x01(\tR\vblockReason\x12\x19\n" +
	"\bapp_name\x18\x13 \x01(\tR\aappName\x12B\n" +
	"\x10app_access_level\x18\x14 \x01(\x0e2\x18.qwibi.v1.AppAccessLevelR\x0eappAccessLevelJ\x04\b\x04\x10\x05J\x04\b\a\x10\bJ\x04\b\b\x10\tR\x10app_principal_idR\x0eactive_releaseR\x0fpending_release\"\xcb\x02\n" +
	"\x1eInstallationParticipantConsent\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x124\n" +
	"\x05right\x18\x03 \x01(\x0e2\x12.qwibi.v1.AppRightB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05right\x12X\n" +
	"\bdecision\x18\x05 \x01(\x0e20.qwibi.v1.InstallationParticipantConsentDecisionB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bdecision\x129\n" +
	"\n" +
	"decided_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAtJ\x04\b\x04\x10\x05R\x0egrant_revision\"\xb0\x01\n" +
	"\x11InstallAppRequest\x12#\n" +
	"\blayer_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\alayerId\x12\x1f\n" +
	"\x06app_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appIdJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\n" +
	"release_idR\x14granted_capabilitiesR!acknowledged_reinstall_disclosure\"w\n" +
	"\x12InstallAppResponse\x12E\n" +
	"\finstallation\x18\x01 \x01(\v2\x19.qwibi.v1.AppInstallationB\x06\xbaH\x03\xc8\x01\x01R\finstallationJ\x04\b\x02\x10\x03R\x14reinstall_disclosure\"7\n" +
	"\x14AddAppToMyMapRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\"\x83\x01\n" +
	"\x15AddAppToMyMapResponse\x12#\n" +
	"\blayer_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\alayerId\x12E\n" +
	"\finstallation\x18\x02 \x01(\v2\x19.qwibi.v1.AppInstallationB\x06\xbaH\x03\xc8\x01\x01R\finstallation\"N\n" +
	"\x19GetAppInstallationRequest\x121\n" +
	"\x0finstallation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0einstallationId\"\x7f\n" +
	"\x1aGetAppInstallationResponse\x12E\n" +
	"\finstallation\x18\x01 \x01(\v2\x19.qwibi.v1.AppInstallationB\x06\xbaH\x03\xc8\x01\x01R\finstallationJ\x04\b\x02\x10\x03R\x14reinstall_disclosure\"{\n" +
	"\x1bListAppInstallationsRequest\x12#\n" +
	"\blayer_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\alayerId\x12)\n" +
	"\x04page\x18\x03 \x01(\v2\x15.qwibi.v1.PageRequestR\x04pageJ\x04\b\x02\x10\x03R\x06app_id\"\x8b\x01\n" +
	"\x1cListAppInstallationsResponse\x12?\n" +
	"\rinstallations\x18\x01 \x03(\v2\x19.qwibi.v1.AppInstallationR\rinstallations\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.qwibi.v1.PageResponseR\x04page\"\x9b\x01\n" +
	"\x1dSuspendAppInstallationRequest\x121\n" +
	"\x0finstallation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0einstallationId\x12G\n" +
	"\x1bexpected_lifecycle_revision\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x19expectedLifecycleRevision\"g\n" +
	"\x1eSuspendAppInstallationResponse\x12E\n" +
	"\finstallation\x18\x01 \x01(\v2\x19.qwibi.v1.AppInstallationB\x06\xbaH\x03\xc8\x01\x01R\finstallation\"\x9a\x01\n" +
	"\x1cResumeAppInstallationRequest\x121\n" +
	"\x0finstallation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0einstallationId\x12G\n" +
	"\x1bexpected_lifecycle_revision\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x19expectedLifecycleRevision\"f\n" +
	"\x1dResumeAppInstallationResponse\x12E\n" +
	"\finstallation\x18\x01 \x01(\v2\x19.qwibi.v1.AppInstallationB\x06\xbaH\x03\xc8\x01\x01R\finstallation\"\xb9\x01\n" +
	"\x1cRemoveAppInstallationRequest\x121\n" +
	"\x0finstallation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0einstallationId\x12G\n" +
	"\x1bexpected_lifecycle_revision\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x19expectedLifecycleRevisionJ\x04\b\x03\x10\x04R\x17retained_content_choice\"\xa5\x01\n" +
	"\x1dRemoveAppInstallationResponse\x12E\n" +
	"\finstallation\x18\x01 \x01(\v2\x19.qwibi.v1.AppInstallationB\x06\xbaH\x03\xc8\x01\x01R\finstallationJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x10retained_contentR\x1fapplied_retained_content_choice\"\xf1\x01\n" +
	"(SetInstallationParticipantConsentRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x124\n" +
	"\x05right\x18\x02 \x01(\x0e2\x12.qwibi.v1.AppRightB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05right\x12X\n" +
	"\bdecision\x18\x04 \x01(\x0e20.qwibi.v1.InstallationParticipantConsentDecisionB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bdecisionJ\x04\b\x03\x10\x04R\x0egrant_revision\"w\n" +
	")SetInstallationParticipantConsentResponse\x12J\n" +
	"\aconsent\x18\x01 \x01(\v2(.qwibi.v1.InstallationParticipantConsentB\x06\xbaH\x03\xc8\x01\x01R\aconsent\"\x90\x01\n" +
	",ListMyInstallationParticipantConsentsRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x12)\n" +
	"\x04page\x18\x03 \x01(\v2\x15.qwibi.v1.PageRequestR\x04pageJ\x04\b\x02\x10\x03R\x0egrant_revision\"\xa1\x01\n" +
	"-ListMyInstallationParticipantConsentsResponse\x12D\n" +
	"\bconsents\x18\x01 \x03(\v2(.qwibi.v1.InstallationParticipantConsentR\bconsents\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.qwibi.v1.PageResponseR\x04page*\xa5\x02\n" +
	"\x15AppInstallationStatus\x12'\n" +
	"#APP_INSTALLATION_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eAPP_INSTALLATION_STATUS_ACTIVE\x10\x02\x12%\n" +
	"!APP_INSTALLATION_STATUS_SUSPENDED\x10\x04\x12#\n" +
	"\x1fAPP_INSTALLATION_STATUS_REMOVED\x10\x05\"\x04\b\x01\x10\x01\"\x04\b\x03\x10\x03\"\x04\b\x06\x10\x06*\x1fAPP_INSTALLATION_STATUS_PENDING* APP_INSTALLATION_STATUS_DEGRADED*\x1eAPP_INSTALLATION_STATUS_PAUSED*\x80\x02\n" +
	"\x1aAppActionUnavailableReason\x12-\n" +
	")APP_ACTION_UNAVAILABLE_REASON_UNSPECIFIED\x10\x00\x12:\n" +
	"6APP_ACTION_UNAVAILABLE_REASON_INSTALLATION_NOT_SERVING\x10\x01\x122\n" +
	".APP_ACTION_UNAVAILABLE_REASON_CONSENT_REQUIRED\x10\x03\"\x04\b\x02\x10\x02*=APP_ACTION_UNAVAILABLE_REASON_REQUIRED_CAPABILITY_NOT_GRANTED*\xd5\x01\n" +
	"&InstallationParticipantConsentDecision\x129\n" +
	"5INSTALLATION_PARTICIPANT_CONSENT_DECISION_UNSPECIFIED\x10\x00\x127\n" +
	"3INSTALLATION_PARTICIPANT_CONSENT_DECISION_CONSENTED\x10\x01\x127\n" +
	"3INSTALLATION_PARTICIPANT_CONSENT_DECISION_WITHDRAWN\x10\x022\x9c\b\n" +
	"\x16AppInstallationService\x12M\n" +
	"\n" +
	"InstallApp\x12\x1b.qwibi.v1.InstallAppRequest\x1a\x1c.qwibi.v1.InstallAppResponse\"\x04\x88\xb5\x18\x03\x12V\n" +
	"\rAddAppToMyMap\x12\x1e.qwibi.v1.AddAppToMyMapRequest\x1a\x1f.qwibi.v1.AddAppToMyMapResponse\"\x04\x88\xb5\x18\x03\x12e\n" +
	"\x12GetAppInstallation\x12#.qwibi.v1.GetAppInstallationRequest\x1a$.qwibi.v1.GetAppInstallationResponse\"\x04\x88\xb5\x18\x03\x12k\n" +
	"\x14ListAppInstallations\x12%.qwibi.v1.ListAppInstallationsRequest\x1a&.qwibi.v1.ListAppInstallationsResponse\"\x04\x88\xb5\x18\x03\x12q\n" +
	"\x16SuspendAppInstallation\x12'.qwibi.v1.SuspendAppInstallationRequest\x1a(.qwibi.v1.SuspendAppInstallationResponse\"\x04\x88\xb5\x18\x03\x12n\n" +
	"\x15ResumeAppInstallation\x12&.qwibi.v1.ResumeAppInstallationRequest\x1a'.qwibi.v1.ResumeAppInstallationResponse\"\x04\x88\xb5\x18\x03\x12n\n" +
	"\x15RemoveAppInstallation\x12&.qwibi.v1.RemoveAppInstallationRequest\x1a'.qwibi.v1.RemoveAppInstallationResponse\"\x04\x88\xb5\x18\x03\x12\x92\x01\n" +
	"!SetInstallationParticipantConsent\x122.qwibi.v1.SetInstallationParticipantConsentRequest\x1a3.qwibi.v1.SetInstallationParticipantConsentResponse\"\x04\x88\xb5\x18\x03\x12\x9e\x01\n" +
	"%ListMyInstallationParticipantConsents\x126.qwibi.v1.ListMyInstallationParticipantConsentsRequest\x1a7.qwibi.v1.ListMyInstallationParticipantConsentsResponse\"\x04\x88\xb5\x18\x03B\x97\x01\n" +
	"\fcom.qwibi.v1B\x14AppInstallationProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_app_installation_proto_rawDescOnce sync.Once
	file_qwibi_v1_app_installation_proto_rawDescData []byte
)

func file_qwibi_v1_app_installation_proto_rawDescGZIP() []byte {
	file_qwibi_v1_app_installation_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_app_installation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_installation_proto_rawDesc), len(file_qwibi_v1_app_installation_proto_rawDesc)))
	})
	return file_qwibi_v1_app_installation_proto_rawDescData
}

var file_qwibi_v1_app_installation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_qwibi_v1_app_installation_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_qwibi_v1_app_installation_proto_goTypes = []any{
	(AppInstallationStatus)(0),                            // 0: qwibi.v1.AppInstallationStatus
	(AppActionUnavailableReason)(0),                       // 1: qwibi.v1.AppActionUnavailableReason
	(InstallationParticipantConsentDecision)(0),           // 2: qwibi.v1.InstallationParticipantConsentDecision
	(*AppActionAvailability)(nil),                         // 3: qwibi.v1.AppActionAvailability
	(*AppInstallation)(nil),                               // 4: qwibi.v1.AppInstallation
	(*InstallationParticipantConsent)(nil),                // 5: qwibi.v1.InstallationParticipantConsent
	(*InstallAppRequest)(nil),                             // 6: qwibi.v1.InstallAppRequest
	(*InstallAppResponse)(nil),                            // 7: qwibi.v1.InstallAppResponse
	(*AddAppToMyMapRequest)(nil),                          // 8: qwibi.v1.AddAppToMyMapRequest
	(*AddAppToMyMapResponse)(nil),                         // 9: qwibi.v1.AddAppToMyMapResponse
	(*GetAppInstallationRequest)(nil),                     // 10: qwibi.v1.GetAppInstallationRequest
	(*GetAppInstallationResponse)(nil),                    // 11: qwibi.v1.GetAppInstallationResponse
	(*ListAppInstallationsRequest)(nil),                   // 12: qwibi.v1.ListAppInstallationsRequest
	(*ListAppInstallationsResponse)(nil),                  // 13: qwibi.v1.ListAppInstallationsResponse
	(*SuspendAppInstallationRequest)(nil),                 // 14: qwibi.v1.SuspendAppInstallationRequest
	(*SuspendAppInstallationResponse)(nil),                // 15: qwibi.v1.SuspendAppInstallationResponse
	(*ResumeAppInstallationRequest)(nil),                  // 16: qwibi.v1.ResumeAppInstallationRequest
	(*ResumeAppInstallationResponse)(nil),                 // 17: qwibi.v1.ResumeAppInstallationResponse
	(*RemoveAppInstallationRequest)(nil),                  // 18: qwibi.v1.RemoveAppInstallationRequest
	(*RemoveAppInstallationResponse)(nil),                 // 19: qwibi.v1.RemoveAppInstallationResponse
	(*SetInstallationParticipantConsentRequest)(nil),      // 20: qwibi.v1.SetInstallationParticipantConsentRequest
	(*SetInstallationParticipantConsentResponse)(nil),     // 21: qwibi.v1.SetInstallationParticipantConsentResponse
	(*ListMyInstallationParticipantConsentsRequest)(nil),  // 22: qwibi.v1.ListMyInstallationParticipantConsentsRequest
	(*ListMyInstallationParticipantConsentsResponse)(nil), // 23: qwibi.v1.ListMyInstallationParticipantConsentsResponse
	(*timestamppb.Timestamp)(nil),                         // 24: google.protobuf.Timestamp
	(AppAccessLevel)(0),                                   // 25: qwibi.v1.AppAccessLevel
	(AppRight)(0),                                         // 26: qwibi.v1.AppRight
	(*PageRequest)(nil),                                   // 27: qwibi.v1.PageRequest
	(*PageResponse)(nil),                                  // 28: qwibi.v1.PageResponse
}
var file_qwibi_v1_app_installation_proto_depIdxs = []int32{
	1,  // 0: qwibi.v1.AppActionAvailability.unavailable_reason:type_name -> qwibi.v1.AppActionUnavailableReason
	0,  // 1: qwibi.v1.AppInstallation.status:type_name -> qwibi.v1.AppInstallationStatus
	24, // 2: qwibi.v1.AppInstallation.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: qwibi.v1.AppInstallation.activated_at:type_name -> google.protobuf.Timestamp
	24, // 4: qwibi.v1.AppInstallation.updated_at:type_name -> google.protobuf.Timestamp
	24, // 5: qwibi.v1.AppInstallation.suspended_at:type_name -> google.protobuf.Timestamp
	24, // 6: qwibi.v1.AppInstallation.removed_at:type_name -> google.protobuf.Timestamp
	3,  // 7: qwibi.v1.AppInstallation.active_action_availability:type_name -> qwibi.v1.AppActionAvailability
	25, // 8: qwibi.v1.AppInstallation.app_access_level:type_name -> qwibi.v1.AppAccessLevel
	26, // 9: qwibi.v1.InstallationParticipantConsent.right:type_name -> qwibi.v1.AppRight
	2,  // 10: qwibi.v1.InstallationParticipantConsent.decision:type_name -> qwibi.v1.InstallationParticipantConsentDecision
	24, // 11: qwibi.v1.InstallationParticipantConsent.decided_at:type_name -> google.protobuf.Timestamp
	4,  // 12: qwibi.v1.InstallAppResponse.installation:type_name -> qwibi.v1.AppInstallation
	4,  // 13: qwibi.v1.AddAppToMyMapResponse.installation:type_name -> qwibi.v1.AppInstallation
	4,  // 14: qwibi.v1.GetAppInstallationResponse.installation:type_name -> qwibi.v1.AppInstallation
	27, // 15: qwibi.v1.ListAppInstallationsRequest.page:type_name -> qwibi.v1.PageRequest
	4,  // 16: qwibi.v1.ListAppInstallationsResponse.installations:type_name -> qwibi.v1.AppInstallation
	28, // 17: qwibi.v1.ListAppInstallationsResponse.page:type_name -> qwibi.v1.PageResponse
	4,  // 18: qwibi.v1.SuspendAppInstallationResponse.installation:type_name -> qwibi.v1.AppInstallation
	4,  // 19: qwibi.v1.ResumeAppInstallationResponse.installation:type_name -> qwibi.v1.AppInstallation
	4,  // 20: qwibi.v1.RemoveAppInstallationResponse.installation:type_name -> qwibi.v1.AppInstallation
	26, // 21: qwibi.v1.SetInstallationParticipantConsentRequest.right:type_name -> qwibi.v1.AppRight
	2,  // 22: qwibi.v1.SetInstallationParticipantConsentRequest.decision:type_name -> qwibi.v1.InstallationParticipantConsentDecision
	5,  // 23: qwibi.v1.SetInstallationParticipantConsentResponse.consent:type_name -> qwibi.v1.InstallationParticipantConsent
	27, // 24: qwibi.v1.ListMyInstallationParticipantConsentsRequest.page:type_name -> qwibi.v1.PageRequest
	5,  // 25: qwibi.v1.ListMyInstallationParticipantConsentsResponse.consents:type_name -> qwibi.v1.InstallationParticipantConsent
	28, // 26: qwibi.v1.ListMyInstallationParticipantConsentsResponse.page:type_name -> qwibi.v1.PageResponse
	6,  // 27: qwibi.v1.AppInstallationService.InstallApp:input_type -> qwibi.v1.InstallAppRequest
	8,  // 28: qwibi.v1.AppInstallationService.AddAppToMyMap:input_type -> qwibi.v1.AddAppToMyMapRequest
	10, // 29: qwibi.v1.AppInstallationService.GetAppInstallation:input_type -> qwibi.v1.GetAppInstallationRequest
	12, // 30: qwibi.v1.AppInstallationService.ListAppInstallations:input_type -> qwibi.v1.ListAppInstallationsRequest
	14, // 31: qwibi.v1.AppInstallationService.SuspendAppInstallation:input_type -> qwibi.v1.SuspendAppInstallationRequest
	16, // 32: qwibi.v1.AppInstallationService.ResumeAppInstallation:input_type -> qwibi.v1.ResumeAppInstallationRequest
	18, // 33: qwibi.v1.AppInstallationService.RemoveAppInstallation:input_type -> qwibi.v1.RemoveAppInstallationRequest
	20, // 34: qwibi.v1.AppInstallationService.SetInstallationParticipantConsent:input_type -> qwibi.v1.SetInstallationParticipantConsentRequest
	22, // 35: qwibi.v1.AppInstallationService.ListMyInstallationParticipantConsents:input_type -> qwibi.v1.ListMyInstallationParticipantConsentsRequest
	7,  // 36: qwibi.v1.AppInstallationService.InstallApp:output_type -> qwibi.v1.InstallAppResponse
	9,  // 37: qwibi.v1.AppInstallationService.AddAppToMyMap:output_type -> qwibi.v1.AddAppToMyMapResponse
	11, // 38: qwibi.v1.AppInstallationService.GetAppInstallation:output_type -> qwibi.v1.GetAppInstallationResponse
	13, // 39: qwibi.v1.AppInstallationService.ListAppInstallations:output_type -> qwibi.v1.ListAppInstallationsResponse
	15, // 40: qwibi.v1.AppInstallationService.SuspendAppInstallation:output_type -> qwibi.v1.SuspendAppInstallationResponse
	17, // 41: qwibi.v1.AppInstallationService.ResumeAppInstallation:output_type -> qwibi.v1.ResumeAppInstallationResponse
	19, // 42: qwibi.v1.AppInstallationService.RemoveAppInstallation:output_type -> qwibi.v1.RemoveAppInstallationResponse
	21, // 43: qwibi.v1.AppInstallationService.SetInstallationParticipantConsent:output_type -> qwibi.v1.SetInstallationParticipantConsentResponse
	23, // 44: qwibi.v1.AppInstallationService.ListMyInstallationParticipantConsents:output_type -> qwibi.v1.ListMyInstallationParticipantConsentsResponse
	36, // [36:45] is the sub-list for method output_type
	27, // [27:36] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_qwibi_v1_app_installation_proto_init() }
func file_qwibi_v1_app_installation_proto_init() {
	if File_qwibi_v1_app_installation_proto != nil {
		return
	}
	file_qwibi_v1_app_proto_init()
	file_qwibi_v1_app_release_proto_init()
	file_qwibi_v1_auth_options_proto_init()
	file_qwibi_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_installation_proto_rawDesc), len(file_qwibi_v1_app_installation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qwibi_v1_app_installation_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_app_installation_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_app_installation_proto_enumTypes,
		MessageInfos:      file_qwibi_v1_app_installation_proto_msgTypes,
	}.Build()
	File_qwibi_v1_app_installation_proto = out.File
	file_qwibi_v1_app_installation_proto_goTypes = nil
	file_qwibi_v1_app_installation_proto_depIdxs = nil
}
