// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/app_release_service.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishAppReleaseRequest publishes exactly the supplied immutable release.
// There is no update operation: any content change requires a new release ID
// and semantic version.
type PublishAppReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *AppRelease            `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAppReleaseRequest) Reset() {
	*x = PublishAppReleaseRequest{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAppReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAppReleaseRequest) ProtoMessage() {}

func (x *PublishAppReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAppReleaseRequest.ProtoReflect.Descriptor instead.
func (*PublishAppReleaseRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{0}
}

func (x *PublishAppReleaseRequest) GetRelease() *AppRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

type PublishAppReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *AppRelease            `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Lifecycle     *AppReleaseLifecycle   `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAppReleaseResponse) Reset() {
	*x = PublishAppReleaseResponse{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAppReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAppReleaseResponse) ProtoMessage() {}

func (x *PublishAppReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAppReleaseResponse.ProtoReflect.Descriptor instead.
func (*PublishAppReleaseResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{1}
}

func (x *PublishAppReleaseResponse) GetRelease() *AppRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *PublishAppReleaseResponse) GetLifecycle() *AppReleaseLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

// GetAppReleaseRequest resolves an exact release ID or exact App/version pair.
// Empty consumer_contract_version means that the caller declares no host
// compatibility constraint; a host must send its actual contract version.
type GetAppReleaseRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Selector                *AppReleaseSelector    `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	ConsumerContractVersion string                 `protobuf:"bytes,2,opt,name=consumer_contract_version,json=consumerContractVersion,proto3" json:"consumer_contract_version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetAppReleaseRequest) Reset() {
	*x = GetAppReleaseRequest{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppReleaseRequest) ProtoMessage() {}

func (x *GetAppReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppReleaseRequest.ProtoReflect.Descriptor instead.
func (*GetAppReleaseRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppReleaseRequest) GetSelector() *AppReleaseSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *GetAppReleaseRequest) GetConsumerContractVersion() string {
	if x != nil {
		return x.ConsumerContractVersion
	}
	return ""
}

type GetAppReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *AppRelease            `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Lifecycle     *AppReleaseLifecycle   `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppReleaseResponse) Reset() {
	*x = GetAppReleaseResponse{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppReleaseResponse) ProtoMessage() {}

func (x *GetAppReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppReleaseResponse.ProtoReflect.Descriptor instead.
func (*GetAppReleaseResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppReleaseResponse) GetRelease() *AppRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *GetAppReleaseResponse) GetLifecycle() *AppReleaseLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

// ListAppReleasesRequest enumerates immutable releases for one exact App. It has
// no active/latest/install state and the cursor is opaque.
type ListAppReleasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppReleasesRequest) Reset() {
	*x = ListAppReleasesRequest{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppReleasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppReleasesRequest) ProtoMessage() {}

func (x *ListAppReleasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppReleasesRequest.ProtoReflect.Descriptor instead.
func (*ListAppReleasesRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAppReleasesRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListAppReleasesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAppReleasesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Releases []*AppRelease          `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	Page     *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// release_lifecycles has the same order and cardinality as releases.
	ReleaseLifecycles []*AppReleaseLifecycle `protobuf:"bytes,3,rep,name=release_lifecycles,json=releaseLifecycles,proto3" json:"release_lifecycles,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListAppReleasesResponse) Reset() {
	*x = ListAppReleasesResponse{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppReleasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppReleasesResponse) ProtoMessage() {}

func (x *ListAppReleasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppReleasesResponse.ProtoReflect.Descriptor instead.
func (*ListAppReleasesResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAppReleasesResponse) GetReleases() []*AppRelease {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *ListAppReleasesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListAppReleasesResponse) GetReleaseLifecycles() []*AppReleaseLifecycle {
	if x != nil {
		return x.ReleaseLifecycles
	}
	return nil
}

// SuspendAppReleaseRequest changes only the lifecycle row for one exact
// release. expected_lifecycle_revision may be zero for its first transition.
type SuspendAppReleaseRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId                 string                 `protobuf:"bytes,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ExpectedLifecycleRevision uint64                 `protobuf:"varint,2,opt,name=expected_lifecycle_revision,json=expectedLifecycleRevision,proto3" json:"expected_lifecycle_revision,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SuspendAppReleaseRequest) Reset() {
	*x = SuspendAppReleaseRequest{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendAppReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendAppReleaseRequest) ProtoMessage() {}

func (x *SuspendAppReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendAppReleaseRequest.ProtoReflect.Descriptor instead.
func (*SuspendAppReleaseRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{6}
}

func (x *SuspendAppReleaseRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *SuspendAppReleaseRequest) GetExpectedLifecycleRevision() uint64 {
	if x != nil {
		return x.ExpectedLifecycleRevision
	}
	return 0
}

type SuspendAppReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *AppRelease            `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Lifecycle     *AppReleaseLifecycle   `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendAppReleaseResponse) Reset() {
	*x = SuspendAppReleaseResponse{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendAppReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendAppReleaseResponse) ProtoMessage() {}

func (x *SuspendAppReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendAppReleaseResponse.ProtoReflect.Descriptor instead.
func (*SuspendAppReleaseResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{7}
}

func (x *SuspendAppReleaseResponse) GetRelease() *AppRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *SuspendAppReleaseResponse) GetLifecycle() *AppReleaseLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

// ResumeAppReleaseRequest requires the exact suspended revision. Successful
// resume always commits a newer durable revision.
type ResumeAppReleaseRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId                 string                 `protobuf:"bytes,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ExpectedLifecycleRevision uint64                 `protobuf:"varint,2,opt,name=expected_lifecycle_revision,json=expectedLifecycleRevision,proto3" json:"expected_lifecycle_revision,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ResumeAppReleaseRequest) Reset() {
	*x = ResumeAppReleaseRequest{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAppReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAppReleaseRequest) ProtoMessage() {}

func (x *ResumeAppReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAppReleaseRequest.ProtoReflect.Descriptor instead.
func (*ResumeAppReleaseRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{8}
}

func (x *ResumeAppReleaseRequest) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ResumeAppReleaseRequest) GetExpectedLifecycleRevision() uint64 {
	if x != nil {
		return x.ExpectedLifecycleRevision
	}
	return 0
}

type ResumeAppReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       *AppRelease            `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Lifecycle     *AppReleaseLifecycle   `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAppReleaseResponse) Reset() {
	*x = ResumeAppReleaseResponse{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAppReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAppReleaseResponse) ProtoMessage() {}

func (x *ResumeAppReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAppReleaseResponse.ProtoReflect.Descriptor instead.
func (*ResumeAppReleaseResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeAppReleaseResponse) GetRelease() *AppRelease {
	if x != nil {
		return x.Release
	}
	return nil
}

func (x *ResumeAppReleaseResponse) GetLifecycle() *AppReleaseLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

// GetReleaseAssetRequest addresses public publisher material by exact hash.
type GetReleaseAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentSha256 []byte                 `protobuf:"bytes,1,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleaseAssetRequest) Reset() {
	*x = GetReleaseAssetRequest{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleaseAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleaseAssetRequest) ProtoMessage() {}

func (x *GetReleaseAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleaseAssetRequest.ProtoReflect.Descriptor instead.
func (*GetReleaseAssetRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetReleaseAssetRequest) GetContentSha256() []byte {
	if x != nil {
		return x.ContentSha256
	}
	return nil
}

type GetReleaseAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *ReleaseAsset          `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,2,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReleaseAssetResponse) Reset() {
	*x = GetReleaseAssetResponse{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReleaseAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleaseAssetResponse) ProtoMessage() {}

func (x *GetReleaseAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleaseAssetResponse.ProtoReflect.Descriptor instead.
func (*GetReleaseAssetResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetReleaseAssetResponse) GetAsset() *ReleaseAsset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *GetReleaseAssetResponse) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

// UploadReleaseAssetRequest stores one exact immutable publisher asset before
// its hash is pinned by a release. The publisher must hold RELEASE_PUBLISH for
// the exact App and authenticate with the exact current human credential.
type UploadReleaseAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Asset         *ReleaseAsset          `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReleaseAssetRequest) Reset() {
	*x = UploadReleaseAssetRequest{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReleaseAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReleaseAssetRequest) ProtoMessage() {}

func (x *UploadReleaseAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReleaseAssetRequest.ProtoReflect.Descriptor instead.
func (*UploadReleaseAssetRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{12}
}

func (x *UploadReleaseAssetRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UploadReleaseAssetRequest) GetAsset() *ReleaseAsset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *UploadReleaseAssetRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadReleaseAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *ReleaseAsset          `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReleaseAssetResponse) Reset() {
	*x = UploadReleaseAssetResponse{}
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReleaseAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReleaseAssetResponse) ProtoMessage() {}

func (x *UploadReleaseAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_release_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReleaseAssetResponse.ProtoReflect.Descriptor instead.
func (*UploadReleaseAssetResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_release_service_proto_rawDescGZIP(), []int{13}
}

func (x *UploadReleaseAssetResponse) GetAsset() *ReleaseAsset {
	if x != nil {
		return x.Asset
	}
	return nil
}

var File_qwibi_v1_app_release_service_proto protoreflect.FileDescriptor

const file_qwibi_v1_app_release_service_proto_rawDesc = "" +
	"\n" +
	"\"qwibi/v1/app_release_service.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1aqwibi/v1/app_release.proto\x1a\x1bqwibi/v1/auth_options.proto\x1a\x15qwibi/v1/common.proto\"R\n" +
	"\x18PublishAppReleaseRequest\x126\n" +
	"\arelease\x18\x01 \x01(\v2\x14.qwibi.v1.AppReleaseB\x06\xbaH\x03\xc8\x01\x01R\arelease\"\x98\x01\n" +
	"\x19PublishAppReleaseResponse\x126\n" +
	"\arelease\x18\x01 \x01(\v2\x14.qwibi.v1.AppReleaseB\x06\xbaH\x03\xc8\x01\x01R\arelease\x12C\n" +
	"\tlifecycle\x18\x02 \x01(\v2\x1d.qwibi.v1.AppReleaseLifecycleB\x06\xbaH\x03\xc8\x01\x01R\tlifecycle\"\xa3\x02\n" +
	"\x14GetAppReleaseRequest\x12@\n" +
	"\bselector\x18\x01 \x01(\v2\x1c.qwibi.v1.AppReleaseSelectorB\x06\xbaH\x03\xc8\x01\x01R\bselector\x12\xc8\x01\n" +
	"\x19consumer_contract_version\x18\x02 \x01(\tB\x8b\x01\xbaH\x87\x01\xd8\x01\x01r\x81\x01\x10\x05\x18\x80\x012z^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$R\x17consumerContractVersion\"\x94\x01\n" +
	"\x15GetAppReleaseResponse\x126\n" +
	"\arelease\x18\x01 \x01(\v2\x14.qwibi.v1.AppReleaseB\x06\xbaH\x03\xc8\x01\x01R\arelease\x12C\n" +
	"\tlifecycle\x18\x02 \x01(\v2\x1d.qwibi.v1.AppReleaseLifecycleB\x06\xbaH\x03\xc8\x01\x01R\tlifecycle\"\xa4\x01\n" +
	"\x16ListAppReleasesRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.qwibi.v1.PageRequestR\x04page\"\xc5\x01\n" +
	"\x17ListAppReleasesResponse\x120\n" +
	"\breleases\x18\x01 \x03(\v2\x14.qwibi.v1.AppReleaseR\breleases\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.qwibi.v1.PageResponseR\x04page\x12L\n" +
	"\x12release_lifecycles\x18\x03 \x03(\v2\x1d.qwibi.v1.AppReleaseLifecycleR\x11releaseLifecycles\"\xc3\x01\n" +
	"\x18SuspendAppReleaseRequest\x12g\n" +
	"\n" +
	"release_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\treleaseId\x12>\n" +
	"\x1bexpected_lifecycle_revision\x18\x02 \x01(\x04R\x19expectedLifecycleRevision\"\x98\x01\n" +
	"\x19SuspendAppReleaseResponse\x126\n" +
	"\arelease\x18\x01 \x01(\v2\x14.qwibi.v1.AppReleaseB\x06\xbaH\x03\xc8\x01\x01R\arelease\x12C\n" +
	"\tlifecycle\x18\x02 \x01(\v2\x1d.qwibi.v1.AppReleaseLifecycleB\x06\xbaH\x03\xc8\x01\x01R\tlifecycle\"\xc2\x01\n" +
	"\x17ResumeAppReleaseRequest\x12g\n" +
	"\n" +
	"release_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\treleaseId\x12>\n" +
	"\x1bexpected_lifecycle_revision\x18\x02 \x01(\x04R\x19expectedLifecycleRevision\"\x97\x01\n" +
	"\x18ResumeAppReleaseResponse\x126\n" +
	"\arelease\x18\x01 \x01(\v2\x14.qwibi.v1.AppReleaseB\x06\xbaH\x03\xc8\x01\x01R\arelease\x12C\n" +
	"\tlifecycle\x18\x02 \x01(\v2\x1d.qwibi.v1.AppReleaseLifecycleB\x06\xbaH\x03\xc8\x01\x01R\tlifecycle\"H\n" +
	"\x16GetReleaseAssetRequest\x12.\n" +
	"\x0econtent_sha256\x18\x01 \x01(\fB\a\xbaH\x04z\x02h R\rcontentSha256\"z\n" +
	"\x17GetReleaseAssetResponse\x124\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.qwibi.v1.ReleaseAssetB\x06\xbaH\x03\xc8\x01\x01R\x05asset\x12)\n" +
	"\n" +
	"public_url\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80 R\tpublicUrl\"\xd5\x01\n" +
	"\x19UploadReleaseAssetRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x124\n" +
	"\x05asset\x18\x02 \x01(\v2\x16.qwibi.v1.ReleaseAssetB\x06\xbaH\x03\xc8\x01\x01R\x05asset\x12!\n" +
	"\acontent\x18\x03 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\acontent\"R\n" +
	"\x1aUploadReleaseAssetResponse\x124\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.qwibi.v1.ReleaseAssetB\x06\xbaH\x03\xc8\x01\x01R\x05asset2\xb7\x05\n" +
	"\x11AppReleaseService\x12b\n" +
	"\x11PublishAppRelease\x12\".qwibi.v1.PublishAppReleaseRequest\x1a#.qwibi.v1.PublishAppReleaseResponse\"\x04\x88\xb5\x18\x03\x12V\n" +
	"\rGetAppRelease\x12\x1e.qwibi.v1.GetAppReleaseRequest\x1a\x1f.qwibi.v1.GetAppReleaseResponse\"\x04\x88\xb5\x18\x02\x12\\\n" +
	"\x0fListAppReleases\x12 .qwibi.v1.ListAppReleasesRequest\x1a!.qwibi.v1.ListAppReleasesResponse\"\x04\x88\xb5\x18\x02\x12b\n" +
	"\x11SuspendAppRelease\x12\".qwibi.v1.SuspendAppReleaseRequest\x1a#.qwibi.v1.SuspendAppReleaseResponse\"\x04\x88\xb5\x18\x03\x12_\n" +
	"\x10ResumeAppRelease\x12!.qwibi.v1.ResumeAppReleaseRequest\x1a\".qwibi.v1.ResumeAppReleaseResponse\"\x04\x88\xb5\x18\x03\x12\\\n" +
	"\x0fGetReleaseAsset\x12 .qwibi.v1.GetReleaseAssetRequest\x1a!.qwibi.v1.GetReleaseAssetResponse\"\x04\x88\xb5\x18\x01\x12e\n" +
	"\x12UploadReleaseAsset\x12#.qwibi.v1.UploadReleaseAssetRequest\x1a$.qwibi.v1.UploadReleaseAssetResponse\"\x04\x88\xb5\x18\x03B\x99\x01\n" +
	"\fcom.qwibi.v1B\x16AppReleaseServiceProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_app_release_service_proto_rawDescOnce sync.Once
	file_qwibi_v1_app_release_service_proto_rawDescData []byte
)

func file_qwibi_v1_app_release_service_proto_rawDescGZIP() []byte {
	file_qwibi_v1_app_release_service_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_app_release_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_release_service_proto_rawDesc), len(file_qwibi_v1_app_release_service_proto_rawDesc)))
	})
	return file_qwibi_v1_app_release_service_proto_rawDescData
}

var file_qwibi_v1_app_release_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_qwibi_v1_app_release_service_proto_goTypes = []any{
	(*PublishAppReleaseRequest)(nil),   // 0: qwibi.v1.PublishAppReleaseRequest
	(*PublishAppReleaseResponse)(nil),  // 1: qwibi.v1.PublishAppReleaseResponse
	(*GetAppReleaseRequest)(nil),       // 2: qwibi.v1.GetAppReleaseRequest
	(*GetAppReleaseResponse)(nil),      // 3: qwibi.v1.GetAppReleaseResponse
	(*ListAppReleasesRequest)(nil),     // 4: qwibi.v1.ListAppReleasesRequest
	(*ListAppReleasesResponse)(nil),    // 5: qwibi.v1.ListAppReleasesResponse
	(*SuspendAppReleaseRequest)(nil),   // 6: qwibi.v1.SuspendAppReleaseRequest
	(*SuspendAppReleaseResponse)(nil),  // 7: qwibi.v1.SuspendAppReleaseResponse
	(*ResumeAppReleaseRequest)(nil),    // 8: qwibi.v1.ResumeAppReleaseRequest
	(*ResumeAppReleaseResponse)(nil),   // 9: qwibi.v1.ResumeAppReleaseResponse
	(*GetReleaseAssetRequest)(nil),     // 10: qwibi.v1.GetReleaseAssetRequest
	(*GetReleaseAssetResponse)(nil),    // 11: qwibi.v1.GetReleaseAssetResponse
	(*UploadReleaseAssetRequest)(nil),  // 12: qwibi.v1.UploadReleaseAssetRequest
	(*UploadReleaseAssetResponse)(nil), // 13: qwibi.v1.UploadReleaseAssetResponse
	(*AppRelease)(nil),                 // 14: qwibi.v1.AppRelease
	(*AppReleaseLifecycle)(nil),        // 15: qwibi.v1.AppReleaseLifecycle
	(*AppReleaseSelector)(nil),         // 16: qwibi.v1.AppReleaseSelector
	(*PageRequest)(nil),                // 17: qwibi.v1.PageRequest
	(*PageResponse)(nil),               // 18: qwibi.v1.PageResponse
	(*ReleaseAsset)(nil),               // 19: qwibi.v1.ReleaseAsset
}
var file_qwibi_v1_app_release_service_proto_depIdxs = []int32{
	14, // 0: qwibi.v1.PublishAppReleaseRequest.release:type_name -> qwibi.v1.AppRelease
	14, // 1: qwibi.v1.PublishAppReleaseResponse.release:type_name -> qwibi.v1.AppRelease
	15, // 2: qwibi.v1.PublishAppReleaseResponse.lifecycle:type_name -> qwibi.v1.AppReleaseLifecycle
	16, // 3: qwibi.v1.GetAppReleaseRequest.selector:type_name -> qwibi.v1.AppReleaseSelector
	14, // 4: qwibi.v1.GetAppReleaseResponse.release:type_name -> qwibi.v1.AppRelease
	15, // 5: qwibi.v1.GetAppReleaseResponse.lifecycle:type_name -> qwibi.v1.AppReleaseLifecycle
	17, // 6: qwibi.v1.ListAppReleasesRequest.page:type_name -> qwibi.v1.PageRequest
	14, // 7: qwibi.v1.ListAppReleasesResponse.releases:type_name -> qwibi.v1.AppRelease
	18, // 8: qwibi.v1.ListAppReleasesResponse.page:type_name -> qwibi.v1.PageResponse
	15, // 9: qwibi.v1.ListAppReleasesResponse.release_lifecycles:type_name -> qwibi.v1.AppReleaseLifecycle
	14, // 10: qwibi.v1.SuspendAppReleaseResponse.release:type_name -> qwibi.v1.AppRelease
	15, // 11: qwibi.v1.SuspendAppReleaseResponse.lifecycle:type_name -> qwibi.v1.AppReleaseLifecycle
	14, // 12: qwibi.v1.ResumeAppReleaseResponse.release:type_name -> qwibi.v1.AppRelease
	15, // 13: qwibi.v1.ResumeAppReleaseResponse.lifecycle:type_name -> qwibi.v1.AppReleaseLifecycle
	19, // 14: qwibi.v1.GetReleaseAssetResponse.asset:type_name -> qwibi.v1.ReleaseAsset
	19, // 15: qwibi.v1.UploadReleaseAssetRequest.asset:type_name -> qwibi.v1.ReleaseAsset
	19, // 16: qwibi.v1.UploadReleaseAssetResponse.asset:type_name -> qwibi.v1.ReleaseAsset
	0,  // 17: qwibi.v1.AppReleaseService.PublishAppRelease:input_type -> qwibi.v1.PublishAppReleaseRequest
	2,  // 18: qwibi.v1.AppReleaseService.GetAppRelease:input_type -> qwibi.v1.GetAppReleaseRequest
	4,  // 19: qwibi.v1.AppReleaseService.ListAppReleases:input_type -> qwibi.v1.ListAppReleasesRequest
	6,  // 20: qwibi.v1.AppReleaseService.SuspendAppRelease:input_type -> qwibi.v1.SuspendAppReleaseRequest
	8,  // 21: qwibi.v1.AppReleaseService.ResumeAppRelease:input_type -> qwibi.v1.ResumeAppReleaseRequest
	10, // 22: qwibi.v1.AppReleaseService.GetReleaseAsset:input_type -> qwibi.v1.GetReleaseAssetRequest
	12, // 23: qwibi.v1.AppReleaseService.UploadReleaseAsset:input_type -> qwibi.v1.UploadReleaseAssetRequest
	1,  // 24: qwibi.v1.AppReleaseService.PublishAppRelease:output_type -> qwibi.v1.PublishAppReleaseResponse
	3,  // 25: qwibi.v1.AppReleaseService.GetAppRelease:output_type -> qwibi.v1.GetAppReleaseResponse
	5,  // 26: qwibi.v1.AppReleaseService.ListAppReleases:output_type -> qwibi.v1.ListAppReleasesResponse
	7,  // 27: qwibi.v1.AppReleaseService.SuspendAppRelease:output_type -> qwibi.v1.SuspendAppReleaseResponse
	9,  // 28: qwibi.v1.AppReleaseService.ResumeAppRelease:output_type -> qwibi.v1.ResumeAppReleaseResponse
	11, // 29: qwibi.v1.AppReleaseService.GetReleaseAsset:output_type -> qwibi.v1.GetReleaseAssetResponse
	13, // 30: qwibi.v1.AppReleaseService.UploadReleaseAsset:output_type -> qwibi.v1.UploadReleaseAssetResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_qwibi_v1_app_release_service_proto_init() }
func file_qwibi_v1_app_release_service_proto_init() {
	if File_qwibi_v1_app_release_service_proto != nil {
		return
	}
	file_qwibi_v1_app_release_proto_init()
	file_qwibi_v1_auth_options_proto_init()
	file_qwibi_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_release_service_proto_rawDesc), len(file_qwibi_v1_app_release_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qwibi_v1_app_release_service_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_app_release_service_proto_depIdxs,
		MessageInfos:      file_qwibi_v1_app_release_service_proto_msgTypes,
	}.Build()
	File_qwibi_v1_app_release_service_proto = out.File
	file_qwibi_v1_app_release_service_proto_goTypes = nil
	file_qwibi_v1_app_release_service_proto_depIdxs = nil
}
