// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: qwibi/v1/app_installation.proto

package qwibiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppInstallationService_InstallApp_FullMethodName                            = "/qwibi.v1.AppInstallationService/InstallApp"
	AppInstallationService_AddAppToMyMap_FullMethodName                         = "/qwibi.v1.AppInstallationService/AddAppToMyMap"
	AppInstallationService_GetAppInstallation_FullMethodName                    = "/qwibi.v1.AppInstallationService/GetAppInstallation"
	AppInstallationService_ListAppInstallations_FullMethodName                  = "/qwibi.v1.AppInstallationService/ListAppInstallations"
	AppInstallationService_SuspendAppInstallation_FullMethodName                = "/qwibi.v1.AppInstallationService/SuspendAppInstallation"
	AppInstallationService_ResumeAppInstallation_FullMethodName                 = "/qwibi.v1.AppInstallationService/ResumeAppInstallation"
	AppInstallationService_RemoveAppInstallation_FullMethodName                 = "/qwibi.v1.AppInstallationService/RemoveAppInstallation"
	AppInstallationService_SetInstallationParticipantConsent_FullMethodName     = "/qwibi.v1.AppInstallationService/SetInstallationParticipantConsent"
	AppInstallationService_ListMyInstallationParticipantConsents_FullMethodName = "/qwibi.v1.AppInstallationService/ListMyInstallationParticipantConsents"
)

// AppInstallationServiceClient is the client API for AppInstallationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppInstallationServiceClient interface {
	InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error)
	AddAppToMyMap(ctx context.Context, in *AddAppToMyMapRequest, opts ...grpc.CallOption) (*AddAppToMyMapResponse, error)
	GetAppInstallation(ctx context.Context, in *GetAppInstallationRequest, opts ...grpc.CallOption) (*GetAppInstallationResponse, error)
	ListAppInstallations(ctx context.Context, in *ListAppInstallationsRequest, opts ...grpc.CallOption) (*ListAppInstallationsResponse, error)
	SuspendAppInstallation(ctx context.Context, in *SuspendAppInstallationRequest, opts ...grpc.CallOption) (*SuspendAppInstallationResponse, error)
	ResumeAppInstallation(ctx context.Context, in *ResumeAppInstallationRequest, opts ...grpc.CallOption) (*ResumeAppInstallationResponse, error)
	RemoveAppInstallation(ctx context.Context, in *RemoveAppInstallationRequest, opts ...grpc.CallOption) (*RemoveAppInstallationResponse, error)
	SetInstallationParticipantConsent(ctx context.Context, in *SetInstallationParticipantConsentRequest, opts ...grpc.CallOption) (*SetInstallationParticipantConsentResponse, error)
	ListMyInstallationParticipantConsents(ctx context.Context, in *ListMyInstallationParticipantConsentsRequest, opts ...grpc.CallOption) (*ListMyInstallationParticipantConsentsResponse, error)
}

type appInstallationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppInstallationServiceClient(cc grpc.ClientConnInterface) AppInstallationServiceClient {
	return &appInstallationServiceClient{cc}
}

func (c *appInstallationServiceClient) InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallAppResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_InstallApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) AddAppToMyMap(ctx context.Context, in *AddAppToMyMapRequest, opts ...grpc.CallOption) (*AddAppToMyMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAppToMyMapResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_AddAppToMyMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) GetAppInstallation(ctx context.Context, in *GetAppInstallationRequest, opts ...grpc.CallOption) (*GetAppInstallationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppInstallationResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_GetAppInstallation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) ListAppInstallations(ctx context.Context, in *ListAppInstallationsRequest, opts ...grpc.CallOption) (*ListAppInstallationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppInstallationsResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_ListAppInstallations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) SuspendAppInstallation(ctx context.Context, in *SuspendAppInstallationRequest, opts ...grpc.CallOption) (*SuspendAppInstallationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendAppInstallationResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_SuspendAppInstallation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) ResumeAppInstallation(ctx context.Context, in *ResumeAppInstallationRequest, opts ...grpc.CallOption) (*ResumeAppInstallationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeAppInstallationResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_ResumeAppInstallation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) RemoveAppInstallation(ctx context.Context, in *RemoveAppInstallationRequest, opts ...grpc.CallOption) (*RemoveAppInstallationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAppInstallationResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_RemoveAppInstallation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) SetInstallationParticipantConsent(ctx context.Context, in *SetInstallationParticipantConsentRequest, opts ...grpc.CallOption) (*SetInstallationParticipantConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInstallationParticipantConsentResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_SetInstallationParticipantConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appInstallationServiceClient) ListMyInstallationParticipantConsents(ctx context.Context, in *ListMyInstallationParticipantConsentsRequest, opts ...grpc.CallOption) (*ListMyInstallationParticipantConsentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyInstallationParticipantConsentsResponse)
	err := c.cc.Invoke(ctx, AppInstallationService_ListMyInstallationParticipantConsents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppInstallationServiceServer is the server API for AppInstallationService service.
// All implementations should embed UnimplementedAppInstallationServiceServer
// for forward compatibility.
type AppInstallationServiceServer interface {
	InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error)
	AddAppToMyMap(context.Context, *AddAppToMyMapRequest) (*AddAppToMyMapResponse, error)
	GetAppInstallation(context.Context, *GetAppInstallationRequest) (*GetAppInstallationResponse, error)
	ListAppInstallations(context.Context, *ListAppInstallationsRequest) (*ListAppInstallationsResponse, error)
	SuspendAppInstallation(context.Context, *SuspendAppInstallationRequest) (*SuspendAppInstallationResponse, error)
	ResumeAppInstallation(context.Context, *ResumeAppInstallationRequest) (*ResumeAppInstallationResponse, error)
	RemoveAppInstallation(context.Context, *RemoveAppInstallationRequest) (*RemoveAppInstallationResponse, error)
	SetInstallationParticipantConsent(context.Context, *SetInstallationParticipantConsentRequest) (*SetInstallationParticipantConsentResponse, error)
	ListMyInstallationParticipantConsents(context.Context, *ListMyInstallationParticipantConsentsRequest) (*ListMyInstallationParticipantConsentsResponse, error)
}

// UnimplementedAppInstallationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppInstallationServiceServer struct{}

func (UnimplementedAppInstallationServiceServer) InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallApp not implemented")
}
func (UnimplementedAppInstallationServiceServer) AddAppToMyMap(context.Context, *AddAppToMyMapRequest) (*AddAppToMyMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAppToMyMap not implemented")
}
func (UnimplementedAppInstallationServiceServer) GetAppInstallation(context.Context, *GetAppInstallationRequest) (*GetAppInstallationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppInstallation not implemented")
}
func (UnimplementedAppInstallationServiceServer) ListAppInstallations(context.Context, *ListAppInstallationsRequest) (*ListAppInstallationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppInstallations not implemented")
}
func (UnimplementedAppInstallationServiceServer) SuspendAppInstallation(context.Context, *SuspendAppInstallationRequest) (*SuspendAppInstallationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendAppInstallation not implemented")
}
func (UnimplementedAppInstallationServiceServer) ResumeAppInstallation(context.Context, *ResumeAppInstallationRequest) (*ResumeAppInstallationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeAppInstallation not implemented")
}
func (UnimplementedAppInstallationServiceServer) RemoveAppInstallation(context.Context, *RemoveAppInstallationRequest) (*RemoveAppInstallationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAppInstallation not implemented")
}
func (UnimplementedAppInstallationServiceServer) SetInstallationParticipantConsent(context.Context, *SetInstallationParticipantConsentRequest) (*SetInstallationParticipantConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInstallationParticipantConsent not implemented")
}
func (UnimplementedAppInstallationServiceServer) ListMyInstallationParticipantConsents(context.Context, *ListMyInstallationParticipantConsentsRequest) (*ListMyInstallationParticipantConsentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyInstallationParticipantConsents not implemented")
}
func (UnimplementedAppInstallationServiceServer) testEmbeddedByValue() {}

// UnsafeAppInstallationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppInstallationServiceServer will
// result in compilation errors.
type UnsafeAppInstallationServiceServer interface {
	mustEmbedUnimplementedAppInstallationServiceServer()
}

func RegisterAppInstallationServiceServer(s grpc.ServiceRegistrar, srv AppInstallationServiceServer) {
	// If the following call panics, it indicates UnimplementedAppInstallationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppInstallationService_ServiceDesc, srv)
}

func _AppInstallationService_InstallApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).InstallApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_InstallApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).InstallApp(ctx, req.(*InstallAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_AddAppToMyMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAppToMyMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).AddAppToMyMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_AddAppToMyMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).AddAppToMyMap(ctx, req.(*AddAppToMyMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_GetAppInstallation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppInstallationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).GetAppInstallation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_GetAppInstallation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).GetAppInstallation(ctx, req.(*GetAppInstallationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_ListAppInstallations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppInstallationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).ListAppInstallations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_ListAppInstallations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).ListAppInstallations(ctx, req.(*ListAppInstallationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_SuspendAppInstallation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendAppInstallationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).SuspendAppInstallation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_SuspendAppInstallation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).SuspendAppInstallation(ctx, req.(*SuspendAppInstallationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_ResumeAppInstallation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeAppInstallationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).ResumeAppInstallation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_ResumeAppInstallation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).ResumeAppInstallation(ctx, req.(*ResumeAppInstallationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_RemoveAppInstallation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAppInstallationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).RemoveAppInstallation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_RemoveAppInstallation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).RemoveAppInstallation(ctx, req.(*RemoveAppInstallationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_SetInstallationParticipantConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstallationParticipantConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).SetInstallationParticipantConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_SetInstallationParticipantConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).SetInstallationParticipantConsent(ctx, req.(*SetInstallationParticipantConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppInstallationService_ListMyInstallationParticipantConsents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyInstallationParticipantConsentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppInstallationServiceServer).ListMyInstallationParticipantConsents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppInstallationService_ListMyInstallationParticipantConsents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppInstallationServiceServer).ListMyInstallationParticipantConsents(ctx, req.(*ListMyInstallationParticipantConsentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppInstallationService_ServiceDesc is the grpc.ServiceDesc for AppInstallationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppInstallationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qwibi.v1.AppInstallationService",
	HandlerType: (*AppInstallationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallApp",
			Handler:    _AppInstallationService_InstallApp_Handler,
		},
		{
			MethodName: "AddAppToMyMap",
			Handler:    _AppInstallationService_AddAppToMyMap_Handler,
		},
		{
			MethodName: "GetAppInstallation",
			Handler:    _AppInstallationService_GetAppInstallation_Handler,
		},
		{
			MethodName: "ListAppInstallations",
			Handler:    _AppInstallationService_ListAppInstallations_Handler,
		},
		{
			MethodName: "SuspendAppInstallation",
			Handler:    _AppInstallationService_SuspendAppInstallation_Handler,
		},
		{
			MethodName: "ResumeAppInstallation",
			Handler:    _AppInstallationService_ResumeAppInstallation_Handler,
		},
		{
			MethodName: "RemoveAppInstallation",
			Handler:    _AppInstallationService_RemoveAppInstallation_Handler,
		},
		{
			MethodName: "SetInstallationParticipantConsent",
			Handler:    _AppInstallationService_SetInstallationParticipantConsent_Handler,
		},
		{
			MethodName: "ListMyInstallationParticipantConsents",
			Handler:    _AppInstallationService_ListMyInstallationParticipantConsents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qwibi/v1/app_installation.proto",
}
