// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/app_data.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutAppObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Objects       []*ObjectWrite         `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	Upsert        bool                   `protobuf:"varint,3,opt,name=upsert,proto3" json:"upsert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppObjectsRequest) Reset() {
	*x = PutAppObjectsRequest{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppObjectsRequest) ProtoMessage() {}

func (x *PutAppObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppObjectsRequest.ProtoReflect.Descriptor instead.
func (*PutAppObjectsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{0}
}

func (x *PutAppObjectsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PutAppObjectsRequest) GetObjects() []*ObjectWrite {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *PutAppObjectsRequest) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

type PutAppObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*GeoObject           `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppObjectsResponse) Reset() {
	*x = PutAppObjectsResponse{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppObjectsResponse) ProtoMessage() {}

func (x *PutAppObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppObjectsResponse.ProtoReflect.Descriptor instead.
func (*PutAppObjectsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{1}
}

func (x *PutAppObjectsResponse) GetObjects() []*GeoObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

// Atomically make the supplied HID set the complete App data set.
type ReplaceAppObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Objects       []*ObjectWrite         `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceAppObjectsRequest) Reset() {
	*x = ReplaceAppObjectsRequest{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceAppObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceAppObjectsRequest) ProtoMessage() {}

func (x *ReplaceAppObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceAppObjectsRequest.ProtoReflect.Descriptor instead.
func (*ReplaceAppObjectsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{2}
}

func (x *ReplaceAppObjectsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReplaceAppObjectsRequest) GetObjects() []*ObjectWrite {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ReplaceAppObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*GeoObject           `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceAppObjectsResponse) Reset() {
	*x = ReplaceAppObjectsResponse{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceAppObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceAppObjectsResponse) ProtoMessage() {}

func (x *ReplaceAppObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceAppObjectsResponse.ProtoReflect.Descriptor instead.
func (*ReplaceAppObjectsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{3}
}

func (x *ReplaceAppObjectsResponse) GetObjects() []*GeoObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type DeleteAppObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ObjectIds     []string               `protobuf:"bytes,2,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	Hids          []string               `protobuf:"bytes,3,rep,name=hids,proto3" json:"hids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppObjectsRequest) Reset() {
	*x = DeleteAppObjectsRequest{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppObjectsRequest) ProtoMessage() {}

func (x *DeleteAppObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppObjectsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppObjectsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAppObjectsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeleteAppObjectsRequest) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *DeleteAppObjectsRequest) GetHids() []string {
	if x != nil {
		return x.Hids
	}
	return nil
}

type DeleteAppObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectIds     []string               `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppObjectsResponse) Reset() {
	*x = DeleteAppObjectsResponse{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppObjectsResponse) ProtoMessage() {}

func (x *DeleteAppObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppObjectsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppObjectsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAppObjectsResponse) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

type MoveAppObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Moves         []*ObjectMove          `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveAppObjectsRequest) Reset() {
	*x = MoveAppObjectsRequest{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveAppObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAppObjectsRequest) ProtoMessage() {}

func (x *MoveAppObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAppObjectsRequest.ProtoReflect.Descriptor instead.
func (*MoveAppObjectsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{6}
}

func (x *MoveAppObjectsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *MoveAppObjectsRequest) GetMoves() []*ObjectMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type MoveAppObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []uint64               `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveAppObjectsResponse) Reset() {
	*x = MoveAppObjectsResponse{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveAppObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAppObjectsResponse) ProtoMessage() {}

func (x *MoveAppObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAppObjectsResponse.ProtoReflect.Descriptor instead.
func (*MoveAppObjectsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{7}
}

func (x *MoveAppObjectsResponse) GetVersions() []uint64 {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ListAppObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppObjectsRequest) Reset() {
	*x = ListAppObjectsRequest{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppObjectsRequest) ProtoMessage() {}

func (x *ListAppObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListAppObjectsRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{8}
}

func (x *ListAppObjectsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListAppObjectsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAppObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*GeoObject           `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppObjectsResponse) Reset() {
	*x = ListAppObjectsResponse{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppObjectsResponse) ProtoMessage() {}

func (x *ListAppObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListAppObjectsResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{9}
}

func (x *ListAppObjectsResponse) GetObjects() []*GeoObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListAppObjectsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// Upload bytes from the App process. picture_ref is an opaque, same-origin
// reference and is stable for the same content within this App only.
type PutAppPictureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppPictureRequest) Reset() {
	*x = PutAppPictureRequest{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppPictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppPictureRequest) ProtoMessage() {}

func (x *PutAppPictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppPictureRequest.ProtoReflect.Descriptor instead.
func (*PutAppPictureRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{10}
}

func (x *PutAppPictureRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PutAppPictureRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PutAppPictureRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type PutAppPictureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PictureRef    string                 `protobuf:"bytes,1,opt,name=picture_ref,json=pictureRef,proto3" json:"picture_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppPictureResponse) Reset() {
	*x = PutAppPictureResponse{}
	mi := &file_qwibi_v1_app_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppPictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppPictureResponse) ProtoMessage() {}

func (x *PutAppPictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppPictureResponse.ProtoReflect.Descriptor instead.
func (*PutAppPictureResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_data_proto_rawDescGZIP(), []int{11}
}

func (x *PutAppPictureResponse) GetPictureRef() string {
	if x != nil {
		return x.PictureRef
	}
	return ""
}

var File_qwibi_v1_app_data_proto protoreflect.FileDescriptor

const file_qwibi_v1_app_data_proto_rawDesc = "" +
	"\n" +
	"\x17qwibi/v1/app_data.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x15qwibi/v1/common.proto\x1a\x15qwibi/v1/object.proto\x1a\x16qwibi/v1/service.proto\"\xcd\x01\n" +
	"\x14PutAppObjectsRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12<\n" +
	"\aobjects\x18\x02 \x03(\v2\x15.qwibi.v1.ObjectWriteB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\aobjects\x12\x16\n" +
	"\x06upsert\x18\x03 \x01(\bR\x06upsert\"F\n" +
	"\x15PutAppObjectsResponse\x12-\n" +
	"\aobjects\x18\x01 \x03(\v2\x13.qwibi.v1.GeoObjectR\aobjects\"\xb7\x01\n" +
	"\x18ReplaceAppObjectsRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12:\n" +
	"\aobjects\x18\x02 \x03(\v2\x15.qwibi.v1.ObjectWriteB\t\xbaH\x06\x92\x01\x03\x10\xe8\aR\aobjects\"J\n" +
	"\x19ReplaceAppObjectsResponse\x12-\n" +
	"\aobjects\x18\x01 \x03(\v2\x13.qwibi.v1.GeoObjectR\aobjects\"\xad\x02\n" +
	"\x17DeleteAppObjectsRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12q\n" +
	"\n" +
	"object_ids\x18\x02 \x03(\tBR\xbaHO\x92\x01L\x10\xe8\a\x18\x01\"ErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\tobjectIds\x12>\n" +
	"\x04hids\x18\x03 \x03(\tB*\xbaH'\x92\x01$\x10\xe8\a\x18\x01\"\x1dr\x1b2\x19^[a-z0-9][a-z0-9-]{1,62}$R\x04hids\"9\n" +
	"\x18DeleteAppObjectsResponse\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\tR\tobjectIds\"\xb1\x01\n" +
	"\x15MoveAppObjectsRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x127\n" +
	"\x05moves\x18\x02 \x03(\v2\x14.qwibi.v1.ObjectMoveB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x05moves\"4\n" +
	"\x16MoveAppObjectsResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\x04R\bversions\"\xa3\x01\n" +
	"\x15ListAppObjectsRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.qwibi.v1.PageRequestR\x04page\"s\n" +
	"\x16ListAppObjectsResponse\x12-\n" +
	"\aobjects\x18\x01 \x03(\v2\x13.qwibi.v1.GeoObjectR\aobjects\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.qwibi.v1.PageResponseR\x04page\"\xc6\x01\n" +
	"\x14PutAppPictureRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12!\n" +
	"\acontent\x18\x02 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\acontent\x12*\n" +
	"\fcontent_type\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x18@R\vcontentType\"8\n" +
	"\x15PutAppPictureResponse\x12\x1f\n" +
	"\vpicture_ref\x18\x01 \x01(\tR\n" +
	"pictureRef2\x97\x04\n" +
	"\x0eAppDataService\x12P\n" +
	"\rPutAppPicture\x12\x1e.qwibi.v1.PutAppPictureRequest\x1a\x1f.qwibi.v1.PutAppPictureResponse\x12P\n" +
	"\rPutAppObjects\x12\x1e.qwibi.v1.PutAppObjectsRequest\x1a\x1f.qwibi.v1.PutAppObjectsResponse\x12\\\n" +
	"\x11ReplaceAppObjects\x12\".qwibi.v1.ReplaceAppObjectsRequest\x1a#.qwibi.v1.ReplaceAppObjectsResponse\x12Y\n" +
	"\x10DeleteAppObjects\x12!.qwibi.v1.DeleteAppObjectsRequest\x1a\".qwibi.v1.DeleteAppObjectsResponse\x12S\n" +
	"\x0eMoveAppObjects\x12\x1f.qwibi.v1.MoveAppObjectsRequest\x1a .qwibi.v1.MoveAppObjectsResponse\x12S\n" +
	"\x0eListAppObjects\x12\x1f.qwibi.v1.ListAppObjectsRequest\x1a .qwibi.v1.ListAppObjectsResponseB\x8f\x01\n" +
	"\fcom.qwibi.v1B\fAppDataProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_app_data_proto_rawDescOnce sync.Once
	file_qwibi_v1_app_data_proto_rawDescData []byte
)

func file_qwibi_v1_app_data_proto_rawDescGZIP() []byte {
	file_qwibi_v1_app_data_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_app_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_data_proto_rawDesc), len(file_qwibi_v1_app_data_proto_rawDesc)))
	})
	return file_qwibi_v1_app_data_proto_rawDescData
}

var file_qwibi_v1_app_data_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_qwibi_v1_app_data_proto_goTypes = []any{
	(*PutAppObjectsRequest)(nil),      // 0: qwibi.v1.PutAppObjectsRequest
	(*PutAppObjectsResponse)(nil),     // 1: qwibi.v1.PutAppObjectsResponse
	(*ReplaceAppObjectsRequest)(nil),  // 2: qwibi.v1.ReplaceAppObjectsRequest
	(*ReplaceAppObjectsResponse)(nil), // 3: qwibi.v1.ReplaceAppObjectsResponse
	(*DeleteAppObjectsRequest)(nil),   // 4: qwibi.v1.DeleteAppObjectsRequest
	(*DeleteAppObjectsResponse)(nil),  // 5: qwibi.v1.DeleteAppObjectsResponse
	(*MoveAppObjectsRequest)(nil),     // 6: qwibi.v1.MoveAppObjectsRequest
	(*MoveAppObjectsResponse)(nil),    // 7: qwibi.v1.MoveAppObjectsResponse
	(*ListAppObjectsRequest)(nil),     // 8: qwibi.v1.ListAppObjectsRequest
	(*ListAppObjectsResponse)(nil),    // 9: qwibi.v1.ListAppObjectsResponse
	(*PutAppPictureRequest)(nil),      // 10: qwibi.v1.PutAppPictureRequest
	(*PutAppPictureResponse)(nil),     // 11: qwibi.v1.PutAppPictureResponse
	(*ObjectWrite)(nil),               // 12: qwibi.v1.ObjectWrite
	(*GeoObject)(nil),                 // 13: qwibi.v1.GeoObject
	(*ObjectMove)(nil),                // 14: qwibi.v1.ObjectMove
	(*PageRequest)(nil),               // 15: qwibi.v1.PageRequest
	(*PageResponse)(nil),              // 16: qwibi.v1.PageResponse
}
var file_qwibi_v1_app_data_proto_depIdxs = []int32{
	12, // 0: qwibi.v1.PutAppObjectsRequest.objects:type_name -> qwibi.v1.ObjectWrite
	13, // 1: qwibi.v1.PutAppObjectsResponse.objects:type_name -> qwibi.v1.GeoObject
	12, // 2: qwibi.v1.ReplaceAppObjectsRequest.objects:type_name -> qwibi.v1.ObjectWrite
	13, // 3: qwibi.v1.ReplaceAppObjectsResponse.objects:type_name -> qwibi.v1.GeoObject
	14, // 4: qwibi.v1.MoveAppObjectsRequest.moves:type_name -> qwibi.v1.ObjectMove
	15, // 5: qwibi.v1.ListAppObjectsRequest.page:type_name -> qwibi.v1.PageRequest
	13, // 6: qwibi.v1.ListAppObjectsResponse.objects:type_name -> qwibi.v1.GeoObject
	16, // 7: qwibi.v1.ListAppObjectsResponse.page:type_name -> qwibi.v1.PageResponse
	10, // 8: qwibi.v1.AppDataService.PutAppPicture:input_type -> qwibi.v1.PutAppPictureRequest
	0,  // 9: qwibi.v1.AppDataService.PutAppObjects:input_type -> qwibi.v1.PutAppObjectsRequest
	2,  // 10: qwibi.v1.AppDataService.ReplaceAppObjects:input_type -> qwibi.v1.ReplaceAppObjectsRequest
	4,  // 11: qwibi.v1.AppDataService.DeleteAppObjects:input_type -> qwibi.v1.DeleteAppObjectsRequest
	6,  // 12: qwibi.v1.AppDataService.MoveAppObjects:input_type -> qwibi.v1.MoveAppObjectsRequest
	8,  // 13: qwibi.v1.AppDataService.ListAppObjects:input_type -> qwibi.v1.ListAppObjectsRequest
	11, // 14: qwibi.v1.AppDataService.PutAppPicture:output_type -> qwibi.v1.PutAppPictureResponse
	1,  // 15: qwibi.v1.AppDataService.PutAppObjects:output_type -> qwibi.v1.PutAppObjectsResponse
	3,  // 16: qwibi.v1.AppDataService.ReplaceAppObjects:output_type -> qwibi.v1.ReplaceAppObjectsResponse
	5,  // 17: qwibi.v1.AppDataService.DeleteAppObjects:output_type -> qwibi.v1.DeleteAppObjectsResponse
	7,  // 18: qwibi.v1.AppDataService.MoveAppObjects:output_type -> qwibi.v1.MoveAppObjectsResponse
	9,  // 19: qwibi.v1.AppDataService.ListAppObjects:output_type -> qwibi.v1.ListAppObjectsResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_qwibi_v1_app_data_proto_init() }
func file_qwibi_v1_app_data_proto_init() {
	if File_qwibi_v1_app_data_proto != nil {
		return
	}
	file_qwibi_v1_common_proto_init()
	file_qwibi_v1_object_proto_init()
	file_qwibi_v1_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_data_proto_rawDesc), len(file_qwibi_v1_app_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qwibi_v1_app_data_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_app_data_proto_depIdxs,
		MessageInfos:      file_qwibi_v1_app_data_proto_msgTypes,
	}.Build()
	File_qwibi_v1_app_data_proto = out.File
	file_qwibi_v1_app_data_proto_goTypes = nil
	file_qwibi_v1_app_data_proto_depIdxs = nil
}
