// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: qwibi/v1/app_member.proto

package qwibiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppMemberService_ListAppMembers_FullMethodName      = "/qwibi.v1.AppMemberService/ListAppMembers"
	AppMemberService_CreateAppInviteLink_FullMethodName = "/qwibi.v1.AppMemberService/CreateAppInviteLink"
	AppMemberService_ListAppInviteLinks_FullMethodName  = "/qwibi.v1.AppMemberService/ListAppInviteLinks"
	AppMemberService_RevokeAppInviteLink_FullMethodName = "/qwibi.v1.AppMemberService/RevokeAppInviteLink"
	AppMemberService_SetAppMemberRole_FullMethodName    = "/qwibi.v1.AppMemberService/SetAppMemberRole"
	AppMemberService_RemoveAppMember_FullMethodName     = "/qwibi.v1.AppMemberService/RemoveAppMember"
	AppMemberService_JoinApp_FullMethodName             = "/qwibi.v1.AppMemberService/JoinApp"
)

// AppMemberServiceClient is the client API for AppMemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppMemberServiceClient interface {
	// Holders of the App's publisher grants list, invite and remove members.
	ListAppMembers(ctx context.Context, in *ListAppMembersRequest, opts ...grpc.CallOption) (*ListAppMembersResponse, error)
	CreateAppInviteLink(ctx context.Context, in *CreateAppInviteLinkRequest, opts ...grpc.CallOption) (*CreateAppInviteLinkResponse, error)
	ListAppInviteLinks(ctx context.Context, in *ListAppInviteLinksRequest, opts ...grpc.CallOption) (*ListAppInviteLinksResponse, error)
	// Revoking stops new joins; members who joined through the link stay.
	RevokeAppInviteLink(ctx context.Context, in *RevokeAppInviteLinkRequest, opts ...grpc.CallOption) (*RevokeAppInviteLinkResponse, error)
	// Changing a member's role closes their open streams of the App's data; a
	// role grants reading only.
	SetAppMemberRole(ctx context.Context, in *SetAppMemberRoleRequest, opts ...grpc.CallOption) (*SetAppMemberRoleResponse, error)
	// Removing a member closes their open streams of the App's data, ends their
	// open calls and withholds their kept answers.
	RemoveAppMember(ctx context.Context, in *RemoveAppMemberRequest, opts ...grpc.CallOption) (*RemoveAppMemberResponse, error)
	// A person with a confirmed email joins a private App through a live link.
	JoinApp(ctx context.Context, in *JoinAppRequest, opts ...grpc.CallOption) (*JoinAppResponse, error)
}

type appMemberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppMemberServiceClient(cc grpc.ClientConnInterface) AppMemberServiceClient {
	return &appMemberServiceClient{cc}
}

func (c *appMemberServiceClient) ListAppMembers(ctx context.Context, in *ListAppMembersRequest, opts ...grpc.CallOption) (*ListAppMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppMembersResponse)
	err := c.cc.Invoke(ctx, AppMemberService_ListAppMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMemberServiceClient) CreateAppInviteLink(ctx context.Context, in *CreateAppInviteLinkRequest, opts ...grpc.CallOption) (*CreateAppInviteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppInviteLinkResponse)
	err := c.cc.Invoke(ctx, AppMemberService_CreateAppInviteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMemberServiceClient) ListAppInviteLinks(ctx context.Context, in *ListAppInviteLinksRequest, opts ...grpc.CallOption) (*ListAppInviteLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppInviteLinksResponse)
	err := c.cc.Invoke(ctx, AppMemberService_ListAppInviteLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMemberServiceClient) RevokeAppInviteLink(ctx context.Context, in *RevokeAppInviteLinkRequest, opts ...grpc.CallOption) (*RevokeAppInviteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAppInviteLinkResponse)
	err := c.cc.Invoke(ctx, AppMemberService_RevokeAppInviteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMemberServiceClient) SetAppMemberRole(ctx context.Context, in *SetAppMemberRoleRequest, opts ...grpc.CallOption) (*SetAppMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAppMemberRoleResponse)
	err := c.cc.Invoke(ctx, AppMemberService_SetAppMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMemberServiceClient) RemoveAppMember(ctx context.Context, in *RemoveAppMemberRequest, opts ...grpc.CallOption) (*RemoveAppMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAppMemberResponse)
	err := c.cc.Invoke(ctx, AppMemberService_RemoveAppMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMemberServiceClient) JoinApp(ctx context.Context, in *JoinAppRequest, opts ...grpc.CallOption) (*JoinAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinAppResponse)
	err := c.cc.Invoke(ctx, AppMemberService_JoinApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppMemberServiceServer is the server API for AppMemberService service.
// All implementations should embed UnimplementedAppMemberServiceServer
// for forward compatibility.
type AppMemberServiceServer interface {
	// Holders of the App's publisher grants list, invite and remove members.
	ListAppMembers(context.Context, *ListAppMembersRequest) (*ListAppMembersResponse, error)
	CreateAppInviteLink(context.Context, *CreateAppInviteLinkRequest) (*CreateAppInviteLinkResponse, error)
	ListAppInviteLinks(context.Context, *ListAppInviteLinksRequest) (*ListAppInviteLinksResponse, error)
	// Revoking stops new joins; members who joined through the link stay.
	RevokeAppInviteLink(context.Context, *RevokeAppInviteLinkRequest) (*RevokeAppInviteLinkResponse, error)
	// Changing a member's role closes their open streams of the App's data; a
	// role grants reading only.
	SetAppMemberRole(context.Context, *SetAppMemberRoleRequest) (*SetAppMemberRoleResponse, error)
	// Removing a member closes their open streams of the App's data, ends their
	// open calls and withholds their kept answers.
	RemoveAppMember(context.Context, *RemoveAppMemberRequest) (*RemoveAppMemberResponse, error)
	// A person with a confirmed email joins a private App through a live link.
	JoinApp(context.Context, *JoinAppRequest) (*JoinAppResponse, error)
}

// UnimplementedAppMemberServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppMemberServiceServer struct{}

func (UnimplementedAppMemberServiceServer) ListAppMembers(context.Context, *ListAppMembersRequest) (*ListAppMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppMembers not implemented")
}
func (UnimplementedAppMemberServiceServer) CreateAppInviteLink(context.Context, *CreateAppInviteLinkRequest) (*CreateAppInviteLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAppInviteLink not implemented")
}
func (UnimplementedAppMemberServiceServer) ListAppInviteLinks(context.Context, *ListAppInviteLinksRequest) (*ListAppInviteLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppInviteLinks not implemented")
}
func (UnimplementedAppMemberServiceServer) RevokeAppInviteLink(context.Context, *RevokeAppInviteLinkRequest) (*RevokeAppInviteLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAppInviteLink not implemented")
}
func (UnimplementedAppMemberServiceServer) SetAppMemberRole(context.Context, *SetAppMemberRoleRequest) (*SetAppMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAppMemberRole not implemented")
}
func (UnimplementedAppMemberServiceServer) RemoveAppMember(context.Context, *RemoveAppMemberRequest) (*RemoveAppMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAppMember not implemented")
}
func (UnimplementedAppMemberServiceServer) JoinApp(context.Context, *JoinAppRequest) (*JoinAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinApp not implemented")
}
func (UnimplementedAppMemberServiceServer) testEmbeddedByValue() {}

// UnsafeAppMemberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppMemberServiceServer will
// result in compilation errors.
type UnsafeAppMemberServiceServer interface {
	mustEmbedUnimplementedAppMemberServiceServer()
}

func RegisterAppMemberServiceServer(s grpc.ServiceRegistrar, srv AppMemberServiceServer) {
	// If the following call panics, it indicates UnimplementedAppMemberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppMemberService_ServiceDesc, srv)
}

func _AppMemberService_ListAppMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMemberServiceServer).ListAppMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMemberService_ListAppMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMemberServiceServer).ListAppMembers(ctx, req.(*ListAppMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMemberService_CreateAppInviteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppInviteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMemberServiceServer).CreateAppInviteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMemberService_CreateAppInviteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMemberServiceServer).CreateAppInviteLink(ctx, req.(*CreateAppInviteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMemberService_ListAppInviteLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppInviteLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMemberServiceServer).ListAppInviteLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMemberService_ListAppInviteLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMemberServiceServer).ListAppInviteLinks(ctx, req.(*ListAppInviteLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMemberService_RevokeAppInviteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAppInviteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMemberServiceServer).RevokeAppInviteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMemberService_RevokeAppInviteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMemberServiceServer).RevokeAppInviteLink(ctx, req.(*RevokeAppInviteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMemberService_SetAppMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAppMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMemberServiceServer).SetAppMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMemberService_SetAppMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMemberServiceServer).SetAppMemberRole(ctx, req.(*SetAppMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMemberService_RemoveAppMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAppMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMemberServiceServer).RemoveAppMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMemberService_RemoveAppMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMemberServiceServer).RemoveAppMember(ctx, req.(*RemoveAppMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMemberService_JoinApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMemberServiceServer).JoinApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMemberService_JoinApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMemberServiceServer).JoinApp(ctx, req.(*JoinAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppMemberService_ServiceDesc is the grpc.ServiceDesc for AppMemberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppMemberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qwibi.v1.AppMemberService",
	HandlerType: (*AppMemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAppMembers",
			Handler:    _AppMemberService_ListAppMembers_Handler,
		},
		{
			MethodName: "CreateAppInviteLink",
			Handler:    _AppMemberService_CreateAppInviteLink_Handler,
		},
		{
			MethodName: "ListAppInviteLinks",
			Handler:    _AppMemberService_ListAppInviteLinks_Handler,
		},
		{
			MethodName: "RevokeAppInviteLink",
			Handler:    _AppMemberService_RevokeAppInviteLink_Handler,
		},
		{
			MethodName: "SetAppMemberRole",
			Handler:    _AppMemberService_SetAppMemberRole_Handler,
		},
		{
			MethodName: "RemoveAppMember",
			Handler:    _AppMemberService_RemoveAppMember_Handler,
		},
		{
			MethodName: "JoinApp",
			Handler:    _AppMemberService_JoinApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qwibi/v1/app_member.proto",
}
