// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: qwibi/v1/app_release_service.proto

package qwibiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppReleaseService_PublishAppRelease_FullMethodName  = "/qwibi.v1.AppReleaseService/PublishAppRelease"
	AppReleaseService_GetAppRelease_FullMethodName      = "/qwibi.v1.AppReleaseService/GetAppRelease"
	AppReleaseService_ListAppReleases_FullMethodName    = "/qwibi.v1.AppReleaseService/ListAppReleases"
	AppReleaseService_SuspendAppRelease_FullMethodName  = "/qwibi.v1.AppReleaseService/SuspendAppRelease"
	AppReleaseService_ResumeAppRelease_FullMethodName   = "/qwibi.v1.AppReleaseService/ResumeAppRelease"
	AppReleaseService_GetReleaseAsset_FullMethodName    = "/qwibi.v1.AppReleaseService/GetReleaseAsset"
	AppReleaseService_UploadReleaseAsset_FullMethodName = "/qwibi.v1.AppReleaseService/UploadReleaseAsset"
)

// AppReleaseServiceClient is the client API for AppReleaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AppReleaseService is intentionally separate from QwibiService. The native
// API server owns release authority and the gateway exposes this exact surface.
type AppReleaseServiceClient interface {
	PublishAppRelease(ctx context.Context, in *PublishAppReleaseRequest, opts ...grpc.CallOption) (*PublishAppReleaseResponse, error)
	GetAppRelease(ctx context.Context, in *GetAppReleaseRequest, opts ...grpc.CallOption) (*GetAppReleaseResponse, error)
	ListAppReleases(ctx context.Context, in *ListAppReleasesRequest, opts ...grpc.CallOption) (*ListAppReleasesResponse, error)
	SuspendAppRelease(ctx context.Context, in *SuspendAppReleaseRequest, opts ...grpc.CallOption) (*SuspendAppReleaseResponse, error)
	ResumeAppRelease(ctx context.Context, in *ResumeAppReleaseRequest, opts ...grpc.CallOption) (*ResumeAppReleaseResponse, error)
	GetReleaseAsset(ctx context.Context, in *GetReleaseAssetRequest, opts ...grpc.CallOption) (*GetReleaseAssetResponse, error)
	UploadReleaseAsset(ctx context.Context, in *UploadReleaseAssetRequest, opts ...grpc.CallOption) (*UploadReleaseAssetResponse, error)
}

type appReleaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppReleaseServiceClient(cc grpc.ClientConnInterface) AppReleaseServiceClient {
	return &appReleaseServiceClient{cc}
}

func (c *appReleaseServiceClient) PublishAppRelease(ctx context.Context, in *PublishAppReleaseRequest, opts ...grpc.CallOption) (*PublishAppReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAppReleaseResponse)
	err := c.cc.Invoke(ctx, AppReleaseService_PublishAppRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appReleaseServiceClient) GetAppRelease(ctx context.Context, in *GetAppReleaseRequest, opts ...grpc.CallOption) (*GetAppReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppReleaseResponse)
	err := c.cc.Invoke(ctx, AppReleaseService_GetAppRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appReleaseServiceClient) ListAppReleases(ctx context.Context, in *ListAppReleasesRequest, opts ...grpc.CallOption) (*ListAppReleasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppReleasesResponse)
	err := c.cc.Invoke(ctx, AppReleaseService_ListAppReleases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appReleaseServiceClient) SuspendAppRelease(ctx context.Context, in *SuspendAppReleaseRequest, opts ...grpc.CallOption) (*SuspendAppReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendAppReleaseResponse)
	err := c.cc.Invoke(ctx, AppReleaseService_SuspendAppRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appReleaseServiceClient) ResumeAppRelease(ctx context.Context, in *ResumeAppReleaseRequest, opts ...grpc.CallOption) (*ResumeAppReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeAppReleaseResponse)
	err := c.cc.Invoke(ctx, AppReleaseService_ResumeAppRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appReleaseServiceClient) GetReleaseAsset(ctx context.Context, in *GetReleaseAssetRequest, opts ...grpc.CallOption) (*GetReleaseAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReleaseAssetResponse)
	err := c.cc.Invoke(ctx, AppReleaseService_GetReleaseAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appReleaseServiceClient) UploadReleaseAsset(ctx context.Context, in *UploadReleaseAssetRequest, opts ...grpc.CallOption) (*UploadReleaseAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadReleaseAssetResponse)
	err := c.cc.Invoke(ctx, AppReleaseService_UploadReleaseAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppReleaseServiceServer is the server API for AppReleaseService service.
// All implementations should embed UnimplementedAppReleaseServiceServer
// for forward compatibility.
//
// AppReleaseService is intentionally separate from QwibiService. The native
// API server owns release authority and the gateway exposes this exact surface.
type AppReleaseServiceServer interface {
	PublishAppRelease(context.Context, *PublishAppReleaseRequest) (*PublishAppReleaseResponse, error)
	GetAppRelease(context.Context, *GetAppReleaseRequest) (*GetAppReleaseResponse, error)
	ListAppReleases(context.Context, *ListAppReleasesRequest) (*ListAppReleasesResponse, error)
	SuspendAppRelease(context.Context, *SuspendAppReleaseRequest) (*SuspendAppReleaseResponse, error)
	ResumeAppRelease(context.Context, *ResumeAppReleaseRequest) (*ResumeAppReleaseResponse, error)
	GetReleaseAsset(context.Context, *GetReleaseAssetRequest) (*GetReleaseAssetResponse, error)
	UploadReleaseAsset(context.Context, *UploadReleaseAssetRequest) (*UploadReleaseAssetResponse, error)
}

// UnimplementedAppReleaseServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppReleaseServiceServer struct{}

func (UnimplementedAppReleaseServiceServer) PublishAppRelease(context.Context, *PublishAppReleaseRequest) (*PublishAppReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishAppRelease not implemented")
}
func (UnimplementedAppReleaseServiceServer) GetAppRelease(context.Context, *GetAppReleaseRequest) (*GetAppReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppRelease not implemented")
}
func (UnimplementedAppReleaseServiceServer) ListAppReleases(context.Context, *ListAppReleasesRequest) (*ListAppReleasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppReleases not implemented")
}
func (UnimplementedAppReleaseServiceServer) SuspendAppRelease(context.Context, *SuspendAppReleaseRequest) (*SuspendAppReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendAppRelease not implemented")
}
func (UnimplementedAppReleaseServiceServer) ResumeAppRelease(context.Context, *ResumeAppReleaseRequest) (*ResumeAppReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeAppRelease not implemented")
}
func (UnimplementedAppReleaseServiceServer) GetReleaseAsset(context.Context, *GetReleaseAssetRequest) (*GetReleaseAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReleaseAsset not implemented")
}
func (UnimplementedAppReleaseServiceServer) UploadReleaseAsset(context.Context, *UploadReleaseAssetRequest) (*UploadReleaseAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadReleaseAsset not implemented")
}
func (UnimplementedAppReleaseServiceServer) testEmbeddedByValue() {}

// UnsafeAppReleaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppReleaseServiceServer will
// result in compilation errors.
type UnsafeAppReleaseServiceServer interface {
	mustEmbedUnimplementedAppReleaseServiceServer()
}

func RegisterAppReleaseServiceServer(s grpc.ServiceRegistrar, srv AppReleaseServiceServer) {
	// If the following call panics, it indicates UnimplementedAppReleaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppReleaseService_ServiceDesc, srv)
}

func _AppReleaseService_PublishAppRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishAppReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppReleaseServiceServer).PublishAppRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppReleaseService_PublishAppRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppReleaseServiceServer).PublishAppRelease(ctx, req.(*PublishAppReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppReleaseService_GetAppRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppReleaseServiceServer).GetAppRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppReleaseService_GetAppRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppReleaseServiceServer).GetAppRelease(ctx, req.(*GetAppReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppReleaseService_ListAppReleases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppReleasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppReleaseServiceServer).ListAppReleases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppReleaseService_ListAppReleases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppReleaseServiceServer).ListAppReleases(ctx, req.(*ListAppReleasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppReleaseService_SuspendAppRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendAppReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppReleaseServiceServer).SuspendAppRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppReleaseService_SuspendAppRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppReleaseServiceServer).SuspendAppRelease(ctx, req.(*SuspendAppReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppReleaseService_ResumeAppRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeAppReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppReleaseServiceServer).ResumeAppRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppReleaseService_ResumeAppRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppReleaseServiceServer).ResumeAppRelease(ctx, req.(*ResumeAppReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppReleaseService_GetReleaseAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReleaseAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppReleaseServiceServer).GetReleaseAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppReleaseService_GetReleaseAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppReleaseServiceServer).GetReleaseAsset(ctx, req.(*GetReleaseAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppReleaseService_UploadReleaseAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadReleaseAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppReleaseServiceServer).UploadReleaseAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppReleaseService_UploadReleaseAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppReleaseServiceServer).UploadReleaseAsset(ctx, req.(*UploadReleaseAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppReleaseService_ServiceDesc is the grpc.ServiceDesc for AppReleaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppReleaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qwibi.v1.AppReleaseService",
	HandlerType: (*AppReleaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishAppRelease",
			Handler:    _AppReleaseService_PublishAppRelease_Handler,
		},
		{
			MethodName: "GetAppRelease",
			Handler:    _AppReleaseService_GetAppRelease_Handler,
		},
		{
			MethodName: "ListAppReleases",
			Handler:    _AppReleaseService_ListAppReleases_Handler,
		},
		{
			MethodName: "SuspendAppRelease",
			Handler:    _AppReleaseService_SuspendAppRelease_Handler,
		},
		{
			MethodName: "ResumeAppRelease",
			Handler:    _AppReleaseService_ResumeAppRelease_Handler,
		},
		{
			MethodName: "GetReleaseAsset",
			Handler:    _AppReleaseService_GetReleaseAsset_Handler,
		},
		{
			MethodName: "UploadReleaseAsset",
			Handler:    _AppReleaseService_UploadReleaseAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qwibi/v1/app_release_service.proto",
}
