// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/app_member.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppInviteLinkState int32

const (
	AppInviteLinkState_APP_INVITE_LINK_STATE_UNSPECIFIED AppInviteLinkState = 0
	AppInviteLinkState_APP_INVITE_LINK_STATE_ACTIVE      AppInviteLinkState = 1
	AppInviteLinkState_APP_INVITE_LINK_STATE_EXPIRED     AppInviteLinkState = 2
	// The link admitted as many people as its use limit allows.
	AppInviteLinkState_APP_INVITE_LINK_STATE_EXHAUSTED AppInviteLinkState = 3
	AppInviteLinkState_APP_INVITE_LINK_STATE_REVOKED   AppInviteLinkState = 4
)

// Enum value maps for AppInviteLinkState.
var (
	AppInviteLinkState_name = map[int32]string{
		0: "APP_INVITE_LINK_STATE_UNSPECIFIED",
		1: "APP_INVITE_LINK_STATE_ACTIVE",
		2: "APP_INVITE_LINK_STATE_EXPIRED",
		3: "APP_INVITE_LINK_STATE_EXHAUSTED",
		4: "APP_INVITE_LINK_STATE_REVOKED",
	}
	AppInviteLinkState_value = map[string]int32{
		"APP_INVITE_LINK_STATE_UNSPECIFIED": 0,
		"APP_INVITE_LINK_STATE_ACTIVE":      1,
		"APP_INVITE_LINK_STATE_EXPIRED":     2,
		"APP_INVITE_LINK_STATE_EXHAUSTED":   3,
		"APP_INVITE_LINK_STATE_REVOKED":     4,
	}
)

func (x AppInviteLinkState) Enum() *AppInviteLinkState {
	p := new(AppInviteLinkState)
	*p = x
	return p
}

func (x AppInviteLinkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppInviteLinkState) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_app_member_proto_enumTypes[0].Descriptor()
}

func (AppInviteLinkState) Type() protoreflect.EnumType {
	return &file_qwibi_v1_app_member_proto_enumTypes[0]
}

func (x AppInviteLinkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppInviteLinkState.Descriptor instead.
func (AppInviteLinkState) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{0}
}

// AppMember is one person who may use a private App.
type AppMember struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccountId   string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The link the member joined through; empty for a member admitted by the
	// platform (the publisher who created or narrowed the App).
	InviteLinkId string                 `protobuf:"bytes,3,opt,name=invite_link_id,json=inviteLinkId,proto3" json:"invite_link_id,omitempty"`
	JoinedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	// The member role the member holds, one of the current release's
	// member_roles, or empty for none.
	RoleId        string `protobuf:"bytes,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppMember) Reset() {
	*x = AppMember{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMember) ProtoMessage() {}

func (x *AppMember) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMember.ProtoReflect.Descriptor instead.
func (*AppMember) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{0}
}

func (x *AppMember) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AppMember) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AppMember) GetInviteLinkId() string {
	if x != nil {
		return x.InviteLinkId
	}
	return ""
}

func (x *AppMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *AppMember) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

// AppInviteLink is an invitation anyone holding its token may use once each.
// Its token is returned only when the link is created.
type AppInviteLink struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	LinkId    string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	AppId     string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unset: the link does not expire.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Zero: no use limit.
	MaxUses       uint32                 `protobuf:"varint,5,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UseCount      uint32                 `protobuf:"varint,6,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	State         AppInviteLinkState     `protobuf:"varint,8,opt,name=state,proto3,enum=qwibi.v1.AppInviteLinkState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInviteLink) Reset() {
	*x = AppInviteLink{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInviteLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInviteLink) ProtoMessage() {}

func (x *AppInviteLink) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInviteLink.ProtoReflect.Descriptor instead.
func (*AppInviteLink) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{1}
}

func (x *AppInviteLink) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *AppInviteLink) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppInviteLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AppInviteLink) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AppInviteLink) GetMaxUses() uint32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *AppInviteLink) GetUseCount() uint32 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

func (x *AppInviteLink) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *AppInviteLink) GetState() AppInviteLinkState {
	if x != nil {
		return x.State
	}
	return AppInviteLinkState_APP_INVITE_LINK_STATE_UNSPECIFIED
}

type ListAppMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Page          *PageRequest           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppMembersRequest) Reset() {
	*x = ListAppMembersRequest{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppMembersRequest) ProtoMessage() {}

func (x *ListAppMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppMembersRequest.ProtoReflect.Descriptor instead.
func (*ListAppMembersRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{2}
}

func (x *ListAppMembersRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListAppMembersRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAppMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*AppMember           `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppMembersResponse) Reset() {
	*x = ListAppMembersResponse{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppMembersResponse) ProtoMessage() {}

func (x *ListAppMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppMembersResponse.ProtoReflect.Descriptor instead.
func (*ListAppMembersResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{3}
}

func (x *ListAppMembersResponse) GetMembers() []*AppMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListAppMembersResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type CreateAppInviteLinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	AppId string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Optional expiry; must be in the future.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Optional use limit; zero means unlimited.
	MaxUses       uint32 `protobuf:"varint,3,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppInviteLinkRequest) Reset() {
	*x = CreateAppInviteLinkRequest{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppInviteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppInviteLinkRequest) ProtoMessage() {}

func (x *CreateAppInviteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppInviteLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateAppInviteLinkRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAppInviteLinkRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateAppInviteLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateAppInviteLinkRequest) GetMaxUses() uint32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

type CreateAppInviteLinkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Link  *AppInviteLink         `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	// The secret the link carries. Shown once; the server keeps only its hash.
	InviteToken   string `protobuf:"bytes,2,opt,name=invite_token,json=inviteToken,proto3" json:"invite_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppInviteLinkResponse) Reset() {
	*x = CreateAppInviteLinkResponse{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppInviteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppInviteLinkResponse) ProtoMessage() {}

func (x *CreateAppInviteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppInviteLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateAppInviteLinkResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAppInviteLinkResponse) GetLink() *AppInviteLink {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *CreateAppInviteLinkResponse) GetInviteToken() string {
	if x != nil {
		return x.InviteToken
	}
	return ""
}

type ListAppInviteLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppInviteLinksRequest) Reset() {
	*x = ListAppInviteLinksRequest{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppInviteLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppInviteLinksRequest) ProtoMessage() {}

func (x *ListAppInviteLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppInviteLinksRequest.ProtoReflect.Descriptor instead.
func (*ListAppInviteLinksRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{6}
}

func (x *ListAppInviteLinksRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ListAppInviteLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*AppInviteLink       `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppInviteLinksResponse) Reset() {
	*x = ListAppInviteLinksResponse{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppInviteLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppInviteLinksResponse) ProtoMessage() {}

func (x *ListAppInviteLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppInviteLinksResponse.ProtoReflect.Descriptor instead.
func (*ListAppInviteLinksResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{7}
}

func (x *ListAppInviteLinksResponse) GetLinks() []*AppInviteLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type RevokeAppInviteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	LinkId        string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAppInviteLinkRequest) Reset() {
	*x = RevokeAppInviteLinkRequest{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAppInviteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAppInviteLinkRequest) ProtoMessage() {}

func (x *RevokeAppInviteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAppInviteLinkRequest.ProtoReflect.Descriptor instead.
func (*RevokeAppInviteLinkRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeAppInviteLinkRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RevokeAppInviteLinkRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type RevokeAppInviteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *AppInviteLink         `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAppInviteLinkResponse) Reset() {
	*x = RevokeAppInviteLinkResponse{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAppInviteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAppInviteLinkResponse) ProtoMessage() {}

func (x *RevokeAppInviteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAppInviteLinkResponse.ProtoReflect.Descriptor instead.
func (*RevokeAppInviteLinkResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeAppInviteLinkResponse) GetLink() *AppInviteLink {
	if x != nil {
		return x.Link
	}
	return nil
}

type SetAppMemberRoleRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AppId     string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountId string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// A role the current release declares, or empty to take the role away.
	RoleId        string `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppMemberRoleRequest) Reset() {
	*x = SetAppMemberRoleRequest{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppMemberRoleRequest) ProtoMessage() {}

func (x *SetAppMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*SetAppMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{10}
}

func (x *SetAppMemberRoleRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetAppMemberRoleRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SetAppMemberRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type SetAppMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *AppMember             `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppMemberRoleResponse) Reset() {
	*x = SetAppMemberRoleResponse{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppMemberRoleResponse) ProtoMessage() {}

func (x *SetAppMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*SetAppMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{11}
}

func (x *SetAppMemberRoleResponse) GetMember() *AppMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveAppMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAppMemberRequest) Reset() {
	*x = RemoveAppMemberRequest{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAppMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAppMemberRequest) ProtoMessage() {}

func (x *RemoveAppMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAppMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveAppMemberRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveAppMemberRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RemoveAppMemberRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RemoveAppMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAppMemberResponse) Reset() {
	*x = RemoveAppMemberResponse{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAppMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAppMemberResponse) ProtoMessage() {}

func (x *RemoveAppMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAppMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveAppMemberResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{13}
}

type JoinAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteToken   string                 `protobuf:"bytes,1,opt,name=invite_token,json=inviteToken,proto3" json:"invite_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAppRequest) Reset() {
	*x = JoinAppRequest{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAppRequest) ProtoMessage() {}

func (x *JoinAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAppRequest.ProtoReflect.Descriptor instead.
func (*JoinAppRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{14}
}

func (x *JoinAppRequest) GetInviteToken() string {
	if x != nil {
		return x.InviteToken
	}
	return ""
}

type JoinAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *GeoApp                `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAppResponse) Reset() {
	*x = JoinAppResponse{}
	mi := &file_qwibi_v1_app_member_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAppResponse) ProtoMessage() {}

func (x *JoinAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_app_member_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAppResponse.ProtoReflect.Descriptor instead.
func (*JoinAppResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_app_member_proto_rawDescGZIP(), []int{15}
}

func (x *JoinAppResponse) GetApp() *GeoApp {
	if x != nil {
		return x.App
	}
	return nil
}

var File_qwibi_v1_app_member_proto protoreflect.FileDescriptor

const file_qwibi_v1_app_member_proto_rawDesc = "" +
	"\n" +
	"\x19qwibi/v1/app_member.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12qwibi/v1/app.proto\x1a\x1bqwibi/v1/auth_options.proto\x1a\x15qwibi/v1/common.proto\"\xcf\x01\n" +
	"\tAppMember\x12'\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12$\n" +
	"\x0einvite_link_id\x18\x03 \x01(\tR\finviteLinkId\x127\n" +
	"\tjoined_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\tR\x06roleId\"\xf0\x02\n" +
	"\rAppInviteLink\x12!\n" +
	"\alink_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06linkId\x12\x1f\n" +
	"\x06app_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x19\n" +
	"\bmax_uses\x18\x05 \x01(\rR\amaxUses\x12\x1b\n" +
	"\tuse_count\x18\x06 \x01(\rR\buseCount\x129\n" +
	"\n" +
	"revoked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x122\n" +
	"\x05state\x18\b \x01(\x0e2\x1c.qwibi.v1.AppInviteLinkStateR\x05state\"c\n" +
	"\x15ListAppMembersRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x12)\n" +
	"\x04page\x18\x02 \x01(\v2\x15.qwibi.v1.PageRequestR\x04page\"s\n" +
	"\x16ListAppMembersResponse\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.qwibi.v1.AppMemberR\amembers\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.qwibi.v1.PageResponseR\x04page\"\x9e\x01\n" +
	"\x1aCreateAppInviteLinkRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\bmax_uses\x18\x03 \x01(\rB\t\xbaH\x06*\x04\x18\xa0\x8d\x06R\amaxUses\"m\n" +
	"\x1bCreateAppInviteLinkResponse\x12+\n" +
	"\x04link\x18\x01 \x01(\v2\x17.qwibi.v1.AppInviteLinkR\x04link\x12!\n" +
	"\finvite_token\x18\x02 \x01(\tR\vinviteToken\"<\n" +
	"\x19ListAppInviteLinksRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\"K\n" +
	"\x1aListAppInviteLinksResponse\x12-\n" +
	"\x05links\x18\x01 \x03(\v2\x17.qwibi.v1.AppInviteLinkR\x05links\"`\n" +
	"\x1aRevokeAppInviteLinkRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x12!\n" +
	"\alink_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06linkId\"J\n" +
	"\x1bRevokeAppInviteLinkResponse\x12+\n" +
	"\x04link\x18\x01 \x01(\v2\x17.qwibi.v1.AppInviteLinkR\x04link\"\xa1\x01\n" +
	"\x17SetAppMemberRoleRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12<\n" +
	"\arole_id\x18\x03 \x01(\tB#\xbaH r\x1e\x18@2\x1a^$|^[a-z][a-z0-9_-]{0,63}$R\x06roleId\"G\n" +
	"\x18SetAppMemberRoleResponse\x12+\n" +
	"\x06member\x18\x01 \x01(\v2\x13.qwibi.v1.AppMemberR\x06member\"b\n" +
	"\x16RemoveAppMemberRequest\x12\x1f\n" +
	"\x06app_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x05appId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\"\x19\n" +
	"\x17RemoveAppMemberResponse\"?\n" +
	"\x0eJoinAppRequest\x12-\n" +
	"\finvite_token\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\vinviteToken\"5\n" +
	"\x0fJoinAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.qwibi.v1.GeoAppR\x03app*\xc8\x01\n" +
	"\x12AppInviteLinkState\x12%\n" +
	"!APP_INVITE_LINK_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAPP_INVITE_LINK_STATE_ACTIVE\x10\x01\x12!\n" +
	"\x1dAPP_INVITE_LINK_STATE_EXPIRED\x10\x02\x12#\n" +
	"\x1fAPP_INVITE_LINK_STATE_EXHAUSTED\x10\x03\x12!\n" +
	"\x1dAPP_INVITE_LINK_STATE_REVOKED\x10\x042\xad\x05\n" +
	"\x10AppMemberService\x12Y\n" +
	"\x0eListAppMembers\x12\x1f.qwibi.v1.ListAppMembersRequest\x1a .qwibi.v1.ListAppMembersResponse\"\x04\x88\xb5\x18\x03\x12h\n" +
	"\x13CreateAppInviteLink\x12$.qwibi.v1.CreateAppInviteLinkRequest\x1a%.qwibi.v1.CreateAppInviteLinkResponse\"\x04\x88\xb5\x18\x03\x12e\n" +
	"\x12ListAppInviteLinks\x12#.qwibi.v1.ListAppInviteLinksRequest\x1a$.qwibi.v1.ListAppInviteLinksResponse\"\x04\x88\xb5\x18\x03\x12h\n" +
	"\x13RevokeAppInviteLink\x12$.qwibi.v1.RevokeAppInviteLinkRequest\x1a%.qwibi.v1.RevokeAppInviteLinkResponse\"\x04\x88\xb5\x18\x03\x12_\n" +
	"\x10SetAppMemberRole\x12!.qwibi.v1.SetAppMemberRoleRequest\x1a\".qwibi.v1.SetAppMemberRoleResponse\"\x04\x88\xb5\x18\x03\x12\\\n" +
	"\x0fRemoveAppMember\x12 .qwibi.v1.RemoveAppMemberRequest\x1a!.qwibi.v1.RemoveAppMemberResponse\"\x04\x88\xb5\x18\x03\x12D\n" +
	"\aJoinApp\x12\x18.qwibi.v1.JoinAppRequest\x1a\x19.qwibi.v1.JoinAppResponse\"\x04\x88\xb5\x18\x03B\x91\x01\n" +
	"\fcom.qwibi.v1B\x0eAppMemberProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_app_member_proto_rawDescOnce sync.Once
	file_qwibi_v1_app_member_proto_rawDescData []byte
)

func file_qwibi_v1_app_member_proto_rawDescGZIP() []byte {
	file_qwibi_v1_app_member_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_app_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_member_proto_rawDesc), len(file_qwibi_v1_app_member_proto_rawDesc)))
	})
	return file_qwibi_v1_app_member_proto_rawDescData
}

var file_qwibi_v1_app_member_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qwibi_v1_app_member_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_qwibi_v1_app_member_proto_goTypes = []any{
	(AppInviteLinkState)(0),             // 0: qwibi.v1.AppInviteLinkState
	(*AppMember)(nil),                   // 1: qwibi.v1.AppMember
	(*AppInviteLink)(nil),               // 2: qwibi.v1.AppInviteLink
	(*ListAppMembersRequest)(nil),       // 3: qwibi.v1.ListAppMembersRequest
	(*ListAppMembersResponse)(nil),      // 4: qwibi.v1.ListAppMembersResponse
	(*CreateAppInviteLinkRequest)(nil),  // 5: qwibi.v1.CreateAppInviteLinkRequest
	(*CreateAppInviteLinkResponse)(nil), // 6: qwibi.v1.CreateAppInviteLinkResponse
	(*ListAppInviteLinksRequest)(nil),   // 7: qwibi.v1.ListAppInviteLinksRequest
	(*ListAppInviteLinksResponse)(nil),  // 8: qwibi.v1.ListAppInviteLinksResponse
	(*RevokeAppInviteLinkRequest)(nil),  // 9: qwibi.v1.RevokeAppInviteLinkRequest
	(*RevokeAppInviteLinkResponse)(nil), // 10: qwibi.v1.RevokeAppInviteLinkResponse
	(*SetAppMemberRoleRequest)(nil),     // 11: qwibi.v1.SetAppMemberRoleRequest
	(*SetAppMemberRoleResponse)(nil),    // 12: qwibi.v1.SetAppMemberRoleResponse
	(*RemoveAppMemberRequest)(nil),      // 13: qwibi.v1.RemoveAppMemberRequest
	(*RemoveAppMemberResponse)(nil),     // 14: qwibi.v1.RemoveAppMemberResponse
	(*JoinAppRequest)(nil),              // 15: qwibi.v1.JoinAppRequest
	(*JoinAppResponse)(nil),             // 16: qwibi.v1.JoinAppResponse
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
	(*PageRequest)(nil),                 // 18: qwibi.v1.PageRequest
	(*PageResponse)(nil),                // 19: qwibi.v1.PageResponse
	(*GeoApp)(nil),                      // 20: qwibi.v1.GeoApp
}
var file_qwibi_v1_app_member_proto_depIdxs = []int32{
	17, // 0: qwibi.v1.AppMember.joined_at:type_name -> google.protobuf.Timestamp
	17, // 1: qwibi.v1.AppInviteLink.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: qwibi.v1.AppInviteLink.expires_at:type_name -> google.protobuf.Timestamp
	17, // 3: qwibi.v1.AppInviteLink.revoked_at:type_name -> google.protobuf.Timestamp
	0,  // 4: qwibi.v1.AppInviteLink.state:type_name -> qwibi.v1.AppInviteLinkState
	18, // 5: qwibi.v1.ListAppMembersRequest.page:type_name -> qwibi.v1.PageRequest
	1,  // 6: qwibi.v1.ListAppMembersResponse.members:type_name -> qwibi.v1.AppMember
	19, // 7: qwibi.v1.ListAppMembersResponse.page:type_name -> qwibi.v1.PageResponse
	17, // 8: qwibi.v1.CreateAppInviteLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 9: qwibi.v1.CreateAppInviteLinkResponse.link:type_name -> qwibi.v1.AppInviteLink
	2,  // 10: qwibi.v1.ListAppInviteLinksResponse.links:type_name -> qwibi.v1.AppInviteLink
	2,  // 11: qwibi.v1.RevokeAppInviteLinkResponse.link:type_name -> qwibi.v1.AppInviteLink
	1,  // 12: qwibi.v1.SetAppMemberRoleResponse.member:type_name -> qwibi.v1.AppMember
	20, // 13: qwibi.v1.JoinAppResponse.app:type_name -> qwibi.v1.GeoApp
	3,  // 14: qwibi.v1.AppMemberService.ListAppMembers:input_type -> qwibi.v1.ListAppMembersRequest
	5,  // 15: qwibi.v1.AppMemberService.CreateAppInviteLink:input_type -> qwibi.v1.CreateAppInviteLinkRequest
	7,  // 16: qwibi.v1.AppMemberService.ListAppInviteLinks:input_type -> qwibi.v1.ListAppInviteLinksRequest
	9,  // 17: qwibi.v1.AppMemberService.RevokeAppInviteLink:input_type -> qwibi.v1.RevokeAppInviteLinkRequest
	11, // 18: qwibi.v1.AppMemberService.SetAppMemberRole:input_type -> qwibi.v1.SetAppMemberRoleRequest
	13, // 19: qwibi.v1.AppMemberService.RemoveAppMember:input_type -> qwibi.v1.RemoveAppMemberRequest
	15, // 20: qwibi.v1.AppMemberService.JoinApp:input_type -> qwibi.v1.JoinAppRequest
	4,  // 21: qwibi.v1.AppMemberService.ListAppMembers:output_type -> qwibi.v1.ListAppMembersResponse
	6,  // 22: qwibi.v1.AppMemberService.CreateAppInviteLink:output_type -> qwibi.v1.CreateAppInviteLinkResponse
	8,  // 23: qwibi.v1.AppMemberService.ListAppInviteLinks:output_type -> qwibi.v1.ListAppInviteLinksResponse
	10, // 24: qwibi.v1.AppMemberService.RevokeAppInviteLink:output_type -> qwibi.v1.RevokeAppInviteLinkResponse
	12, // 25: qwibi.v1.AppMemberService.SetAppMemberRole:output_type -> qwibi.v1.SetAppMemberRoleResponse
	14, // 26: qwibi.v1.AppMemberService.RemoveAppMember:output_type -> qwibi.v1.RemoveAppMemberResponse
	16, // 27: qwibi.v1.AppMemberService.JoinApp:output_type -> qwibi.v1.JoinAppResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_qwibi_v1_app_member_proto_init() }
func file_qwibi_v1_app_member_proto_init() {
	if File_qwibi_v1_app_member_proto != nil {
		return
	}
	file_qwibi_v1_app_proto_init()
	file_qwibi_v1_auth_options_proto_init()
	file_qwibi_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_app_member_proto_rawDesc), len(file_qwibi_v1_app_member_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qwibi_v1_app_member_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_app_member_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_app_member_proto_enumTypes,
		MessageInfos:      file_qwibi_v1_app_member_proto_msgTypes,
	}.Build()
	File_qwibi_v1_app_member_proto = out.File
	file_qwibi_v1_app_member_proto_goTypes = nil
	file_qwibi_v1_app_member_proto_depIdxs = nil
}
