// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: qwibi/v1/app_data.proto

package qwibiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppDataService_PutAppPicture_FullMethodName     = "/qwibi.v1.AppDataService/PutAppPicture"
	AppDataService_PutAppObjects_FullMethodName     = "/qwibi.v1.AppDataService/PutAppObjects"
	AppDataService_ReplaceAppObjects_FullMethodName = "/qwibi.v1.AppDataService/ReplaceAppObjects"
	AppDataService_DeleteAppObjects_FullMethodName  = "/qwibi.v1.AppDataService/DeleteAppObjects"
	AppDataService_MoveAppObjects_FullMethodName    = "/qwibi.v1.AppDataService/MoveAppObjects"
	AppDataService_ListAppObjects_FullMethodName    = "/qwibi.v1.AppDataService/ListAppObjects"
)

// AppDataServiceClient is the client API for AppDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppDataServiceClient interface {
	PutAppPicture(ctx context.Context, in *PutAppPictureRequest, opts ...grpc.CallOption) (*PutAppPictureResponse, error)
	PutAppObjects(ctx context.Context, in *PutAppObjectsRequest, opts ...grpc.CallOption) (*PutAppObjectsResponse, error)
	ReplaceAppObjects(ctx context.Context, in *ReplaceAppObjectsRequest, opts ...grpc.CallOption) (*ReplaceAppObjectsResponse, error)
	DeleteAppObjects(ctx context.Context, in *DeleteAppObjectsRequest, opts ...grpc.CallOption) (*DeleteAppObjectsResponse, error)
	MoveAppObjects(ctx context.Context, in *MoveAppObjectsRequest, opts ...grpc.CallOption) (*MoveAppObjectsResponse, error)
	ListAppObjects(ctx context.Context, in *ListAppObjectsRequest, opts ...grpc.CallOption) (*ListAppObjectsResponse, error)
}

type appDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppDataServiceClient(cc grpc.ClientConnInterface) AppDataServiceClient {
	return &appDataServiceClient{cc}
}

func (c *appDataServiceClient) PutAppPicture(ctx context.Context, in *PutAppPictureRequest, opts ...grpc.CallOption) (*PutAppPictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutAppPictureResponse)
	err := c.cc.Invoke(ctx, AppDataService_PutAppPicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appDataServiceClient) PutAppObjects(ctx context.Context, in *PutAppObjectsRequest, opts ...grpc.CallOption) (*PutAppObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutAppObjectsResponse)
	err := c.cc.Invoke(ctx, AppDataService_PutAppObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appDataServiceClient) ReplaceAppObjects(ctx context.Context, in *ReplaceAppObjectsRequest, opts ...grpc.CallOption) (*ReplaceAppObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceAppObjectsResponse)
	err := c.cc.Invoke(ctx, AppDataService_ReplaceAppObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appDataServiceClient) DeleteAppObjects(ctx context.Context, in *DeleteAppObjectsRequest, opts ...grpc.CallOption) (*DeleteAppObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppObjectsResponse)
	err := c.cc.Invoke(ctx, AppDataService_DeleteAppObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appDataServiceClient) MoveAppObjects(ctx context.Context, in *MoveAppObjectsRequest, opts ...grpc.CallOption) (*MoveAppObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveAppObjectsResponse)
	err := c.cc.Invoke(ctx, AppDataService_MoveAppObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appDataServiceClient) ListAppObjects(ctx context.Context, in *ListAppObjectsRequest, opts ...grpc.CallOption) (*ListAppObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppObjectsResponse)
	err := c.cc.Invoke(ctx, AppDataService_ListAppObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppDataServiceServer is the server API for AppDataService service.
// All implementations should embed UnimplementedAppDataServiceServer
// for forward compatibility.
type AppDataServiceServer interface {
	PutAppPicture(context.Context, *PutAppPictureRequest) (*PutAppPictureResponse, error)
	PutAppObjects(context.Context, *PutAppObjectsRequest) (*PutAppObjectsResponse, error)
	ReplaceAppObjects(context.Context, *ReplaceAppObjectsRequest) (*ReplaceAppObjectsResponse, error)
	DeleteAppObjects(context.Context, *DeleteAppObjectsRequest) (*DeleteAppObjectsResponse, error)
	MoveAppObjects(context.Context, *MoveAppObjectsRequest) (*MoveAppObjectsResponse, error)
	ListAppObjects(context.Context, *ListAppObjectsRequest) (*ListAppObjectsResponse, error)
}

// UnimplementedAppDataServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppDataServiceServer struct{}

func (UnimplementedAppDataServiceServer) PutAppPicture(context.Context, *PutAppPictureRequest) (*PutAppPictureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutAppPicture not implemented")
}
func (UnimplementedAppDataServiceServer) PutAppObjects(context.Context, *PutAppObjectsRequest) (*PutAppObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutAppObjects not implemented")
}
func (UnimplementedAppDataServiceServer) ReplaceAppObjects(context.Context, *ReplaceAppObjectsRequest) (*ReplaceAppObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceAppObjects not implemented")
}
func (UnimplementedAppDataServiceServer) DeleteAppObjects(context.Context, *DeleteAppObjectsRequest) (*DeleteAppObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAppObjects not implemented")
}
func (UnimplementedAppDataServiceServer) MoveAppObjects(context.Context, *MoveAppObjectsRequest) (*MoveAppObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveAppObjects not implemented")
}
func (UnimplementedAppDataServiceServer) ListAppObjects(context.Context, *ListAppObjectsRequest) (*ListAppObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAppObjects not implemented")
}
func (UnimplementedAppDataServiceServer) testEmbeddedByValue() {}

// UnsafeAppDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppDataServiceServer will
// result in compilation errors.
type UnsafeAppDataServiceServer interface {
	mustEmbedUnimplementedAppDataServiceServer()
}

func RegisterAppDataServiceServer(s grpc.ServiceRegistrar, srv AppDataServiceServer) {
	// If the following call panics, it indicates UnimplementedAppDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppDataService_ServiceDesc, srv)
}

func _AppDataService_PutAppPicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAppPictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDataServiceServer).PutAppPicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppDataService_PutAppPicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDataServiceServer).PutAppPicture(ctx, req.(*PutAppPictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppDataService_PutAppObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAppObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDataServiceServer).PutAppObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppDataService_PutAppObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDataServiceServer).PutAppObjects(ctx, req.(*PutAppObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppDataService_ReplaceAppObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceAppObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDataServiceServer).ReplaceAppObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppDataService_ReplaceAppObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDataServiceServer).ReplaceAppObjects(ctx, req.(*ReplaceAppObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppDataService_DeleteAppObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDataServiceServer).DeleteAppObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppDataService_DeleteAppObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDataServiceServer).DeleteAppObjects(ctx, req.(*DeleteAppObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppDataService_MoveAppObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveAppObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDataServiceServer).MoveAppObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppDataService_MoveAppObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDataServiceServer).MoveAppObjects(ctx, req.(*MoveAppObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppDataService_ListAppObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppDataServiceServer).ListAppObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppDataService_ListAppObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppDataServiceServer).ListAppObjects(ctx, req.(*ListAppObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppDataService_ServiceDesc is the grpc.ServiceDesc for AppDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qwibi.v1.AppDataService",
	HandlerType: (*AppDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutAppPicture",
			Handler:    _AppDataService_PutAppPicture_Handler,
		},
		{
			MethodName: "PutAppObjects",
			Handler:    _AppDataService_PutAppObjects_Handler,
		},
		{
			MethodName: "ReplaceAppObjects",
			Handler:    _AppDataService_ReplaceAppObjects_Handler,
		},
		{
			MethodName: "DeleteAppObjects",
			Handler:    _AppDataService_DeleteAppObjects_Handler,
		},
		{
			MethodName: "MoveAppObjects",
			Handler:    _AppDataService_MoveAppObjects_Handler,
		},
		{
			MethodName: "ListAppObjects",
			Handler:    _AppDataService_ListAppObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qwibi/v1/app_data.proto",
}
