// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/auth_options.proto

package qwibiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthLevel declares what authentication an RPC requires. It is the single source
// of per-method auth policy: the api-server builds its auth registry from it, and
// the edge gateway reads the same value, so the two never carry separate per-method
// tables that can drift. An RPC with no annotation is AUTH_LEVEL_REQUIRED (deny by
// default).
type AuthLevel int32

const (
	// Unannotated: treated as required (deny by default).
	AuthLevel_AUTH_LEVEL_UNSPECIFIED AuthLevel = 0
	// No token needed (e.g. sign-in, token refresh).
	AuthLevel_AUTH_LEVEL_PUBLIC AuthLevel = 1
	// A valid token enriches the result, but an absent or invalid token is treated
	// as anonymous and never rejected (public reads).
	AuthLevel_AUTH_LEVEL_OPTIONAL AuthLevel = 2
	// A valid session is required.
	AuthLevel_AUTH_LEVEL_REQUIRED AuthLevel = 3
)

// Enum value maps for AuthLevel.
var (
	AuthLevel_name = map[int32]string{
		0: "AUTH_LEVEL_UNSPECIFIED",
		1: "AUTH_LEVEL_PUBLIC",
		2: "AUTH_LEVEL_OPTIONAL",
		3: "AUTH_LEVEL_REQUIRED",
	}
	AuthLevel_value = map[string]int32{
		"AUTH_LEVEL_UNSPECIFIED": 0,
		"AUTH_LEVEL_PUBLIC":      1,
		"AUTH_LEVEL_OPTIONAL":    2,
		"AUTH_LEVEL_REQUIRED":    3,
	}
)

func (x AuthLevel) Enum() *AuthLevel {
	p := new(AuthLevel)
	*p = x
	return p
}

func (x AuthLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_auth_options_proto_enumTypes[0].Descriptor()
}

func (AuthLevel) Type() protoreflect.EnumType {
	return &file_qwibi_v1_auth_options_proto_enumTypes[0]
}

func (x AuthLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthLevel.Descriptor instead.
func (AuthLevel) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_auth_options_proto_rawDescGZIP(), []int{0}
}

var file_qwibi_v1_auth_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthLevel)(nil),
		Field:         50001,
		Name:          "qwibi.v1.auth",
		Tag:           "varint,50001,opt,name=auth,enum=qwibi.v1.AuthLevel",
		Filename:      "qwibi/v1/auth_options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Per-RPC authentication policy. The api-server enforces it as authoritative; the
	// gateway reads it to decide what it can shed at the edge — a present-but-invalid
	// token on a required method — without breaking public or optional methods. The
	// field number is in the private-use extension range (50000-99999).
	//
	// optional qwibi.v1.AuthLevel auth = 50001;
	E_Auth = &file_qwibi_v1_auth_options_proto_extTypes[0]
)

var File_qwibi_v1_auth_options_proto protoreflect.FileDescriptor

const file_qwibi_v1_auth_options_proto_rawDesc = "" +
	"\n" +
	"\x1bqwibi/v1/auth_options.proto\x12\bqwibi.v1\x1a google/protobuf/descriptor.proto*p\n" +
	"\tAuthLevel\x12\x1a\n" +
	"\x16AUTH_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AUTH_LEVEL_PUBLIC\x10\x01\x12\x17\n" +
	"\x13AUTH_LEVEL_OPTIONAL\x10\x02\x12\x17\n" +
	"\x13AUTH_LEVEL_REQUIRED\x10\x03:L\n" +
	"\x04auth\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\x0e2\x13.qwibi.v1.AuthLevelR\x04auth\x88\x01\x01B\x93\x01\n" +
	"\fcom.qwibi.v1B\x10AuthOptionsProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_auth_options_proto_rawDescOnce sync.Once
	file_qwibi_v1_auth_options_proto_rawDescData []byte
)

func file_qwibi_v1_auth_options_proto_rawDescGZIP() []byte {
	file_qwibi_v1_auth_options_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_auth_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_auth_options_proto_rawDesc), len(file_qwibi_v1_auth_options_proto_rawDesc)))
	})
	return file_qwibi_v1_auth_options_proto_rawDescData
}

var file_qwibi_v1_auth_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qwibi_v1_auth_options_proto_goTypes = []any{
	(AuthLevel)(0),                     // 0: qwibi.v1.AuthLevel
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_qwibi_v1_auth_options_proto_depIdxs = []int32{
	1, // 0: qwibi.v1.auth:extendee -> google.protobuf.MethodOptions
	0, // 1: qwibi.v1.auth:type_name -> qwibi.v1.AuthLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qwibi_v1_auth_options_proto_init() }
func file_qwibi_v1_auth_options_proto_init() {
	if File_qwibi_v1_auth_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_auth_options_proto_rawDesc), len(file_qwibi_v1_auth_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_v1_auth_options_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_auth_options_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_auth_options_proto_enumTypes,
		ExtensionInfos:    file_qwibi_v1_auth_options_proto_extTypes,
	}.Build()
	File_qwibi_v1_auth_options_proto = out.File
	file_qwibi_v1_auth_options_proto_goTypes = nil
	file_qwibi_v1_auth_options_proto_depIdxs = nil
}
