// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/geometry.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeometryType enumerates the GeoJSON geometry kinds supported by the platform.
// It mirrors the "type" member of a GeoJSON geometry object and is used where a
// caller wants to constrain or report a geometry kind without inspecting the
// payload.
type GeometryType int32

const (
	GeometryType_GEOMETRY_TYPE_UNSPECIFIED         GeometryType = 0
	GeometryType_GEOMETRY_TYPE_POINT               GeometryType = 1
	GeometryType_GEOMETRY_TYPE_LINE_STRING         GeometryType = 2
	GeometryType_GEOMETRY_TYPE_POLYGON             GeometryType = 3
	GeometryType_GEOMETRY_TYPE_MULTI_POINT         GeometryType = 4
	GeometryType_GEOMETRY_TYPE_MULTI_LINE_STRING   GeometryType = 5
	GeometryType_GEOMETRY_TYPE_MULTI_POLYGON       GeometryType = 6
	GeometryType_GEOMETRY_TYPE_GEOMETRY_COLLECTION GeometryType = 7
)

// Enum value maps for GeometryType.
var (
	GeometryType_name = map[int32]string{
		0: "GEOMETRY_TYPE_UNSPECIFIED",
		1: "GEOMETRY_TYPE_POINT",
		2: "GEOMETRY_TYPE_LINE_STRING",
		3: "GEOMETRY_TYPE_POLYGON",
		4: "GEOMETRY_TYPE_MULTI_POINT",
		5: "GEOMETRY_TYPE_MULTI_LINE_STRING",
		6: "GEOMETRY_TYPE_MULTI_POLYGON",
		7: "GEOMETRY_TYPE_GEOMETRY_COLLECTION",
	}
	GeometryType_value = map[string]int32{
		"GEOMETRY_TYPE_UNSPECIFIED":         0,
		"GEOMETRY_TYPE_POINT":               1,
		"GEOMETRY_TYPE_LINE_STRING":         2,
		"GEOMETRY_TYPE_POLYGON":             3,
		"GEOMETRY_TYPE_MULTI_POINT":         4,
		"GEOMETRY_TYPE_MULTI_LINE_STRING":   5,
		"GEOMETRY_TYPE_MULTI_POLYGON":       6,
		"GEOMETRY_TYPE_GEOMETRY_COLLECTION": 7,
	}
)

func (x GeometryType) Enum() *GeometryType {
	p := new(GeometryType)
	*p = x
	return p
}

func (x GeometryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeometryType) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_geometry_proto_enumTypes[0].Descriptor()
}

func (GeometryType) Type() protoreflect.EnumType {
	return &file_qwibi_v1_geometry_proto_enumTypes[0]
}

func (x GeometryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeometryType.Descriptor instead.
func (GeometryType) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{0}
}

// Position is the single, type-safe coordinate primitive used everywhere in the
// contract. It corresponds to a GeoJSON position: longitude and latitude in
// EPSG:4326 decimal degrees, with an optional elevation in meters. Modelling
// longitude/latitude as named fields (rather than an order-dependent
// `repeated double`) removes the axis-ordering ambiguity that plagues GeoJSON
// integrations and lets the server validate ranges per axis.
type Position struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Longitude in decimal degrees, EPSG:4326. Range [-180, 180]. Explicit
	// presence: an unset lon is distinguishable from 0, so a half-built Position
	// can no longer silently read as Null Island — wherever a position is
	// required, the server rejects a missing lon/lat as INVALID_ARGUMENT.
	Lon *float64 `protobuf:"fixed64,1,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	// Latitude in decimal degrees, EPSG:4326. Range [-90, 90]. Explicit presence,
	// same contract as lon.
	Lat *float64 `protobuf:"fixed64,2,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	// Optional Z ordinate: height in meters above the WGS84 ellipsoid. Named `z`
	// (rather than elevation/altitude) to match the geometry's Z dimension and stay
	// reference-neutral.
	Z *float64 `protobuf:"fixed64,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
	// Optional M ordinate: a per-vertex "measure" — an app-defined scalar attached
	// to each position (e.g. timestamp, speed, or linear-reference distance along a
	// line). The platform stores and returns it verbatim; its meaning is the app's.
	M             *float64 `protobuf:"fixed64,4,opt,name=m,proto3,oneof" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *Position) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Position) GetZ() float64 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *Position) GetM() float64 {
	if x != nil && x.M != nil {
		return *x.M
	}
	return 0
}

// Point is a GeoJSON Point: a single position.
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   *Position              `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetCoordinates() *Position {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// LineString is a GeoJSON LineString: an ordered list of two or more positions.
type LineString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Position            `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineString) Reset() {
	*x = LineString{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineString) ProtoMessage() {}

func (x *LineString) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineString.ProtoReflect.Descriptor instead.
func (*LineString) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{2}
}

func (x *LineString) GetCoordinates() []*Position {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// LinearRing is a closed LineString used as a Polygon boundary. Per GeoJSON a
// ring has at least four positions and the first and last positions are
// identical; the equality of endpoints is enforced server-side.
type LinearRing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Position            `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinearRing) Reset() {
	*x = LinearRing{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinearRing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearRing) ProtoMessage() {}

func (x *LinearRing) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearRing.ProtoReflect.Descriptor instead.
func (*LinearRing) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{3}
}

func (x *LinearRing) GetCoordinates() []*Position {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// Polygon is a GeoJSON Polygon: an array of LinearRings. The first ring is the
// exterior boundary; any subsequent rings are interior boundaries (holes).
type Polygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rings         []*LinearRing          `protobuf:"bytes,1,rep,name=rings,proto3" json:"rings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Polygon) Reset() {
	*x = Polygon{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polygon) ProtoMessage() {}

func (x *Polygon) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polygon.ProtoReflect.Descriptor instead.
func (*Polygon) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{4}
}

func (x *Polygon) GetRings() []*LinearRing {
	if x != nil {
		return x.Rings
	}
	return nil
}

// MultiPoint is a GeoJSON MultiPoint: an array of positions.
type MultiPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Position            `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPoint) Reset() {
	*x = MultiPoint{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPoint) ProtoMessage() {}

func (x *MultiPoint) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPoint.ProtoReflect.Descriptor instead.
func (*MultiPoint) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{5}
}

func (x *MultiPoint) GetCoordinates() []*Position {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// MultiLineString is a GeoJSON MultiLineString: an array of LineStrings.
type MultiLineString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineStrings   []*LineString          `protobuf:"bytes,1,rep,name=line_strings,json=lineStrings,proto3" json:"line_strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiLineString) Reset() {
	*x = MultiLineString{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiLineString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiLineString) ProtoMessage() {}

func (x *MultiLineString) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiLineString.ProtoReflect.Descriptor instead.
func (*MultiLineString) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{6}
}

func (x *MultiLineString) GetLineStrings() []*LineString {
	if x != nil {
		return x.LineStrings
	}
	return nil
}

// MultiPolygon is a GeoJSON MultiPolygon: an array of Polygons.
type MultiPolygon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polygons      []*Polygon             `protobuf:"bytes,1,rep,name=polygons,proto3" json:"polygons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPolygon) Reset() {
	*x = MultiPolygon{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPolygon) ProtoMessage() {}

func (x *MultiPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPolygon.ProtoReflect.Descriptor instead.
func (*MultiPolygon) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{7}
}

func (x *MultiPolygon) GetPolygons() []*Polygon {
	if x != nil {
		return x.Polygons
	}
	return nil
}

// GeometryCollection is a GeoJSON GeometryCollection: a heterogeneous array of
// geometries. It must not contain another GeometryCollection (enforced
// server-side to keep the value mappable to a single PostGIS geometry column).
type GeometryCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geometries    []*Geometry            `protobuf:"bytes,1,rep,name=geometries,proto3" json:"geometries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeometryCollection) Reset() {
	*x = GeometryCollection{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeometryCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeometryCollection) ProtoMessage() {}

func (x *GeometryCollection) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeometryCollection.ProtoReflect.Descriptor instead.
func (*GeometryCollection) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{8}
}

func (x *GeometryCollection) GetGeometries() []*Geometry {
	if x != nil {
		return x.Geometries
	}
	return nil
}

// Geometry is the one canonical envelope for any GeoJSON geometry value. Exactly
// one variant is set. This is the type written to and read back from the PostGIS
// `geometry(Geometry,4326)` column via the Go GoType wrapper, so the variant set
// here is the geometry kind persisted and returned on read.
type Geometry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Geometry:
	//
	//	*Geometry_Point
	//	*Geometry_LineString
	//	*Geometry_Polygon
	//	*Geometry_MultiPoint
	//	*Geometry_MultiLineString
	//	*Geometry_MultiPolygon
	//	*Geometry_GeometryCollection
	Geometry      isGeometry_Geometry `protobuf_oneof:"geometry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{9}
}

func (x *Geometry) GetGeometry() isGeometry_Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *Geometry) GetPoint() *Point {
	if x != nil {
		if x, ok := x.Geometry.(*Geometry_Point); ok {
			return x.Point
		}
	}
	return nil
}

func (x *Geometry) GetLineString() *LineString {
	if x != nil {
		if x, ok := x.Geometry.(*Geometry_LineString); ok {
			return x.LineString
		}
	}
	return nil
}

func (x *Geometry) GetPolygon() *Polygon {
	if x != nil {
		if x, ok := x.Geometry.(*Geometry_Polygon); ok {
			return x.Polygon
		}
	}
	return nil
}

func (x *Geometry) GetMultiPoint() *MultiPoint {
	if x != nil {
		if x, ok := x.Geometry.(*Geometry_MultiPoint); ok {
			return x.MultiPoint
		}
	}
	return nil
}

func (x *Geometry) GetMultiLineString() *MultiLineString {
	if x != nil {
		if x, ok := x.Geometry.(*Geometry_MultiLineString); ok {
			return x.MultiLineString
		}
	}
	return nil
}

func (x *Geometry) GetMultiPolygon() *MultiPolygon {
	if x != nil {
		if x, ok := x.Geometry.(*Geometry_MultiPolygon); ok {
			return x.MultiPolygon
		}
	}
	return nil
}

func (x *Geometry) GetGeometryCollection() *GeometryCollection {
	if x != nil {
		if x, ok := x.Geometry.(*Geometry_GeometryCollection); ok {
			return x.GeometryCollection
		}
	}
	return nil
}

type isGeometry_Geometry interface {
	isGeometry_Geometry()
}

type Geometry_Point struct {
	Point *Point `protobuf:"bytes,1,opt,name=point,proto3,oneof"`
}

type Geometry_LineString struct {
	LineString *LineString `protobuf:"bytes,2,opt,name=line_string,json=lineString,proto3,oneof"`
}

type Geometry_Polygon struct {
	Polygon *Polygon `protobuf:"bytes,3,opt,name=polygon,proto3,oneof"`
}

type Geometry_MultiPoint struct {
	MultiPoint *MultiPoint `protobuf:"bytes,4,opt,name=multi_point,json=multiPoint,proto3,oneof"`
}

type Geometry_MultiLineString struct {
	MultiLineString *MultiLineString `protobuf:"bytes,5,opt,name=multi_line_string,json=multiLineString,proto3,oneof"`
}

type Geometry_MultiPolygon struct {
	MultiPolygon *MultiPolygon `protobuf:"bytes,6,opt,name=multi_polygon,json=multiPolygon,proto3,oneof"`
}

type Geometry_GeometryCollection struct {
	// Rendered in v0: every heterogeneous member is preserved and routed by
	// its declared geometry kind through the corresponding paint layer.
	GeometryCollection *GeometryCollection `protobuf:"bytes,7,opt,name=geometry_collection,json=geometryCollection,proto3,oneof"`
}

func (*Geometry_Point) isGeometry_Geometry() {}

func (*Geometry_LineString) isGeometry_Geometry() {}

func (*Geometry_Polygon) isGeometry_Geometry() {}

func (*Geometry_MultiPoint) isGeometry_Geometry() {}

func (*Geometry_MultiLineString) isGeometry_Geometry() {}

func (*Geometry_MultiPolygon) isGeometry_Geometry() {}

func (*Geometry_GeometryCollection) isGeometry_Geometry() {}

// BoundingBox is an axis-aligned rectangle in EPSG:4326, used for spatial
// queries and viewport descriptions. Stored as the two corner positions; the
// optional elevation members of the corners carry the 3D extent when present.
//
// A box may cross the antimeridian on the wire, in which case min_lon >
// max_lon; consumers must handle that case explicitly rather than assuming
// min_lon <= max_lon. v1 servers, however, do not yet serve
// antimeridian-crossing queries or viewports: they reject such boxes loudly
// as INVALID_ARGUMENT — split a crossing box into two non-crossing boxes
// client-side.
type BoundingBox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// South-west corner (minimum longitude/latitude under the non-wrapping case).
	SouthWest *Position `protobuf:"bytes,1,opt,name=south_west,json=southWest,proto3" json:"south_west,omitempty"`
	// North-east corner (maximum longitude/latitude under the non-wrapping case).
	NorthEast     *Position `protobuf:"bytes,2,opt,name=north_east,json=northEast,proto3" json:"north_east,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_qwibi_v1_geometry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_geometry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_geometry_proto_rawDescGZIP(), []int{10}
}

func (x *BoundingBox) GetSouthWest() *Position {
	if x != nil {
		return x.SouthWest
	}
	return nil
}

func (x *BoundingBox) GetNorthEast() *Position {
	if x != nil {
		return x.NorthEast
	}
	return nil
}

var File_qwibi_v1_geometry_proto protoreflect.FileDescriptor

const file_qwibi_v1_geometry_proto_rawDesc = "" +
	"\n" +
	"\x17qwibi/v1/geometry.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\"\xac\x01\n" +
	"\bPosition\x12.\n" +
	"\x03lon\x18\x01 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80f@)\x00\x00\x00\x00\x00\x80f\xc0H\x00R\x03lon\x88\x01\x01\x12.\n" +
	"\x03lat\x18\x02 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x80V@)\x00\x00\x00\x00\x00\x80V\xc0H\x01R\x03lat\x88\x01\x01\x12\x11\n" +
	"\x01z\x18\x03 \x01(\x01H\x02R\x01z\x88\x01\x01\x12\x11\n" +
	"\x01m\x18\x04 \x01(\x01H\x03R\x01m\x88\x01\x01B\x06\n" +
	"\x04_lonB\x06\n" +
	"\x04_latB\x04\n" +
	"\x02_zB\x04\n" +
	"\x02_m\"E\n" +
	"\x05Point\x12<\n" +
	"\vcoordinates\x18\x01 \x01(\v2\x12.qwibi.v1.PositionB\x06\xbaH\x03\xc8\x01\x01R\vcoordinates\"L\n" +
	"\n" +
	"LineString\x12>\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x12.qwibi.v1.PositionB\b\xbaH\x05\x92\x01\x02\b\x02R\vcoordinates\"L\n" +
	"\n" +
	"LinearRing\x12>\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x12.qwibi.v1.PositionB\b\xbaH\x05\x92\x01\x02\b\x04R\vcoordinates\"?\n" +
	"\aPolygon\x124\n" +
	"\x05rings\x18\x01 \x03(\v2\x14.qwibi.v1.LinearRingB\b\xbaH\x05\x92\x01\x02\b\x01R\x05rings\"B\n" +
	"\n" +
	"MultiPoint\x124\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x12.qwibi.v1.PositionR\vcoordinates\"J\n" +
	"\x0fMultiLineString\x127\n" +
	"\fline_strings\x18\x01 \x03(\v2\x14.qwibi.v1.LineStringR\vlineStrings\"=\n" +
	"\fMultiPolygon\x12-\n" +
	"\bpolygons\x18\x01 \x03(\v2\x11.qwibi.v1.PolygonR\bpolygons\"R\n" +
	"\x12GeometryCollection\x12<\n" +
	"\n" +
	"geometries\x18\x01 \x03(\v2\x12.qwibi.v1.GeometryB\b\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"geometries\"\xc0\x03\n" +
	"\bGeometry\x12'\n" +
	"\x05point\x18\x01 \x01(\v2\x0f.qwibi.v1.PointH\x00R\x05point\x127\n" +
	"\vline_string\x18\x02 \x01(\v2\x14.qwibi.v1.LineStringH\x00R\n" +
	"lineString\x12-\n" +
	"\apolygon\x18\x03 \x01(\v2\x11.qwibi.v1.PolygonH\x00R\apolygon\x127\n" +
	"\vmulti_point\x18\x04 \x01(\v2\x14.qwibi.v1.MultiPointH\x00R\n" +
	"multiPoint\x12G\n" +
	"\x11multi_line_string\x18\x05 \x01(\v2\x19.qwibi.v1.MultiLineStringH\x00R\x0fmultiLineString\x12=\n" +
	"\rmulti_polygon\x18\x06 \x01(\v2\x16.qwibi.v1.MultiPolygonH\x00R\fmultiPolygon\x12O\n" +
	"\x13geometry_collection\x18\a \x01(\v2\x1c.qwibi.v1.GeometryCollectionH\x00R\x12geometryCollectionB\x11\n" +
	"\bgeometry\x12\x05\xbaH\x02\b\x01\"\x83\x01\n" +
	"\vBoundingBox\x129\n" +
	"\n" +
	"south_west\x18\x01 \x01(\v2\x12.qwibi.v1.PositionB\x06\xbaH\x03\xc8\x01\x01R\tsouthWest\x129\n" +
	"\n" +
	"north_east\x18\x02 \x01(\v2\x12.qwibi.v1.PositionB\x06\xbaH\x03\xc8\x01\x01R\tnorthEast*\x8c\x02\n" +
	"\fGeometryType\x12\x1d\n" +
	"\x19GEOMETRY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GEOMETRY_TYPE_POINT\x10\x01\x12\x1d\n" +
	"\x19GEOMETRY_TYPE_LINE_STRING\x10\x02\x12\x19\n" +
	"\x15GEOMETRY_TYPE_POLYGON\x10\x03\x12\x1d\n" +
	"\x19GEOMETRY_TYPE_MULTI_POINT\x10\x04\x12#\n" +
	"\x1fGEOMETRY_TYPE_MULTI_LINE_STRING\x10\x05\x12\x1f\n" +
	"\x1bGEOMETRY_TYPE_MULTI_POLYGON\x10\x06\x12%\n" +
	"!GEOMETRY_TYPE_GEOMETRY_COLLECTION\x10\aB\x90\x01\n" +
	"\fcom.qwibi.v1B\rGeometryProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_geometry_proto_rawDescOnce sync.Once
	file_qwibi_v1_geometry_proto_rawDescData []byte
)

func file_qwibi_v1_geometry_proto_rawDescGZIP() []byte {
	file_qwibi_v1_geometry_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_geometry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_geometry_proto_rawDesc), len(file_qwibi_v1_geometry_proto_rawDesc)))
	})
	return file_qwibi_v1_geometry_proto_rawDescData
}

var file_qwibi_v1_geometry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qwibi_v1_geometry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_qwibi_v1_geometry_proto_goTypes = []any{
	(GeometryType)(0),          // 0: qwibi.v1.GeometryType
	(*Position)(nil),           // 1: qwibi.v1.Position
	(*Point)(nil),              // 2: qwibi.v1.Point
	(*LineString)(nil),         // 3: qwibi.v1.LineString
	(*LinearRing)(nil),         // 4: qwibi.v1.LinearRing
	(*Polygon)(nil),            // 5: qwibi.v1.Polygon
	(*MultiPoint)(nil),         // 6: qwibi.v1.MultiPoint
	(*MultiLineString)(nil),    // 7: qwibi.v1.MultiLineString
	(*MultiPolygon)(nil),       // 8: qwibi.v1.MultiPolygon
	(*GeometryCollection)(nil), // 9: qwibi.v1.GeometryCollection
	(*Geometry)(nil),           // 10: qwibi.v1.Geometry
	(*BoundingBox)(nil),        // 11: qwibi.v1.BoundingBox
}
var file_qwibi_v1_geometry_proto_depIdxs = []int32{
	1,  // 0: qwibi.v1.Point.coordinates:type_name -> qwibi.v1.Position
	1,  // 1: qwibi.v1.LineString.coordinates:type_name -> qwibi.v1.Position
	1,  // 2: qwibi.v1.LinearRing.coordinates:type_name -> qwibi.v1.Position
	4,  // 3: qwibi.v1.Polygon.rings:type_name -> qwibi.v1.LinearRing
	1,  // 4: qwibi.v1.MultiPoint.coordinates:type_name -> qwibi.v1.Position
	3,  // 5: qwibi.v1.MultiLineString.line_strings:type_name -> qwibi.v1.LineString
	5,  // 6: qwibi.v1.MultiPolygon.polygons:type_name -> qwibi.v1.Polygon
	10, // 7: qwibi.v1.GeometryCollection.geometries:type_name -> qwibi.v1.Geometry
	2,  // 8: qwibi.v1.Geometry.point:type_name -> qwibi.v1.Point
	3,  // 9: qwibi.v1.Geometry.line_string:type_name -> qwibi.v1.LineString
	5,  // 10: qwibi.v1.Geometry.polygon:type_name -> qwibi.v1.Polygon
	6,  // 11: qwibi.v1.Geometry.multi_point:type_name -> qwibi.v1.MultiPoint
	7,  // 12: qwibi.v1.Geometry.multi_line_string:type_name -> qwibi.v1.MultiLineString
	8,  // 13: qwibi.v1.Geometry.multi_polygon:type_name -> qwibi.v1.MultiPolygon
	9,  // 14: qwibi.v1.Geometry.geometry_collection:type_name -> qwibi.v1.GeometryCollection
	1,  // 15: qwibi.v1.BoundingBox.south_west:type_name -> qwibi.v1.Position
	1,  // 16: qwibi.v1.BoundingBox.north_east:type_name -> qwibi.v1.Position
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_qwibi_v1_geometry_proto_init() }
func file_qwibi_v1_geometry_proto_init() {
	if File_qwibi_v1_geometry_proto != nil {
		return
	}
	file_qwibi_v1_geometry_proto_msgTypes[0].OneofWrappers = []any{}
	file_qwibi_v1_geometry_proto_msgTypes[9].OneofWrappers = []any{
		(*Geometry_Point)(nil),
		(*Geometry_LineString)(nil),
		(*Geometry_Polygon)(nil),
		(*Geometry_MultiPoint)(nil),
		(*Geometry_MultiLineString)(nil),
		(*Geometry_MultiPolygon)(nil),
		(*Geometry_GeometryCollection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_geometry_proto_rawDesc), len(file_qwibi_v1_geometry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_v1_geometry_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_geometry_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_geometry_proto_enumTypes,
		MessageInfos:      file_qwibi_v1_geometry_proto_msgTypes,
	}.Build()
	File_qwibi_v1_geometry_proto = out.File
	file_qwibi_v1_geometry_proto_goTypes = nil
	file_qwibi_v1_geometry_proto_depIdxs = nil
}
