// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/mark.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mark is one person's private mark on one App data object. Marks belong to
// the account and the App, appear on every map where that App appears and are
// erased with the account. Only the owning account ever reads or writes them.
type Mark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	MarkId        string                 `protobuf:"bytes,2,opt,name=mark_id,json=markId,proto3" json:"mark_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MarkedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=marked_at,json=markedAt,proto3" json:"marked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mark) Reset() {
	*x = Mark{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mark) ProtoMessage() {}

func (x *Mark) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mark.ProtoReflect.Descriptor instead.
func (*Mark) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{0}
}

func (x *Mark) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Mark) GetMarkId() string {
	if x != nil {
		return x.MarkId
	}
	return ""
}

func (x *Mark) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Mark) GetMarkedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MarkedAt
	}
	return nil
}

// DeviceMark is a mark a person without a confirmed email kept on the device.
type DeviceMark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarkId        string                 `protobuf:"bytes,1,opt,name=mark_id,json=markId,proto3" json:"mark_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceMark) Reset() {
	*x = DeviceMark{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMark) ProtoMessage() {}

func (x *DeviceMark) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMark.ProtoReflect.Descriptor instead.
func (*DeviceMark) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceMark) GetMarkId() string {
	if x != nil {
		return x.MarkId
	}
	return ""
}

func (x *DeviceMark) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type SetMarkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	AppId string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// The Layer on screen. It is never stored with the mark.
	LayerId       string `protobuf:"bytes,2,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	MarkId        string `protobuf:"bytes,3,opt,name=mark_id,json=markId,proto3" json:"mark_id,omitempty"`
	ObjectId      string `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	On            bool   `protobuf:"varint,5,opt,name=on,proto3" json:"on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMarkRequest) Reset() {
	*x = SetMarkRequest{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMarkRequest) ProtoMessage() {}

func (x *SetMarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMarkRequest.ProtoReflect.Descriptor instead.
func (*SetMarkRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{2}
}

func (x *SetMarkRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SetMarkRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *SetMarkRequest) GetMarkId() string {
	if x != nil {
		return x.MarkId
	}
	return ""
}

func (x *SetMarkRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *SetMarkRequest) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

type SetMarkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of objects the person has marked with this mark after the call.
	Count         uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMarkResponse) Reset() {
	*x = SetMarkResponse{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMarkResponse) ProtoMessage() {}

func (x *SetMarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMarkResponse.ProtoReflect.Descriptor instead.
func (*SetMarkResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{3}
}

func (x *SetMarkResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListMyMarksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyMarksRequest) Reset() {
	*x = ListMyMarksRequest{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyMarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyMarksRequest) ProtoMessage() {}

func (x *ListMyMarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyMarksRequest.ProtoReflect.Descriptor instead.
func (*ListMyMarksRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyMarksRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ListMyMarksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Marks         []*Mark                `protobuf:"bytes,1,rep,name=marks,proto3" json:"marks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyMarksResponse) Reset() {
	*x = ListMyMarksResponse{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyMarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyMarksResponse) ProtoMessage() {}

func (x *ListMyMarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyMarksResponse.ProtoReflect.Descriptor instead.
func (*ListMyMarksResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyMarksResponse) GetMarks() []*Mark {
	if x != nil {
		return x.Marks
	}
	return nil
}

type ImportMyMarksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Marks         []*DeviceMark          `protobuf:"bytes,2,rep,name=marks,proto3" json:"marks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportMyMarksRequest) Reset() {
	*x = ImportMyMarksRequest{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportMyMarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportMyMarksRequest) ProtoMessage() {}

func (x *ImportMyMarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportMyMarksRequest.ProtoReflect.Descriptor instead.
func (*ImportMyMarksRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{6}
}

func (x *ImportMyMarksRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ImportMyMarksRequest) GetMarks() []*DeviceMark {
	if x != nil {
		return x.Marks
	}
	return nil
}

type ImportMyMarksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device marks now stored in the account, including ones it already had.
	Imported uint32 `protobuf:"varint,1,opt,name=imported,proto3" json:"imported,omitempty"`
	// Device marks refused: undeclared mark, unreadable object, or over the quota.
	Skipped       uint32 `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportMyMarksResponse) Reset() {
	*x = ImportMyMarksResponse{}
	mi := &file_qwibi_v1_mark_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportMyMarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportMyMarksResponse) ProtoMessage() {}

func (x *ImportMyMarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_mark_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportMyMarksResponse.ProtoReflect.Descriptor instead.
func (*ImportMyMarksResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_mark_proto_rawDescGZIP(), []int{7}
}

func (x *ImportMyMarksResponse) GetImported() uint32 {
	if x != nil {
		return x.Imported
	}
	return 0
}

func (x *ImportMyMarksResponse) GetSkipped() uint32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

var File_qwibi_v1_mark_proto protoreflect.FileDescriptor

const file_qwibi_v1_mark_proto_rawDesc = "" +
	"\n" +
	"\x13qwibi/v1/mark.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x01\n" +
	"\x04Mark\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\amark_id\x18\x02 \x01(\tR\x06markId\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x127\n" +
	"\tmarked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bmarkedAt\"\xb0\x01\n" +
	"\n" +
	"DeviceMark\x12;\n" +
	"\amark_id\x18\x01 \x01(\tB\"\xbaH\x1fr\x1d\x10\x01\x18@2\x17^[a-z][a-z0-9_-]{0,63}$R\x06markId\x12e\n" +
	"\tobject_id\x18\x02 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\bobjectId\"\x8c\x03\n" +
	"\x0eSetMarkRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12e\n" +
	"\blayer_id\x18\x02 \x01(\tBJ\xbaHGrE\x18$2A^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\alayerId\x12;\n" +
	"\amark_id\x18\x03 \x01(\tB\"\xbaH\x1fr\x1d\x10\x01\x18@2\x17^[a-z][a-z0-9_-]{0,63}$R\x06markId\x12e\n" +
	"\tobject_id\x18\x04 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\bobjectId\x12\x0e\n" +
	"\x02on\x18\x05 \x01(\bR\x02on\"'\n" +
	"\x0fSetMarkResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"u\n" +
	"\x12ListMyMarksRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\";\n" +
	"\x13ListMyMarksResponse\x12$\n" +
	"\x05marks\x18\x01 \x03(\v2\x0e.qwibi.v1.MarkR\x05marks\"\xb0\x01\n" +
	"\x14ImportMyMarksRequest\x12_\n" +
	"\x06app_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x127\n" +
	"\x05marks\x18\x02 \x03(\v2\x14.qwibi.v1.DeviceMarkB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x05marks\"M\n" +
	"\x15ImportMyMarksResponse\x12\x1a\n" +
	"\bimported\x18\x01 \x01(\rR\bimported\x12\x18\n" +
	"\askipped\x18\x02 \x01(\rR\askipped2\xeb\x01\n" +
	"\vMarkService\x12>\n" +
	"\aSetMark\x12\x18.qwibi.v1.SetMarkRequest\x1a\x19.qwibi.v1.SetMarkResponse\x12J\n" +
	"\vListMyMarks\x12\x1c.qwibi.v1.ListMyMarksRequest\x1a\x1d.qwibi.v1.ListMyMarksResponse\x12P\n" +
	"\rImportMyMarks\x12\x1e.qwibi.v1.ImportMyMarksRequest\x1a\x1f.qwibi.v1.ImportMyMarksResponseB\x8c\x01\n" +
	"\fcom.qwibi.v1B\tMarkProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_mark_proto_rawDescOnce sync.Once
	file_qwibi_v1_mark_proto_rawDescData []byte
)

func file_qwibi_v1_mark_proto_rawDescGZIP() []byte {
	file_qwibi_v1_mark_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_mark_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_mark_proto_rawDesc), len(file_qwibi_v1_mark_proto_rawDesc)))
	})
	return file_qwibi_v1_mark_proto_rawDescData
}

var file_qwibi_v1_mark_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_qwibi_v1_mark_proto_goTypes = []any{
	(*Mark)(nil),                  // 0: qwibi.v1.Mark
	(*DeviceMark)(nil),            // 1: qwibi.v1.DeviceMark
	(*SetMarkRequest)(nil),        // 2: qwibi.v1.SetMarkRequest
	(*SetMarkResponse)(nil),       // 3: qwibi.v1.SetMarkResponse
	(*ListMyMarksRequest)(nil),    // 4: qwibi.v1.ListMyMarksRequest
	(*ListMyMarksResponse)(nil),   // 5: qwibi.v1.ListMyMarksResponse
	(*ImportMyMarksRequest)(nil),  // 6: qwibi.v1.ImportMyMarksRequest
	(*ImportMyMarksResponse)(nil), // 7: qwibi.v1.ImportMyMarksResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_qwibi_v1_mark_proto_depIdxs = []int32{
	8, // 0: qwibi.v1.Mark.marked_at:type_name -> google.protobuf.Timestamp
	0, // 1: qwibi.v1.ListMyMarksResponse.marks:type_name -> qwibi.v1.Mark
	1, // 2: qwibi.v1.ImportMyMarksRequest.marks:type_name -> qwibi.v1.DeviceMark
	2, // 3: qwibi.v1.MarkService.SetMark:input_type -> qwibi.v1.SetMarkRequest
	4, // 4: qwibi.v1.MarkService.ListMyMarks:input_type -> qwibi.v1.ListMyMarksRequest
	6, // 5: qwibi.v1.MarkService.ImportMyMarks:input_type -> qwibi.v1.ImportMyMarksRequest
	3, // 6: qwibi.v1.MarkService.SetMark:output_type -> qwibi.v1.SetMarkResponse
	5, // 7: qwibi.v1.MarkService.ListMyMarks:output_type -> qwibi.v1.ListMyMarksResponse
	7, // 8: qwibi.v1.MarkService.ImportMyMarks:output_type -> qwibi.v1.ImportMyMarksResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_qwibi_v1_mark_proto_init() }
func file_qwibi_v1_mark_proto_init() {
	if File_qwibi_v1_mark_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_mark_proto_rawDesc), len(file_qwibi_v1_mark_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qwibi_v1_mark_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_mark_proto_depIdxs,
		MessageInfos:      file_qwibi_v1_mark_proto_msgTypes,
	}.Build()
	File_qwibi_v1_mark_proto = out.File
	file_qwibi_v1_mark_proto_goTypes = nil
	file_qwibi_v1_mark_proto_depIdxs = nil
}
