// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: qwibi/v1/mark.proto

package qwibiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarkService_SetMark_FullMethodName       = "/qwibi.v1.MarkService/SetMark"
	MarkService_ListMyMarks_FullMethodName   = "/qwibi.v1.MarkService/ListMyMarks"
	MarkService_ImportMyMarks_FullMethodName = "/qwibi.v1.MarkService/ImportMyMarks"
)

// MarkServiceClient is the client API for MarkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarkService is for the authenticated person only; an App token is refused.
// Every call requires a confirmed email.
type MarkServiceClient interface {
	SetMark(ctx context.Context, in *SetMarkRequest, opts ...grpc.CallOption) (*SetMarkResponse, error)
	ListMyMarks(ctx context.Context, in *ListMyMarksRequest, opts ...grpc.CallOption) (*ListMyMarksResponse, error)
	// Moves device marks into the account once an email is confirmed. It opens
	// no session and emits no event.
	ImportMyMarks(ctx context.Context, in *ImportMyMarksRequest, opts ...grpc.CallOption) (*ImportMyMarksResponse, error)
}

type markServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarkServiceClient(cc grpc.ClientConnInterface) MarkServiceClient {
	return &markServiceClient{cc}
}

func (c *markServiceClient) SetMark(ctx context.Context, in *SetMarkRequest, opts ...grpc.CallOption) (*SetMarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMarkResponse)
	err := c.cc.Invoke(ctx, MarkService_SetMark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markServiceClient) ListMyMarks(ctx context.Context, in *ListMyMarksRequest, opts ...grpc.CallOption) (*ListMyMarksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyMarksResponse)
	err := c.cc.Invoke(ctx, MarkService_ListMyMarks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *markServiceClient) ImportMyMarks(ctx context.Context, in *ImportMyMarksRequest, opts ...grpc.CallOption) (*ImportMyMarksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportMyMarksResponse)
	err := c.cc.Invoke(ctx, MarkService_ImportMyMarks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarkServiceServer is the server API for MarkService service.
// All implementations should embed UnimplementedMarkServiceServer
// for forward compatibility.
//
// MarkService is for the authenticated person only; an App token is refused.
// Every call requires a confirmed email.
type MarkServiceServer interface {
	SetMark(context.Context, *SetMarkRequest) (*SetMarkResponse, error)
	ListMyMarks(context.Context, *ListMyMarksRequest) (*ListMyMarksResponse, error)
	// Moves device marks into the account once an email is confirmed. It opens
	// no session and emits no event.
	ImportMyMarks(context.Context, *ImportMyMarksRequest) (*ImportMyMarksResponse, error)
}

// UnimplementedMarkServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarkServiceServer struct{}

func (UnimplementedMarkServiceServer) SetMark(context.Context, *SetMarkRequest) (*SetMarkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMark not implemented")
}
func (UnimplementedMarkServiceServer) ListMyMarks(context.Context, *ListMyMarksRequest) (*ListMyMarksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyMarks not implemented")
}
func (UnimplementedMarkServiceServer) ImportMyMarks(context.Context, *ImportMyMarksRequest) (*ImportMyMarksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportMyMarks not implemented")
}
func (UnimplementedMarkServiceServer) testEmbeddedByValue() {}

// UnsafeMarkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarkServiceServer will
// result in compilation errors.
type UnsafeMarkServiceServer interface {
	mustEmbedUnimplementedMarkServiceServer()
}

func RegisterMarkServiceServer(s grpc.ServiceRegistrar, srv MarkServiceServer) {
	// If the following call panics, it indicates UnimplementedMarkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarkService_ServiceDesc, srv)
}

func _MarkService_SetMark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkServiceServer).SetMark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkService_SetMark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkServiceServer).SetMark(ctx, req.(*SetMarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkService_ListMyMarks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyMarksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkServiceServer).ListMyMarks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkService_ListMyMarks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkServiceServer).ListMyMarks(ctx, req.(*ListMyMarksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarkService_ImportMyMarks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportMyMarksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarkServiceServer).ImportMyMarks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarkService_ImportMyMarks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarkServiceServer).ImportMyMarks(ctx, req.(*ImportMyMarksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarkService_ServiceDesc is the grpc.ServiceDesc for MarkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qwibi.v1.MarkService",
	HandlerType: (*MarkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMark",
			Handler:    _MarkService_SetMark_Handler,
		},
		{
			MethodName: "ListMyMarks",
			Handler:    _MarkService_ListMyMarks_Handler,
		},
		{
			MethodName: "ImportMyMarks",
			Handler:    _MarkService_ImportMyMarks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qwibi/v1/mark.proto",
}
