// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/object.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObjectAudience scopes one object inside an otherwise readable layer. Durable
// private channels remain private layers; this field is for small, ephemeral
// recipient sets in a shared layer (ADR-0017).
type ObjectAudience int32

const (
	// Backward-compatible public visibility for old clients and stored rows.
	ObjectAudience_OBJECT_AUDIENCE_UNSPECIFIED ObjectAudience = 0
	// Visible to every account that may read the layer.
	ObjectAudience_OBJECT_AUDIENCE_PUBLIC ObjectAudience = 1
	// Visible only to the authoring account.
	ObjectAudience_OBJECT_AUDIENCE_AUTHOR ObjectAudience = 2
	// Visible to the author plus audience_ids.
	ObjectAudience_OBJECT_AUDIENCE_DIRECT ObjectAudience = 3
	// Visible to the author plus layer owners and editors.
	ObjectAudience_OBJECT_AUDIENCE_ROLE ObjectAudience = 4
)

// Enum value maps for ObjectAudience.
var (
	ObjectAudience_name = map[int32]string{
		0: "OBJECT_AUDIENCE_UNSPECIFIED",
		1: "OBJECT_AUDIENCE_PUBLIC",
		2: "OBJECT_AUDIENCE_AUTHOR",
		3: "OBJECT_AUDIENCE_DIRECT",
		4: "OBJECT_AUDIENCE_ROLE",
	}
	ObjectAudience_value = map[string]int32{
		"OBJECT_AUDIENCE_UNSPECIFIED": 0,
		"OBJECT_AUDIENCE_PUBLIC":      1,
		"OBJECT_AUDIENCE_AUTHOR":      2,
		"OBJECT_AUDIENCE_DIRECT":      3,
		"OBJECT_AUDIENCE_ROLE":        4,
	}
)

func (x ObjectAudience) Enum() *ObjectAudience {
	p := new(ObjectAudience)
	*p = x
	return p
}

func (x ObjectAudience) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectAudience) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_object_proto_enumTypes[0].Descriptor()
}

func (ObjectAudience) Type() protoreflect.EnumType {
	return &file_qwibi_v1_object_proto_enumTypes[0]
}

func (x ObjectAudience) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectAudience.Descriptor instead.
func (ObjectAudience) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_object_proto_rawDescGZIP(), []int{0}
}

// Feature is one part of a GeoObject, modelled on a GeoJSON Feature: a geometry
// plus its own free-form properties. A GeoObject groups related features (for
// example, a route's path plus its start and end markers) under one identity.
type Feature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned id (UUIDv7), unique within the owning object. Empty on
	// write (the server assigns it); a uuid on read.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Rendered in v0 using the same canonical conversion as the object's primary
	// geometry, including expansion of every GeometryCollection member. Required:
	// a feature without geometry is meaningless here (unlike GeoJSON, which
	// permits null geometry).
	Geometry *Geometry `protobuf:"bytes,2,opt,name=geometry,proto3" json:"geometry,omitempty"`
	// Rendered in v0 as generic data: these free-form app-defined attributes
	// overlay the object's properties for this constituent, but acquire no
	// implicit paint meaning.
	Properties *structpb.Struct `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	// Per-feature render style, rendered in v0 and forwarded verbatim. For every
	// style property independently, precedence is Feature > GeoObject > GeoLayer
	// > theme; this carrier is the highest-precedence value for its constituent.
	Style         string `protobuf:"bytes,4,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_qwibi_v1_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_object_proto_rawDescGZIP(), []int{0}
}

func (x *Feature) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Feature) GetGeometry() *Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *Feature) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Feature) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

// GeoObject is the primary spatial entity placed on a layer. It carries one
// top-level geometry (the value indexed in PostGIS for spatial queries) and may
// additionally group several Features. It belongs to exactly one layer and is
// never inlined inside the layer message.
type GeoObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7, stable public identifier and primary key.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Owning layer's public id.
	LayerId string `protobuf:"bytes,2,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	// Primary geometry; this is the geometry persisted to and read back from the
	// PostGIS geometry column and matched by spatial queries. Required.
	Geometry *Geometry `protobuf:"bytes,4,opt,name=geometry,proto3" json:"geometry,omitempty"`
	// Optional ordered constituents, rendered in v0 under this object's identity.
	// Each valid feature is emitted in wire order alongside the primary geometry.
	Features []*Feature `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`
	// Free-form, app-defined attributes.
	Properties *structpb.Struct `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`
	// Application-defined type discriminator, e.g. "poi", "track", "zone".
	ObjectType string `protobuf:"bytes,7,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// Application-defined classification/grouping label. Reserved as a rendering
	// input in v0: it has no generic paint, visibility, ordering or presentation-
	// selection effect today.
	Category string `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	// Rendering/ordering priority; higher is more important.
	Priority int32 `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	// Whether the client may select/interact with the object.
	IsSelectable bool `protobuf:"varint,10,opt,name=is_selectable,json=isSelectable,proto3" json:"is_selectable,omitempty"`
	// Rendered in v0 as the first visibility gate.
	IsVisible bool `protobuf:"varint,11,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	// Object-level render style, rendered in v0 and forwarded verbatim. For every
	// style property independently, precedence is Feature > GeoObject > GeoLayer
	// > theme; this carrier styles the primary geometry and defaults constituents.
	Style     string                 `protobuf:"bytes,12,opt,name=style,proto3" json:"style,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Monotonic per-object mutation counter. It is independent of ServerEvent.seq:
	// clients reconcile a Snapshot against live deltas by dropping any delta whose
	// version is <= the snapshot object's version (no double-apply), and use it as
	// the optimistic-concurrency token. Server-owned.
	Version uint64 `protobuf:"varint,15,opt,name=version,proto3" json:"version,omitempty"`
	// Parent GeoObject public id (same layer); empty for roots. Objects form a
	// tree within a layer. Reserved as a rendering input in v0: parentage has no
	// implicit grouping, inheritance or visibility effect today.
	ParentId string `protobuf:"bytes,16,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Mutable human ID, unique within the layer. Every target Object has one.
	Hid string `protobuf:"bytes,17,opt,name=hid,proto3" json:"hid,omitempty"`
	// Display name shown in UI.
	Name string `protobuf:"bytes,18,opt,name=name,proto3" json:"name,omitempty"`
	// Geometry type, derived server-side from `geometry`. Server-owned and
	// reserved as a rendering input in v0: renderers derive the kind from the
	// canonical geometry payload, so this projection has no image effect today.
	Gtype GeometryType `protobuf:"varint,19,opt,name=gtype,proto3,enum=qwibi.v1.GeometryType" json:"gtype,omitempty"`
	// Optional auto-expiry: past this time the object is dropped from reads and
	// swept away. Unset = never expires. Server-owned (set from
	// ObjectWrite.ttl_seconds) and reserved as a rendering input in v0: clients
	// observe deletion and do not apply an independent render timer today.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// State-plane checkpoint stamp of `geometry` for kind=position (ADR-0022):
	// the (owner_epoch, seq) pair the stored geometry was last flushed at. Clients
	// that subscribed with state_kinds seed their per-object position gate from
	// this value at snapshot/read time and then apply only strictly newer
	// StateEvents (QTP §6.3). Zero pair = the object has never streamed. Server-owned.
	PositionVersion *StateVersion `protobuf:"bytes,22,opt,name=position_version,json=positionVersion,proto3" json:"position_version,omitempty"`
	// Immutable delivery scope stamped by the server from ObjectWrite.audience.
	// UNSPECIFIED is public for backward compatibility.
	Audience ObjectAudience `protobuf:"varint,23,opt,name=audience,proto3,enum=qwibi.v1.ObjectAudience" json:"audience,omitempty"`
	// Canonically sorted direct recipient account UUIDs. Server-owned.
	AudienceIds []string `protobuf:"bytes,24,rep,name=audience_ids,json=audienceIds,proto3" json:"audience_ids,omitempty"`
	// Server-owned immutable producer identity and latest mutation audit.
	Provenance *Provenance `protobuf:"bytes,25,opt,name=provenance,proto3" json:"provenance,omitempty"`
	// Private Layer media attached transactionally to this Object.
	LayerBlobIds  []string `protobuf:"bytes,26,rep,name=layer_blob_ids,json=layerBlobIds,proto3" json:"layer_blob_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoObject) Reset() {
	*x = GeoObject{}
	mi := &file_qwibi_v1_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoObject) ProtoMessage() {}

func (x *GeoObject) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoObject.ProtoReflect.Descriptor instead.
func (*GeoObject) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_object_proto_rawDescGZIP(), []int{1}
}

func (x *GeoObject) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GeoObject) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *GeoObject) GetGeometry() *Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *GeoObject) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GeoObject) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GeoObject) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GeoObject) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GeoObject) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *GeoObject) GetIsSelectable() bool {
	if x != nil {
		return x.IsSelectable
	}
	return false
}

func (x *GeoObject) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *GeoObject) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *GeoObject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GeoObject) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GeoObject) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GeoObject) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *GeoObject) GetHid() string {
	if x != nil {
		return x.Hid
	}
	return ""
}

func (x *GeoObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeoObject) GetGtype() GeometryType {
	if x != nil {
		return x.Gtype
	}
	return GeometryType_GEOMETRY_TYPE_UNSPECIFIED
}

func (x *GeoObject) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GeoObject) GetPositionVersion() *StateVersion {
	if x != nil {
		return x.PositionVersion
	}
	return nil
}

func (x *GeoObject) GetAudience() ObjectAudience {
	if x != nil {
		return x.Audience
	}
	return ObjectAudience_OBJECT_AUDIENCE_UNSPECIFIED
}

func (x *GeoObject) GetAudienceIds() []string {
	if x != nil {
		return x.AudienceIds
	}
	return nil
}

func (x *GeoObject) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *GeoObject) GetLayerBlobIds() []string {
	if x != nil {
		return x.LayerBlobIds
	}
	return nil
}

// ObjectWrite is the mutable subset of a GeoObject accepted on create/update.
// Server-owned fields (uid, provenance, timestamps) are excluded so they
// cannot be spoofed by clients; the layer is named by the enclosing request.
type ObjectWrite struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Geometry *Geometry              `protobuf:"bytes,1,opt,name=geometry,proto3" json:"geometry,omitempty"`
	// Ordered v0-rendered constituents; see GeoObject.features and Feature.
	Features   []*Feature       `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	Properties *structpb.Struct `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	ObjectType string           `protobuf:"bytes,4,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// Reserved as a rendering input in v0; it has no image effect today.
	Category string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Priority int32  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	// Optional (proto3 presence): unset keeps the server default (selectable /
	// visible); set explicitly to override.
	IsSelectable *bool `protobuf:"varint,7,opt,name=is_selectable,json=isSelectable,proto3,oneof" json:"is_selectable,omitempty"`
	// The v0 visibility gate.
	IsVisible *bool `protobuf:"varint,8,opt,name=is_visible,json=isVisible,proto3,oneof" json:"is_visible,omitempty"`
	// Rendered in v0. For every style property independently, precedence is
	// Feature > GeoObject > GeoLayer > theme.
	Style string `protobuf:"bytes,9,opt,name=style,proto3" json:"style,omitempty"`
	// Optional parent object (same layer) to attach under; empty for a root.
	// Reserved as a rendering input in v0; it has no image effect today.
	ParentId string `protobuf:"bytes,10,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Required human ID, unique within the layer. Every target write supplies one.
	Hid string `protobuf:"bytes,11,opt,name=hid,proto3" json:"hid,omitempty"`
	// Optional display name shown in UI.
	Name string `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	// Optional time-to-live in seconds: the object auto-expires this long after the
	// write. 0 = no expiry. For ephemeral data (vehicle fixes, transient results).
	TtlSeconds uint32 `protobuf:"varint,13,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Optional delivery scope. Unset means public on create and preserves the
	// stored audience on update. Audience is immutable after creation in v1.
	Audience *ObjectAudience `protobuf:"varint,15,opt,name=audience,proto3,enum=qwibi.v1.ObjectAudience,oneof" json:"audience,omitempty"`
	// Direct recipient account UUIDs. Valid only with DIRECT; at most 16 unique
	// values. The server normalizes their order before persistence.
	AudienceIds []string `protobuf:"bytes,16,rep,name=audience_ids,json=audienceIds,proto3" json:"audience_ids,omitempty"`
	// Exact private Layer media references to attach in the Object transaction.
	LayerBlobIds  []string `protobuf:"bytes,17,rep,name=layer_blob_ids,json=layerBlobIds,proto3" json:"layer_blob_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectWrite) Reset() {
	*x = ObjectWrite{}
	mi := &file_qwibi_v1_object_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectWrite) ProtoMessage() {}

func (x *ObjectWrite) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_object_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectWrite.ProtoReflect.Descriptor instead.
func (*ObjectWrite) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_object_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectWrite) GetGeometry() *Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *ObjectWrite) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ObjectWrite) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ObjectWrite) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ObjectWrite) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ObjectWrite) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ObjectWrite) GetIsSelectable() bool {
	if x != nil && x.IsSelectable != nil {
		return *x.IsSelectable
	}
	return false
}

func (x *ObjectWrite) GetIsVisible() bool {
	if x != nil && x.IsVisible != nil {
		return *x.IsVisible
	}
	return false
}

func (x *ObjectWrite) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *ObjectWrite) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ObjectWrite) GetHid() string {
	if x != nil {
		return x.Hid
	}
	return ""
}

func (x *ObjectWrite) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectWrite) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ObjectWrite) GetAudience() ObjectAudience {
	if x != nil && x.Audience != nil {
		return *x.Audience
	}
	return ObjectAudience_OBJECT_AUDIENCE_UNSPECIFIED
}

func (x *ObjectWrite) GetAudienceIds() []string {
	if x != nil {
		return x.AudienceIds
	}
	return nil
}

func (x *ObjectWrite) GetLayerBlobIds() []string {
	if x != nil {
		return x.LayerBlobIds
	}
	return nil
}

var File_qwibi_v1_object_proto protoreflect.FileDescriptor

const file_qwibi_v1_object_proto_rawDesc = "" +
	"\n" +
	"\x15qwibi/v1/object.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x15qwibi/v1/common.proto\x1a\x17qwibi/v1/geometry.proto\x1a\x19qwibi/v1/provenance.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\aFeature\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2A^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\x03uid\x126\n" +
	"\bgeometry\x18\x02 \x01(\v2\x12.qwibi.v1.GeometryB\x06\xbaH\x03\xc8\x01\x01R\bgeometry\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12\x1f\n" +
	"\x05style\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x01R\x05style\"\xc7\f\n" +
	"\tGeoObject\x12Z\n" +
	"\x03uid\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x03uid\x12c\n" +
	"\blayer_id\x18\x02 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\alayerId\x126\n" +
	"\bgeometry\x18\x04 \x01(\v2\x12.qwibi.v1.GeometryB\x06\xbaH\x03\xc8\x01\x01R\bgeometry\x12-\n" +
	"\bfeatures\x18\x05 \x03(\v2\x11.qwibi.v1.FeatureR\bfeatures\x127\n" +
	"\n" +
	"properties\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12(\n" +
	"\vobject_type\x18\a \x01(\tB\a\xbaH\x04r\x02\x18@R\n" +
	"objectType\x12#\n" +
	"\bcategory\x18\b \x01(\tB\a\xbaH\x04r\x02\x18@R\bcategory\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12#\n" +
	"\ris_selectable\x18\n" +
	" \x01(\bR\fisSelectable\x12\x1d\n" +
	"\n" +
	"is_visible\x18\v \x01(\bR\tisVisible\x12\x1f\n" +
	"\x05style\x18\f \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x01R\x05style\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x0f \x01(\x04R\aversion\x12e\n" +
	"\tparent_id\x18\x10 \x01(\tBH\xbaHErC2A^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\bparentId\x122\n" +
	"\x03hid\x18\x11 \x01(\tB \xbaH\x1dr\x1b2\x19^[a-z0-9][a-z0-9-]{1,62}$R\x03hid\x12\x1c\n" +
	"\x04name\x18\x12 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\x04name\x12,\n" +
	"\x05gtype\x18\x13 \x01(\x0e2\x16.qwibi.v1.GeometryTypeR\x05gtype\x129\n" +
	"\n" +
	"expires_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12A\n" +
	"\x10position_version\x18\x16 \x01(\v2\x16.qwibi.v1.StateVersionR\x0fpositionVersion\x124\n" +
	"\baudience\x18\x17 \x01(\x0e2\x18.qwibi.v1.ObjectAudienceR\baudience\x12!\n" +
	"\faudience_ids\x18\x18 \x03(\tR\vaudienceIds\x12<\n" +
	"\n" +
	"provenance\x18\x19 \x01(\v2\x14.qwibi.v1.ProvenanceB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"provenance\x12\x8b\x01\n" +
	"\x0elayer_blob_ids\x18\x1a \x03(\tBe\xbaHb\x92\x01_\x10@\x18\x01\"YrW2R^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}-[0-9a-f]{32}$\x98\x01ER\flayerBlobIds:\xcf\x01\xbaH\xcb\x01\x1a\xc8\x01\n" +
	"\x12geo_object.creator\x12Ncreator_principal_id may be absent only for a platform-produced durable record\x1abthis.provenance.producer.producer_kind == 2 || this.provenance.producer.creator_principal_id != ''J\x04\b\x03\x10\x04J\x04\b\x15\x10\x16R\tauthor_idR\x06result\"\xda\a\n" +
	"\vObjectWrite\x126\n" +
	"\bgeometry\x18\x01 \x01(\v2\x12.qwibi.v1.GeometryB\x06\xbaH\x03\xc8\x01\x01R\bgeometry\x12-\n" +
	"\bfeatures\x18\x02 \x03(\v2\x11.qwibi.v1.FeatureR\bfeatures\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12(\n" +
	"\vobject_type\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18@R\n" +
	"objectType\x12#\n" +
	"\bcategory\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18@R\bcategory\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12(\n" +
	"\ris_selectable\x18\a \x01(\bH\x00R\fisSelectable\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_visible\x18\b \x01(\bH\x01R\tisVisible\x88\x01\x01\x12\x1f\n" +
	"\x05style\x18\t \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x01R\x05style\x12e\n" +
	"\tparent_id\x18\n" +
	" \x01(\tBH\xbaHErC2A^$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\bparentId\x125\n" +
	"\x03hid\x18\v \x01(\tB#\xbaH \xc8\x01\x01r\x1b2\x19^[a-z0-9][a-z0-9-]{1,62}$R\x03hid\x12\x1c\n" +
	"\x04name\x18\f \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\x04name\x12\x1f\n" +
	"\vttl_seconds\x18\r \x01(\rR\n" +
	"ttlSeconds\x129\n" +
	"\baudience\x18\x0f \x01(\x0e2\x18.qwibi.v1.ObjectAudienceH\x02R\baudience\x88\x01\x01\x12o\n" +
	"\faudience_ids\x18\x10 \x03(\tBL\xbaHI\x92\x01F\x10\x10\"Br@2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$R\vaudienceIds\x12\x8b\x01\n" +
	"\x0elayer_blob_ids\x18\x11 \x03(\tBe\xbaHb\x92\x01_\x10@\x18\x01\"YrW2R^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}-[0-9a-f]{32}$\x98\x01ER\flayerBlobIdsB\x10\n" +
	"\x0e_is_selectableB\r\n" +
	"\v_is_visibleB\v\n" +
	"\t_audienceJ\x04\b\x0e\x10\x0fR\x06result*\x9f\x01\n" +
	"\x0eObjectAudience\x12\x1f\n" +
	"\x1bOBJECT_AUDIENCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OBJECT_AUDIENCE_PUBLIC\x10\x01\x12\x1a\n" +
	"\x16OBJECT_AUDIENCE_AUTHOR\x10\x02\x12\x1a\n" +
	"\x16OBJECT_AUDIENCE_DIRECT\x10\x03\x12\x18\n" +
	"\x14OBJECT_AUDIENCE_ROLE\x10\x04B\x8e\x01\n" +
	"\fcom.qwibi.v1B\vObjectProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_object_proto_rawDescOnce sync.Once
	file_qwibi_v1_object_proto_rawDescData []byte
)

func file_qwibi_v1_object_proto_rawDescGZIP() []byte {
	file_qwibi_v1_object_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_object_proto_rawDesc), len(file_qwibi_v1_object_proto_rawDesc)))
	})
	return file_qwibi_v1_object_proto_rawDescData
}

var file_qwibi_v1_object_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qwibi_v1_object_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_qwibi_v1_object_proto_goTypes = []any{
	(ObjectAudience)(0),           // 0: qwibi.v1.ObjectAudience
	(*Feature)(nil),               // 1: qwibi.v1.Feature
	(*GeoObject)(nil),             // 2: qwibi.v1.GeoObject
	(*ObjectWrite)(nil),           // 3: qwibi.v1.ObjectWrite
	(*Geometry)(nil),              // 4: qwibi.v1.Geometry
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(GeometryType)(0),             // 7: qwibi.v1.GeometryType
	(*StateVersion)(nil),          // 8: qwibi.v1.StateVersion
	(*Provenance)(nil),            // 9: qwibi.v1.Provenance
}
var file_qwibi_v1_object_proto_depIdxs = []int32{
	4,  // 0: qwibi.v1.Feature.geometry:type_name -> qwibi.v1.Geometry
	5,  // 1: qwibi.v1.Feature.properties:type_name -> google.protobuf.Struct
	4,  // 2: qwibi.v1.GeoObject.geometry:type_name -> qwibi.v1.Geometry
	1,  // 3: qwibi.v1.GeoObject.features:type_name -> qwibi.v1.Feature
	5,  // 4: qwibi.v1.GeoObject.properties:type_name -> google.protobuf.Struct
	6,  // 5: qwibi.v1.GeoObject.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: qwibi.v1.GeoObject.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 7: qwibi.v1.GeoObject.gtype:type_name -> qwibi.v1.GeometryType
	6,  // 8: qwibi.v1.GeoObject.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 9: qwibi.v1.GeoObject.position_version:type_name -> qwibi.v1.StateVersion
	0,  // 10: qwibi.v1.GeoObject.audience:type_name -> qwibi.v1.ObjectAudience
	9,  // 11: qwibi.v1.GeoObject.provenance:type_name -> qwibi.v1.Provenance
	4,  // 12: qwibi.v1.ObjectWrite.geometry:type_name -> qwibi.v1.Geometry
	1,  // 13: qwibi.v1.ObjectWrite.features:type_name -> qwibi.v1.Feature
	5,  // 14: qwibi.v1.ObjectWrite.properties:type_name -> google.protobuf.Struct
	0,  // 15: qwibi.v1.ObjectWrite.audience:type_name -> qwibi.v1.ObjectAudience
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_qwibi_v1_object_proto_init() }
func file_qwibi_v1_object_proto_init() {
	if File_qwibi_v1_object_proto != nil {
		return
	}
	file_qwibi_v1_common_proto_init()
	file_qwibi_v1_geometry_proto_init()
	file_qwibi_v1_provenance_proto_init()
	file_qwibi_v1_object_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_object_proto_rawDesc), len(file_qwibi_v1_object_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_v1_object_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_object_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_object_proto_enumTypes,
		MessageInfos:      file_qwibi_v1_object_proto_msgTypes,
	}.Build()
	File_qwibi_v1_object_proto = out.File
	file_qwibi_v1_object_proto_goTypes = nil
	file_qwibi_v1_object_proto_depIdxs = nil
}
