// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/provenance.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActorKind identifies the principal class responsible for one mutation.
type ActorKind int32

const (
	ActorKind_ACTOR_KIND_UNSPECIFIED  ActorKind = 0
	ActorKind_ACTOR_KIND_HUMAN        ActorKind = 1
	ActorKind_ACTOR_KIND_APP          ActorKind = 2
	ActorKind_ACTOR_KIND_PLATFORM     ActorKind = 3
	ActorKind_ACTOR_KIND_ORGANIZATION ActorKind = 4
)

// Enum value maps for ActorKind.
var (
	ActorKind_name = map[int32]string{
		0: "ACTOR_KIND_UNSPECIFIED",
		1: "ACTOR_KIND_HUMAN",
		2: "ACTOR_KIND_APP",
		3: "ACTOR_KIND_PLATFORM",
		4: "ACTOR_KIND_ORGANIZATION",
	}
	ActorKind_value = map[string]int32{
		"ACTOR_KIND_UNSPECIFIED":  0,
		"ACTOR_KIND_HUMAN":        1,
		"ACTOR_KIND_APP":          2,
		"ACTOR_KIND_PLATFORM":     3,
		"ACTOR_KIND_ORGANIZATION": 4,
	}
)

func (x ActorKind) Enum() *ActorKind {
	p := new(ActorKind)
	*p = x
	return p
}

func (x ActorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_provenance_proto_enumTypes[0].Descriptor()
}

func (ActorKind) Type() protoreflect.EnumType {
	return &file_qwibi_v1_provenance_proto_enumTypes[0]
}

func (x ActorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorKind.Descriptor instead.
func (ActorKind) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_provenance_proto_rawDescGZIP(), []int{0}
}

// ProducerKind identifies the immutable namespace that produced a record.
// Human-authored records use the platform namespace while their human identity
// remains in MutationAudit.actor.
type ProducerKind int32

const (
	ProducerKind_PRODUCER_KIND_UNSPECIFIED ProducerKind = 0
	ProducerKind_PRODUCER_KIND_APP         ProducerKind = 1
	ProducerKind_PRODUCER_KIND_PLATFORM    ProducerKind = 2
)

// Enum value maps for ProducerKind.
var (
	ProducerKind_name = map[int32]string{
		0: "PRODUCER_KIND_UNSPECIFIED",
		1: "PRODUCER_KIND_APP",
		2: "PRODUCER_KIND_PLATFORM",
	}
	ProducerKind_value = map[string]int32{
		"PRODUCER_KIND_UNSPECIFIED": 0,
		"PRODUCER_KIND_APP":         1,
		"PRODUCER_KIND_PLATFORM":    2,
	}
)

func (x ProducerKind) Enum() *ProducerKind {
	p := new(ProducerKind)
	*p = x
	return p
}

func (x ProducerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProducerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_provenance_proto_enumTypes[1].Descriptor()
}

func (ProducerKind) Type() protoreflect.EnumType {
	return &file_qwibi_v1_provenance_proto_enumTypes[1]
}

func (x ProducerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProducerKind.Descriptor instead.
func (ProducerKind) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_provenance_proto_rawDescGZIP(), []int{1}
}

// ActorProvenance is the server-resolved identity that performed a mutation.
// It is attribution only: an App tuple records which installation acted and
// never grants that installation authority.
type ActorProvenance struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ActorKind ActorKind              `protobuf:"varint,1,opt,name=actor_kind,json=actorKind,proto3,enum=qwibi.v1.ActorKind" json:"actor_kind,omitempty"`
	// Immutable principal UUID. It may be empty only when actor_kind is PLATFORM.
	ActorPrincipalId string `protobuf:"bytes,2,opt,name=actor_principal_id,json=actorPrincipalId,proto3" json:"actor_principal_id,omitempty"`
	// Immutable UUIDv7 identity of the authenticated credential. Platform
	// mutations may omit it when no credential exists.
	CredentialId   string `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	AppId          string `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ReleaseId      string `protobuf:"bytes,5,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	InstallationId string `protobuf:"bytes,6,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	// Organization bound to an organization actor. No other actor may carry it.
	OrganizationId string `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActorProvenance) Reset() {
	*x = ActorProvenance{}
	mi := &file_qwibi_v1_provenance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorProvenance) ProtoMessage() {}

func (x *ActorProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_provenance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorProvenance.ProtoReflect.Descriptor instead.
func (*ActorProvenance) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_provenance_proto_rawDescGZIP(), []int{0}
}

func (x *ActorProvenance) GetActorKind() ActorKind {
	if x != nil {
		return x.ActorKind
	}
	return ActorKind_ACTOR_KIND_UNSPECIFIED
}

func (x *ActorProvenance) GetActorPrincipalId() string {
	if x != nil {
		return x.ActorPrincipalId
	}
	return ""
}

func (x *ActorProvenance) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *ActorProvenance) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ActorProvenance) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ActorProvenance) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *ActorProvenance) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

// ProducerProvenance is stamped once when a record is created and never
// rewritten by later mutations. App production requires the exact release and
// installation for Layer writes. App data has no installation; platform
// production carries no App tuple.
type ProducerProvenance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProducerKind   ProducerKind           `protobuf:"varint,1,opt,name=producer_kind,json=producerKind,proto3,enum=qwibi.v1.ProducerKind" json:"producer_kind,omitempty"`
	AppId          string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ReleaseId      string                 `protobuf:"bytes,3,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	InstallationId string                 `protobuf:"bytes,4,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	// Immutable principal UUID that created a durable record. Shared-vocabulary
	// uses with no distinct creator, such as state-plane values, leave it empty;
	// each durable record carrier constrains absence in its own validation rule.
	CreatorPrincipalId string `protobuf:"bytes,5,opt,name=creator_principal_id,json=creatorPrincipalId,proto3" json:"creator_principal_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProducerProvenance) Reset() {
	*x = ProducerProvenance{}
	mi := &file_qwibi_v1_provenance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProducerProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerProvenance) ProtoMessage() {}

func (x *ProducerProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_provenance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerProvenance.ProtoReflect.Descriptor instead.
func (*ProducerProvenance) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_provenance_proto_rawDescGZIP(), []int{1}
}

func (x *ProducerProvenance) GetProducerKind() ProducerKind {
	if x != nil {
		return x.ProducerKind
	}
	return ProducerKind_PRODUCER_KIND_UNSPECIFIED
}

func (x *ProducerProvenance) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ProducerProvenance) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *ProducerProvenance) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *ProducerProvenance) GetCreatorPrincipalId() string {
	if x != nil {
		return x.CreatorPrincipalId
	}
	return ""
}

// MutationAudit records the server-resolved actor and trace relationship for
// the latest mutation represented by a record or event.
type MutationAudit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Actor *ActorProvenance       `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	// Opaque server-stamped identifier shared by related work. Empty when the
	// mutation has no correlation context.
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Opaque server-stamped identifier of the direct cause. For a write made in
	// reaction to a delivered Layer event it names that event and the causal
	// depth that event itself reached, so a stored record states its own place
	// in the chain; for a root mutation it is the server-minted identity of the
	// originating request. Clients cannot supply it and must not parse it.
	CausationId string                 `protobuf:"bytes,3,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	RecordedAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	// Number of causal hops between the originating root action and this
	// mutation. A root action carries zero; a write made in reaction to a
	// delivered event carries the depth of that event plus one. The server
	// derives it from the durable event named by causation_id, so a client can
	// neither supply nor reset it.
	CausalDepth   uint32 `protobuf:"varint,5,opt,name=causal_depth,json=causalDepth,proto3" json:"causal_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationAudit) Reset() {
	*x = MutationAudit{}
	mi := &file_qwibi_v1_provenance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationAudit) ProtoMessage() {}

func (x *MutationAudit) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_provenance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationAudit.ProtoReflect.Descriptor instead.
func (*MutationAudit) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_provenance_proto_rawDescGZIP(), []int{2}
}

func (x *MutationAudit) GetActor() *ActorProvenance {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *MutationAudit) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *MutationAudit) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *MutationAudit) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *MutationAudit) GetCausalDepth() uint32 {
	if x != nil {
		return x.CausalDepth
	}
	return 0
}

// Provenance is the single server-owned vocabulary carried by mutation records
// and event envelopes. Clients cannot supply or rewrite either component.
type Provenance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producer      *ProducerProvenance    `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	MutationAudit *MutationAudit         `protobuf:"bytes,2,opt,name=mutation_audit,json=mutationAudit,proto3" json:"mutation_audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_qwibi_v1_provenance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_provenance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_provenance_proto_rawDescGZIP(), []int{3}
}

func (x *Provenance) GetProducer() *ProducerProvenance {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *Provenance) GetMutationAudit() *MutationAudit {
	if x != nil {
		return x.MutationAudit
	}
	return nil
}

var File_qwibi_v1_provenance_proto protoreflect.FileDescriptor

const file_qwibi_v1_provenance_proto_rawDesc = "" +
	"\n" +
	"\x19qwibi/v1/provenance.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\v\n" +
	"\x0fActorProvenance\x12>\n" +
	"\n" +
	"actor_kind\x18\x01 \x01(\x0e2\x13.qwibi.v1.ActorKindB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\tactorKind\x12y\n" +
	"\x12actor_principal_id\x18\x02 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x10actorPrincipalId\x12w\n" +
	"\rcredential_id\x18\x03 \x01(\tBR\xbaHO\xd8\x01\x01rJ2E^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$\x98\x01$R\fcredentialId\x12b\n" +
	"\x06app_id\x18\x04 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12j\n" +
	"\n" +
	"release_id\x18\x05 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\treleaseId\x12t\n" +
	"\x0finstallation_id\x18\x06 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x0einstallationId\x12t\n" +
	"\x0forganization_id\x18\a \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x0eorganizationId:\xe3\x05\xbaH\xdf\x05\x1a\x8f\x01\n" +
	"\x1aactor_provenance.principal\x12:actor_principal_id may be absent only for a platform actor\x1a5this.actor_kind == 3 || this.actor_principal_id != ''\x1a\xc6\x01\n" +
	"#actor_provenance.organization_tuple\x12Oan organization actor requires organization_id and other actors cannot carry it\x1aNthis.actor_kind == 4 ? this.organization_id != '' : this.organization_id == ''\x1a{\n" +
	"\x1bactor_provenance.credential\x12*human and App actors require credential_id\x1a0this.actor_kind == 3 || this.credential_id != ''\x1a\x84\x02\n" +
	"\x1aactor_provenance.app_tuple\x12Wan App actor requires app_id and release_id; installation_id is absent only on App data\x1a\x8c\x01this.actor_kind == 2 ? this.app_id != '' && this.release_id != '' : this.app_id == '' && this.release_id == '' && this.installation_id == ''\"\xd3\x06\n" +
	"\x12ProducerProvenance\x12G\n" +
	"\rproducer_kind\x18\x01 \x01(\x0e2\x16.qwibi.v1.ProducerKindB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\fproducerKind\x12b\n" +
	"\x06app_id\x18\x02 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x05appId\x12j\n" +
	"\n" +
	"release_id\x18\x03 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\treleaseId\x12t\n" +
	"\x0finstallation_id\x18\x04 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x0einstallationId\x12}\n" +
	"\x14creator_principal_id\x18\x05 \x01(\tBK\xbaHH\xd8\x01\x01rC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\x12creatorPrincipalId:\xae\x02\xbaH\xaa\x02\x1a\xa7\x02\n" +
	"\x1cproducer_provenance.identity\x12Zan App producer requires app_id and release_id; installation_id is absent only on App data\x1a\xaa\x01this.producer_kind == 1 ? this.app_id != '' && this.release_id != '' : this.producer_kind == 2 && this.app_id == '' && this.release_id == '' && this.installation_id == ''\"\x8e\x02\n" +
	"\rMutationAudit\x127\n" +
	"\x05actor\x18\x01 \x01(\v2\x19.qwibi.v1.ActorProvenanceB\x06\xbaH\x03\xc8\x01\x01R\x05actor\x12/\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\rcorrelationId\x12+\n" +
	"\fcausation_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\vcausationId\x12C\n" +
	"\vrecorded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"recordedAt\x12!\n" +
	"\fcausal_depth\x18\x05 \x01(\rR\vcausalDepth\"\x96\x01\n" +
	"\n" +
	"Provenance\x12@\n" +
	"\bproducer\x18\x01 \x01(\v2\x1c.qwibi.v1.ProducerProvenanceB\x06\xbaH\x03\xc8\x01\x01R\bproducer\x12F\n" +
	"\x0emutation_audit\x18\x02 \x01(\v2\x17.qwibi.v1.MutationAuditB\x06\xbaH\x03\xc8\x01\x01R\rmutationAudit*\x87\x01\n" +
	"\tActorKind\x12\x1a\n" +
	"\x16ACTOR_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTOR_KIND_HUMAN\x10\x01\x12\x12\n" +
	"\x0eACTOR_KIND_APP\x10\x02\x12\x17\n" +
	"\x13ACTOR_KIND_PLATFORM\x10\x03\x12\x1b\n" +
	"\x17ACTOR_KIND_ORGANIZATION\x10\x04*`\n" +
	"\fProducerKind\x12\x1d\n" +
	"\x19PRODUCER_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRODUCER_KIND_APP\x10\x01\x12\x1a\n" +
	"\x16PRODUCER_KIND_PLATFORM\x10\x02B\x92\x01\n" +
	"\fcom.qwibi.v1B\x0fProvenanceProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_provenance_proto_rawDescOnce sync.Once
	file_qwibi_v1_provenance_proto_rawDescData []byte
)

func file_qwibi_v1_provenance_proto_rawDescGZIP() []byte {
	file_qwibi_v1_provenance_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_provenance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_provenance_proto_rawDesc), len(file_qwibi_v1_provenance_proto_rawDesc)))
	})
	return file_qwibi_v1_provenance_proto_rawDescData
}

var file_qwibi_v1_provenance_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_qwibi_v1_provenance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_qwibi_v1_provenance_proto_goTypes = []any{
	(ActorKind)(0),                // 0: qwibi.v1.ActorKind
	(ProducerKind)(0),             // 1: qwibi.v1.ProducerKind
	(*ActorProvenance)(nil),       // 2: qwibi.v1.ActorProvenance
	(*ProducerProvenance)(nil),    // 3: qwibi.v1.ProducerProvenance
	(*MutationAudit)(nil),         // 4: qwibi.v1.MutationAudit
	(*Provenance)(nil),            // 5: qwibi.v1.Provenance
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_qwibi_v1_provenance_proto_depIdxs = []int32{
	0, // 0: qwibi.v1.ActorProvenance.actor_kind:type_name -> qwibi.v1.ActorKind
	1, // 1: qwibi.v1.ProducerProvenance.producer_kind:type_name -> qwibi.v1.ProducerKind
	2, // 2: qwibi.v1.MutationAudit.actor:type_name -> qwibi.v1.ActorProvenance
	6, // 3: qwibi.v1.MutationAudit.recorded_at:type_name -> google.protobuf.Timestamp
	3, // 4: qwibi.v1.Provenance.producer:type_name -> qwibi.v1.ProducerProvenance
	4, // 5: qwibi.v1.Provenance.mutation_audit:type_name -> qwibi.v1.MutationAudit
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_qwibi_v1_provenance_proto_init() }
func file_qwibi_v1_provenance_proto_init() {
	if File_qwibi_v1_provenance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_provenance_proto_rawDesc), len(file_qwibi_v1_provenance_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_v1_provenance_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_provenance_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_provenance_proto_enumTypes,
		MessageInfos:      file_qwibi_v1_provenance_proto_msgTypes,
	}.Build()
	File_qwibi_v1_provenance_proto = out.File
	file_qwibi_v1_provenance_proto_goTypes = nil
	file_qwibi_v1_provenance_proto_depIdxs = nil
}
