// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qwibi/v1/push.proto

package qwibiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushPlatform identifies the delivery protocol used by a registered token.
// Additional native platforms can be added without changing the token model.
type PushPlatform int32

const (
	PushPlatform_PUSH_PLATFORM_UNSPECIFIED PushPlatform = 0
	PushPlatform_PUSH_PLATFORM_WEBPUSH     PushPlatform = 1
)

// Enum value maps for PushPlatform.
var (
	PushPlatform_name = map[int32]string{
		0: "PUSH_PLATFORM_UNSPECIFIED",
		1: "PUSH_PLATFORM_WEBPUSH",
	}
	PushPlatform_value = map[string]int32{
		"PUSH_PLATFORM_UNSPECIFIED": 0,
		"PUSH_PLATFORM_WEBPUSH":     1,
	}
)

func (x PushPlatform) Enum() *PushPlatform {
	p := new(PushPlatform)
	*p = x
	return p
}

func (x PushPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_push_proto_enumTypes[0].Descriptor()
}

func (PushPlatform) Type() protoreflect.EnumType {
	return &file_qwibi_v1_push_proto_enumTypes[0]
}

func (x PushPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushPlatform.Descriptor instead.
func (PushPlatform) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{0}
}

// LayerNotifyPolicy controls push delivery for one account's layer membership.
type LayerNotifyPolicy int32

const (
	LayerNotifyPolicy_LAYER_NOTIFY_POLICY_UNSPECIFIED LayerNotifyPolicy = 0
	LayerNotifyPolicy_LAYER_NOTIFY_POLICY_ALL         LayerNotifyPolicy = 1
	LayerNotifyPolicy_LAYER_NOTIFY_POLICY_NONE        LayerNotifyPolicy = 2
)

// Enum value maps for LayerNotifyPolicy.
var (
	LayerNotifyPolicy_name = map[int32]string{
		0: "LAYER_NOTIFY_POLICY_UNSPECIFIED",
		1: "LAYER_NOTIFY_POLICY_ALL",
		2: "LAYER_NOTIFY_POLICY_NONE",
	}
	LayerNotifyPolicy_value = map[string]int32{
		"LAYER_NOTIFY_POLICY_UNSPECIFIED": 0,
		"LAYER_NOTIFY_POLICY_ALL":         1,
		"LAYER_NOTIFY_POLICY_NONE":        2,
	}
)

func (x LayerNotifyPolicy) Enum() *LayerNotifyPolicy {
	p := new(LayerNotifyPolicy)
	*p = x
	return p
}

func (x LayerNotifyPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerNotifyPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_qwibi_v1_push_proto_enumTypes[1].Descriptor()
}

func (LayerNotifyPolicy) Type() protoreflect.EnumType {
	return &file_qwibi_v1_push_proto_enumTypes[1]
}

func (x LayerNotifyPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerNotifyPolicy.Descriptor instead.
func (LayerNotifyPolicy) EnumDescriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{1}
}

// PushTokenInfo is the non-sensitive registry view of a push token. Endpoint
// and key material are accepted only during registration and are never listed.
type PushTokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Platform      PushPlatform           `protobuf:"varint,2,opt,name=platform,proto3,enum=qwibi.v1.PushPlatform" json:"platform,omitempty"`
	DeviceLabel   string                 `protobuf:"bytes,3,opt,name=device_label,json=deviceLabel,proto3" json:"device_label,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastOkAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_ok_at,json=lastOkAt,proto3" json:"last_ok_at,omitempty"`
	DisabledAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=disabled_at,json=disabledAt,proto3" json:"disabled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTokenInfo) Reset() {
	*x = PushTokenInfo{}
	mi := &file_qwibi_v1_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenInfo) ProtoMessage() {}

func (x *PushTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenInfo.ProtoReflect.Descriptor instead.
func (*PushTokenInfo) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushTokenInfo) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *PushTokenInfo) GetPlatform() PushPlatform {
	if x != nil {
		return x.Platform
	}
	return PushPlatform_PUSH_PLATFORM_UNSPECIFIED
}

func (x *PushTokenInfo) GetDeviceLabel() string {
	if x != nil {
		return x.DeviceLabel
	}
	return ""
}

func (x *PushTokenInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PushTokenInfo) GetLastOkAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastOkAt
	}
	return nil
}

func (x *PushTokenInfo) GetDisabledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisabledAt
	}
	return nil
}

// RegisterPushTokenRequest registers or refreshes the caller's browser token.
// Re-registering an endpoint is idempotent and transfers it to the caller.
type RegisterPushTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      PushPlatform           `protobuf:"varint,1,opt,name=platform,proto3,enum=qwibi.v1.PushPlatform" json:"platform,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh        string                 `protobuf:"bytes,3,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth          string                 `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	DeviceLabel   string                 `protobuf:"bytes,5,opt,name=device_label,json=deviceLabel,proto3" json:"device_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPushTokenRequest) Reset() {
	*x = RegisterPushTokenRequest{}
	mi := &file_qwibi_v1_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPushTokenRequest) ProtoMessage() {}

func (x *RegisterPushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPushTokenRequest.ProtoReflect.Descriptor instead.
func (*RegisterPushTokenRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPushTokenRequest) GetPlatform() PushPlatform {
	if x != nil {
		return x.Platform
	}
	return PushPlatform_PUSH_PLATFORM_UNSPECIFIED
}

func (x *RegisterPushTokenRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterPushTokenRequest) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *RegisterPushTokenRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *RegisterPushTokenRequest) GetDeviceLabel() string {
	if x != nil {
		return x.DeviceLabel
	}
	return ""
}

type RegisterPushTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPushTokenResponse) Reset() {
	*x = RegisterPushTokenResponse{}
	mi := &file_qwibi_v1_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPushTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPushTokenResponse) ProtoMessage() {}

func (x *RegisterPushTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPushTokenResponse.ProtoReflect.Descriptor instead.
func (*RegisterPushTokenResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPushTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

// UnregisterPushTokenRequest permanently removes one token owned by the caller.
type UnregisterPushTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterPushTokenRequest) Reset() {
	*x = UnregisterPushTokenRequest{}
	mi := &file_qwibi_v1_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterPushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterPushTokenRequest) ProtoMessage() {}

func (x *UnregisterPushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterPushTokenRequest.ProtoReflect.Descriptor instead.
func (*UnregisterPushTokenRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterPushTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type UnregisterPushTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterPushTokenResponse) Reset() {
	*x = UnregisterPushTokenResponse{}
	mi := &file_qwibi_v1_push_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterPushTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterPushTokenResponse) ProtoMessage() {}

func (x *UnregisterPushTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterPushTokenResponse.ProtoReflect.Descriptor instead.
func (*UnregisterPushTokenResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{4}
}

// ListPushTokensRequest lists the caller's tokens one keyset page at a time.
type ListPushTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *PageRequest           `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPushTokensRequest) Reset() {
	*x = ListPushTokensRequest{}
	mi := &file_qwibi_v1_push_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushTokensRequest) ProtoMessage() {}

func (x *ListPushTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushTokensRequest.ProtoReflect.Descriptor instead.
func (*ListPushTokensRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{5}
}

func (x *ListPushTokensRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListPushTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*PushTokenInfo       `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Page          *PageResponse          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPushTokensResponse) Reset() {
	*x = ListPushTokensResponse{}
	mi := &file_qwibi_v1_push_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushTokensResponse) ProtoMessage() {}

func (x *ListPushTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushTokensResponse.ProtoReflect.Descriptor instead.
func (*ListPushTokensResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{6}
}

func (x *ListPushTokensResponse) GetTokens() []*PushTokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListPushTokensResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// SetLayerNotifyPolicyRequest updates the caller's own membership policy.
type SetLayerNotifyPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LayerId       string                 `protobuf:"bytes,1,opt,name=layer_id,json=layerId,proto3" json:"layer_id,omitempty"`
	Policy        LayerNotifyPolicy      `protobuf:"varint,2,opt,name=policy,proto3,enum=qwibi.v1.LayerNotifyPolicy" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLayerNotifyPolicyRequest) Reset() {
	*x = SetLayerNotifyPolicyRequest{}
	mi := &file_qwibi_v1_push_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLayerNotifyPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLayerNotifyPolicyRequest) ProtoMessage() {}

func (x *SetLayerNotifyPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLayerNotifyPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetLayerNotifyPolicyRequest) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{7}
}

func (x *SetLayerNotifyPolicyRequest) GetLayerId() string {
	if x != nil {
		return x.LayerId
	}
	return ""
}

func (x *SetLayerNotifyPolicyRequest) GetPolicy() LayerNotifyPolicy {
	if x != nil {
		return x.Policy
	}
	return LayerNotifyPolicy_LAYER_NOTIFY_POLICY_UNSPECIFIED
}

type SetLayerNotifyPolicyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EffectivePolicy LayerNotifyPolicy      `protobuf:"varint,1,opt,name=effective_policy,json=effectivePolicy,proto3,enum=qwibi.v1.LayerNotifyPolicy" json:"effective_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetLayerNotifyPolicyResponse) Reset() {
	*x = SetLayerNotifyPolicyResponse{}
	mi := &file_qwibi_v1_push_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLayerNotifyPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLayerNotifyPolicyResponse) ProtoMessage() {}

func (x *SetLayerNotifyPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qwibi_v1_push_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLayerNotifyPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetLayerNotifyPolicyResponse) Descriptor() ([]byte, []int) {
	return file_qwibi_v1_push_proto_rawDescGZIP(), []int{8}
}

func (x *SetLayerNotifyPolicyResponse) GetEffectivePolicy() LayerNotifyPolicy {
	if x != nil {
		return x.EffectivePolicy
	}
	return LayerNotifyPolicy_LAYER_NOTIFY_POLICY_UNSPECIFIED
}

var File_qwibi_v1_push_proto protoreflect.FileDescriptor

const file_qwibi_v1_push_proto_rawDesc = "" +
	"\n" +
	"\x13qwibi/v1/push.proto\x12\bqwibi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15qwibi/v1/common.proto\"\xfd\x02\n" +
	"\rPushTokenInfo\x12c\n" +
	"\btoken_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\atokenId\x122\n" +
	"\bplatform\x18\x02 \x01(\x0e2\x16.qwibi.v1.PushPlatformR\bplatform\x12!\n" +
	"\fdevice_label\x18\x03 \x01(\tR\vdeviceLabel\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\n" +
	"last_ok_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastOkAt\x12;\n" +
	"\vdisabled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"disabledAt\"\xf3\x01\n" +
	"\x18RegisterPushTokenRequest\x12>\n" +
	"\bplatform\x18\x01 \x01(\x0e2\x16.qwibi.v1.PushPlatformB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\bplatform\x12&\n" +
	"\bendpoint\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80 R\bendpoint\x12\"\n" +
	"\x06p256dh\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x06p256dh\x12\x1e\n" +
	"\x04auth\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x04auth\x12+\n" +
	"\fdevice_label\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\vdeviceLabel\"\x80\x01\n" +
	"\x19RegisterPushTokenResponse\x12c\n" +
	"\btoken_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\atokenId\"\x81\x01\n" +
	"\x1aUnregisterPushTokenRequest\x12c\n" +
	"\btoken_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\atokenId\"\x1d\n" +
	"\x1bUnregisterPushTokenResponse\"B\n" +
	"\x15ListPushTokensRequest\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.qwibi.v1.PageRequestR\x04page\"u\n" +
	"\x16ListPushTokensResponse\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.qwibi.v1.PushTokenInfoR\x06tokens\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.qwibi.v1.PageResponseR\x04page\"\xc3\x01\n" +
	"\x1bSetLayerNotifyPolicyRequest\x12c\n" +
	"\blayer_id\x18\x01 \x01(\tBH\xbaHErC2>^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\x98\x01$R\alayerId\x12?\n" +
	"\x06policy\x18\x02 \x01(\x0e2\x1b.qwibi.v1.LayerNotifyPolicyB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06policy\"f\n" +
	"\x1cSetLayerNotifyPolicyResponse\x12F\n" +
	"\x10effective_policy\x18\x01 \x01(\x0e2\x1b.qwibi.v1.LayerNotifyPolicyR\x0feffectivePolicy*H\n" +
	"\fPushPlatform\x12\x1d\n" +
	"\x19PUSH_PLATFORM_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PUSH_PLATFORM_WEBPUSH\x10\x01*s\n" +
	"\x11LayerNotifyPolicy\x12#\n" +
	"\x1fLAYER_NOTIFY_POLICY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LAYER_NOTIFY_POLICY_ALL\x10\x01\x12\x1c\n" +
	"\x18LAYER_NOTIFY_POLICY_NONE\x10\x02B\x8c\x01\n" +
	"\fcom.qwibi.v1B\tPushProtoP\x01Z0github.com/qwibi/qwibi-proto-go/qwibi/v1;qwibiv1\xa2\x02\x03QXX\xaa\x02\bQwibi.V1\xca\x02\bQwibi\\V1\xe2\x02\x14Qwibi\\V1\\GPBMetadata\xea\x02\tQwibi::V1b\x06proto3"

var (
	file_qwibi_v1_push_proto_rawDescOnce sync.Once
	file_qwibi_v1_push_proto_rawDescData []byte
)

func file_qwibi_v1_push_proto_rawDescGZIP() []byte {
	file_qwibi_v1_push_proto_rawDescOnce.Do(func() {
		file_qwibi_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qwibi_v1_push_proto_rawDesc), len(file_qwibi_v1_push_proto_rawDesc)))
	})
	return file_qwibi_v1_push_proto_rawDescData
}

var file_qwibi_v1_push_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_qwibi_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_qwibi_v1_push_proto_goTypes = []any{
	(PushPlatform)(0),                    // 0: qwibi.v1.PushPlatform
	(LayerNotifyPolicy)(0),               // 1: qwibi.v1.LayerNotifyPolicy
	(*PushTokenInfo)(nil),                // 2: qwibi.v1.PushTokenInfo
	(*RegisterPushTokenRequest)(nil),     // 3: qwibi.v1.RegisterPushTokenRequest
	(*RegisterPushTokenResponse)(nil),    // 4: qwibi.v1.RegisterPushTokenResponse
	(*UnregisterPushTokenRequest)(nil),   // 5: qwibi.v1.UnregisterPushTokenRequest
	(*UnregisterPushTokenResponse)(nil),  // 6: qwibi.v1.UnregisterPushTokenResponse
	(*ListPushTokensRequest)(nil),        // 7: qwibi.v1.ListPushTokensRequest
	(*ListPushTokensResponse)(nil),       // 8: qwibi.v1.ListPushTokensResponse
	(*SetLayerNotifyPolicyRequest)(nil),  // 9: qwibi.v1.SetLayerNotifyPolicyRequest
	(*SetLayerNotifyPolicyResponse)(nil), // 10: qwibi.v1.SetLayerNotifyPolicyResponse
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
	(*PageRequest)(nil),                  // 12: qwibi.v1.PageRequest
	(*PageResponse)(nil),                 // 13: qwibi.v1.PageResponse
}
var file_qwibi_v1_push_proto_depIdxs = []int32{
	0,  // 0: qwibi.v1.PushTokenInfo.platform:type_name -> qwibi.v1.PushPlatform
	11, // 1: qwibi.v1.PushTokenInfo.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: qwibi.v1.PushTokenInfo.last_ok_at:type_name -> google.protobuf.Timestamp
	11, // 3: qwibi.v1.PushTokenInfo.disabled_at:type_name -> google.protobuf.Timestamp
	0,  // 4: qwibi.v1.RegisterPushTokenRequest.platform:type_name -> qwibi.v1.PushPlatform
	12, // 5: qwibi.v1.ListPushTokensRequest.page:type_name -> qwibi.v1.PageRequest
	2,  // 6: qwibi.v1.ListPushTokensResponse.tokens:type_name -> qwibi.v1.PushTokenInfo
	13, // 7: qwibi.v1.ListPushTokensResponse.page:type_name -> qwibi.v1.PageResponse
	1,  // 8: qwibi.v1.SetLayerNotifyPolicyRequest.policy:type_name -> qwibi.v1.LayerNotifyPolicy
	1,  // 9: qwibi.v1.SetLayerNotifyPolicyResponse.effective_policy:type_name -> qwibi.v1.LayerNotifyPolicy
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_qwibi_v1_push_proto_init() }
func file_qwibi_v1_push_proto_init() {
	if File_qwibi_v1_push_proto != nil {
		return
	}
	file_qwibi_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qwibi_v1_push_proto_rawDesc), len(file_qwibi_v1_push_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qwibi_v1_push_proto_goTypes,
		DependencyIndexes: file_qwibi_v1_push_proto_depIdxs,
		EnumInfos:         file_qwibi_v1_push_proto_enumTypes,
		MessageInfos:      file_qwibi_v1_push_proto_msgTypes,
	}.Build()
	File_qwibi_v1_push_proto = out.File
	file_qwibi_v1_push_proto_goTypes = nil
	file_qwibi_v1_push_proto_depIdxs = nil
}
